package com.device.business.equip.service.element;

import javax.ws.rs.FormParam;

public class SectionElement {
	@FormParam("sectionName")
	private String sectionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_section_info.Section_Leader
     *
     * @mbg.generated Tue Jan 03 19:48:23 CST 2017
     */
	@FormParam("sectionLeader")
    private String sectionLeader;
	
	/**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_luding_section_info.Project_Name
    *
    * @mbg.generated Tue Jan 03 19:48:23 CST 2017
    */
	@FormParam("projectId")
   private Integer projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_section_info.Project_Name
     *
     * @mbg.generated Tue Jan 03 19:48:23 CST 2017
     */
	@FormParam("projectName")
    private String projectName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_section_info.Contract_number
     *
     * @mbg.generated Tue Jan 03 19:48:23 CST 2017
     */
	@FormParam("contractNumber")
    private String contractNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_section_info.Parameter1
     *
     * @mbg.generated Tue Jan 03 19:48:23 CST 2017
     */
    private String parameter1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_section_info.Parameter2
     *
     * @mbg.generated Tue Jan 03 19:48:23 CST 2017
     */
    private String parameter2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_section_info.Parameter3
     *
     * @mbg.generated Tue Jan 03 19:48:23 CST 2017
     */
    private String parameter3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_section_info.Section_Name
     *
     * @return the value of t_luding_section_info.Section_Name
     *
     * @mbg.generated Tue Jan 03 19:48:23 CST 2017
     */
    public String getSectionName() {
        return sectionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_section_info.Section_Name
     *
     * @param sectionName the value for t_luding_section_info.Section_Name
     *
     * @mbg.generated Tue Jan 03 19:48:23 CST 2017
     */
    public void setSectionName(String sectionName) {
        this.sectionName = sectionName == null ? null : sectionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_section_info.Section_Leader
     *
     * @return the value of t_luding_section_info.Section_Leader
     *
     * @mbg.generated Tue Jan 03 19:48:23 CST 2017
     */
    public String getSectionLeader() {
        return sectionLeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_section_info.Section_Leader
     *
     * @param sectionLeader the value for t_luding_section_info.Section_Leader
     *
     * @mbg.generated Tue Jan 03 19:48:23 CST 2017
     */
    public void setSectionLeader(String sectionLeader) {
        this.sectionLeader = sectionLeader == null ? null : sectionLeader.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_section_info.Project_Name
     *
     * @return the value of t_luding_section_info.Project_Name
     *
     * @mbg.generated Tue Jan 03 19:48:23 CST 2017
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_section_info.Project_Name
     *
     * @param projectName the value for t_luding_section_info.Project_Name
     *
     * @mbg.generated Tue Jan 03 19:48:23 CST 2017
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }
    
    

    public Integer getProjectId() {
		return projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_section_info.Contract_number
     *
     * @return the value of t_luding_section_info.Contract_number
     *
     * @mbg.generated Tue Jan 03 19:48:23 CST 2017
     */
    public String getContractNumber() {
        return contractNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_section_info.Contract_number
     *
     * @param contractNumber the value for t_luding_section_info.Contract_number
     *
     * @mbg.generated Tue Jan 03 19:48:23 CST 2017
     */
    public void setContractNumber(String contractNumber) {
        this.contractNumber = contractNumber == null ? null : contractNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_section_info.Parameter1
     *
     * @return the value of t_luding_section_info.Parameter1
     *
     * @mbg.generated Tue Jan 03 19:48:23 CST 2017
     */
    public String getParameter1() {
        return parameter1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_section_info.Parameter1
     *
     * @param parameter1 the value for t_luding_section_info.Parameter1
     *
     * @mbg.generated Tue Jan 03 19:48:23 CST 2017
     */
    public void setParameter1(String parameter1) {
        this.parameter1 = parameter1 == null ? null : parameter1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_section_info.Parameter2
     *
     * @return the value of t_luding_section_info.Parameter2
     *
     * @mbg.generated Tue Jan 03 19:48:23 CST 2017
     */
    public String getParameter2() {
        return parameter2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_section_info.Parameter2
     *
     * @param parameter2 the value for t_luding_section_info.Parameter2
     *
     * @mbg.generated Tue Jan 03 19:48:23 CST 2017
     */
    public void setParameter2(String parameter2) {
        this.parameter2 = parameter2 == null ? null : parameter2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_section_info.Parameter3
     *
     * @return the value of t_luding_section_info.Parameter3
     *
     * @mbg.generated Tue Jan 03 19:48:23 CST 2017
     */
    public String getParameter3() {
        return parameter3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_section_info.Parameter3
     *
     * @param parameter3 the value for t_luding_section_info.Parameter3
     *
     * @mbg.generated Tue Jan 03 19:48:23 CST 2017
     */
    public void setParameter3(String parameter3) {
        this.parameter3 = parameter3 == null ? null : parameter3.trim();
    }
}
