package com.device.business.equip.dao.mapper;

import com.device.business.equip.bean.PileBean;
import com.device.business.equip.bean.PileBeanExample;
import com.device.business.equip.bean.PileEquipBean;
import com.device.business.equip.bean.PileEquipBeanExample;
import com.device.business.equip.bean.SectionPileBean;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PileBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_pile_info
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    long countByExample(PileBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_pile_info
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    int deleteByExample(PileBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_pile_info
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    int insert(PileBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_pile_info
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    int insertSelective(PileBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_pile_info
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    List<PileBean> selectByExample(PileBeanExample example,RowBounds rowBounds);
    
    List<PileBean> selectAll(PileBeanExample example);
    
    PileBean selectById(@Param("id")String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_pile_info
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    int updateByExampleSelective(@Param("record") PileBean record, @Param("example") PileBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_pile_info
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    int updateByExample(@Param("record") PileBean record, @Param("example") PileBeanExample example);
    
    List<SectionPileBean> sectionPileInfo(@Param("userId") String userId,@Param("dateInfo") String  dateInfo);

    List<PileBean> selectByProjectId(@Param("projectId") String projectId, @Param("start") int start, @Param("limit") int limit);
}