package com.device.business.equip.dao.mapper;

import com.device.business.equip.bean.PileEquipBean;
import com.device.business.equip.bean.PileEquipBeanExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PileEquipBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_pile_equipment
     *
     * @mbg.generated Tue Jan 03 21:18:55 CST 2017
     */
    long countByExample(PileEquipBeanExample example);
    List<PileEquipBean> selectByExample(PileEquipBeanExample example,RowBounds rowBounds);
    
    int insert(PileEquipBean record);
    
    PileEquipBean selectById(@Param("id")String id);
    
    int updateById(@Param("record") PileEquipBean record);
    
    int deleteById(@Param("id")String id);
    
}