package com.device.business.equip.dao.mapper;

import com.device.business.equip.bean.ProjectBean;
import com.device.business.equip.bean.ProjectBeanExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ProjectBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_project_info
     *
     * @mbg.generated Tue Jan 03 19:48:23 CST 2017
     */
    long countByExample(ProjectBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_project_info
     *
     * @mbg.generated Tue Jan 03 19:48:23 CST 2017
     */
    int deleteByExample(ProjectBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_project_info
     *
     * @mbg.generated Tue Jan 03 19:48:23 CST 2017
     */
    int insert(ProjectBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_project_info
     *
     * @mbg.generated Tue Jan 03 19:48:23 CST 2017
     */
    int insertSelective(ProjectBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_project_info
     *
     * @mbg.generated Tue Jan 03 19:48:23 CST 2017
     */
    List<ProjectBean> selectByExample(ProjectBeanExample example,RowBounds rowBunds);
    
    List<ProjectBean> selectAll();
    
    ProjectBean selectById(@Param("id") String id);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_project_info
     *
     * @mbg.generated Tue Jan 03 19:48:23 CST 2017
     */
    int updateByExample(@Param("record") ProjectBean record);
}