package com.device.business.equip.dao.mapper;

import com.device.business.equip.bean.SlurryRecordBean;
import com.device.business.equip.bean.SlurryRecordBeanExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SlurryRecordBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_slurry_mix_record
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    long countByExample(SlurryRecordBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_slurry_mix_record
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    int deleteByExample(SlurryRecordBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_slurry_mix_record
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_slurry_mix_record
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    int insert(SlurryRecordBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_slurry_mix_record
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    int insertSelective(SlurryRecordBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_slurry_mix_record
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    List<SlurryRecordBean> selectByExample(SlurryRecordBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_slurry_mix_record
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    SlurryRecordBean selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_slurry_mix_record
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    int updateByExampleSelective(@Param("record") SlurryRecordBean record, @Param("example") SlurryRecordBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_slurry_mix_record
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    int updateByExample(@Param("record") SlurryRecordBean record, @Param("example") SlurryRecordBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_slurry_mix_record
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    int updateByPrimaryKeySelective(SlurryRecordBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_slurry_mix_record
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    int updateByPrimaryKey(SlurryRecordBean record);
}