package com.device.business.equip.dao.mapper;

import com.device.business.equip.bean.SlurryAmountBean;
import com.device.business.equip.bean.SlurryAmountBeanExample;
import com.device.business.equip.bean.SlurryAmountBeanKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SlurryAmountBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_slurry_amount
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    long countByExample(SlurryAmountBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_slurry_amount
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    int deleteByExample(SlurryAmountBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_slurry_amount
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    int deleteByPrimaryKey(SlurryAmountBeanKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_slurry_amount
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    int insert(SlurryAmountBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_slurry_amount
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    int insertSelective(SlurryAmountBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_slurry_amount
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    List<SlurryAmountBean> selectByExample(SlurryAmountBeanExample example);
    
    List<SlurryAmountBean> selectByProject(SlurryAmountBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_slurry_amount
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    SlurryAmountBean selectByPrimaryKey(SlurryAmountBeanKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_slurry_amount
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    int updateByExampleSelective(@Param("record") SlurryAmountBean record, @Param("example") SlurryAmountBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_slurry_amount
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    int updateByExample(@Param("record") SlurryAmountBean record, @Param("example") SlurryAmountBeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_slurry_amount
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    int updateByPrimaryKeySelective(SlurryAmountBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_slurry_amount
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    int updateByPrimaryKey(SlurryAmountBean record);
}