package com.device.business.equip.bean;

import java.util.Date;

import javax.ws.rs.FormParam;

public class MixEquipBean {
	
	@FormParam("projectName")
	private String projectName;
	
	@FormParam("sectionName")
	private String sectionName;
	
	
    public String getProjectName() {
		return projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	public String getSectionName() {
		return sectionName;
	}

	public void setSectionName(String sectionName) {
		this.sectionName = sectionName;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_mix_equipment.Equipment_ID
     *
     * @mbg.generated Tue Jan 03 21:18:55 CST 2017
     */
	@FormParam("equipmentId")
    private String equipmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_mix_equipment.Equipment_Name
     *
     * @mbg.generated Tue Jan 03 21:18:55 CST 2017
     */
	@FormParam("equipmentName")
    private String equipmentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_mix_equipment.Equipment_Code
     *
     * @mbg.generated Tue Jan 03 21:18:55 CST 2017
     */
	@FormParam("equipmentCode")
    private String equipmentCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_mix_equipment.Equipment_Type
     *
     * @mbg.generated Tue Jan 03 21:18:55 CST 2017
     */
	@FormParam("equipmentType")
    private String equipmentType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_mix_equipment.Start_Time
     *
     * @mbg.generated Tue Jan 03 21:18:55 CST 2017
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_mix_equipment.Stop_Time
     *
     * @mbg.generated Tue Jan 03 21:18:55 CST 2017
     */
    private Date stopTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_mix_equipment.Section_ID
     *
     * @mbg.generated Tue Jan 03 21:18:55 CST 2017
     */
	@FormParam("sectionId")
    private Integer sectionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_mix_equipment.Project_ID
     *
     * @mbg.generated Tue Jan 03 21:18:55 CST 2017
     */
	@FormParam("projectId")
    private Integer projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_mix_equipment.Equipment_Status
     *
     * @mbg.generated Tue Jan 03 21:18:55 CST 2017
     */
	@FormParam("equipmentStatus")
    private String equipmentStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_mix_equipment.Project_Status
     *
     * @mbg.generated Tue Jan 03 21:18:55 CST 2017
     */
	@FormParam("projectStatus")
    private String projectStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_mix_equipment.Supervision_Status
     *
     * @mbg.generated Tue Jan 03 21:18:55 CST 2017
     */
	@FormParam("supervisionStatus")
    private String supervisionStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_mix_equipment.Create_Time
     *
     * @mbg.generated Tue Jan 03 21:18:55 CST 2017
     */
	
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_mix_equipment.Equipment_ID
     *
     * @return the value of t_luding_mix_equipment.Equipment_ID
     *
     * @mbg.generated Tue Jan 03 21:18:55 CST 2017
     */
    public String getEquipmentId() {
        return equipmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_mix_equipment.Equipment_ID
     *
     * @param equipmentId the value for t_luding_mix_equipment.Equipment_ID
     *
     * @mbg.generated Tue Jan 03 21:18:55 CST 2017
     */
    public void setEquipmentId(String equipmentId) {
        this.equipmentId = equipmentId == null ? null : equipmentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_mix_equipment.Equipment_Name
     *
     * @return the value of t_luding_mix_equipment.Equipment_Name
     *
     * @mbg.generated Tue Jan 03 21:18:55 CST 2017
     */
    public String getEquipmentName() {
        return equipmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_mix_equipment.Equipment_Name
     *
     * @param equipmentName the value for t_luding_mix_equipment.Equipment_Name
     *
     * @mbg.generated Tue Jan 03 21:18:55 CST 2017
     */
    public void setEquipmentName(String equipmentName) {
        this.equipmentName = equipmentName == null ? null : equipmentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_mix_equipment.Equipment_Code
     *
     * @return the value of t_luding_mix_equipment.Equipment_Code
     *
     * @mbg.generated Tue Jan 03 21:18:55 CST 2017
     */
    public String getEquipmentCode() {
        return equipmentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_mix_equipment.Equipment_Code
     *
     * @param equipmentCode the value for t_luding_mix_equipment.Equipment_Code
     *
     * @mbg.generated Tue Jan 03 21:18:55 CST 2017
     */
    public void setEquipmentCode(String equipmentCode) {
        this.equipmentCode = equipmentCode == null ? null : equipmentCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_mix_equipment.Equipment_Type
     *
     * @return the value of t_luding_mix_equipment.Equipment_Type
     *
     * @mbg.generated Tue Jan 03 21:18:55 CST 2017
     */
    public String getEquipmentType() {
        return equipmentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_mix_equipment.Equipment_Type
     *
     * @param equipmentType the value for t_luding_mix_equipment.Equipment_Type
     *
     * @mbg.generated Tue Jan 03 21:18:55 CST 2017
     */
    public void setEquipmentType(String equipmentType) {
        this.equipmentType = equipmentType == null ? null : equipmentType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_mix_equipment.Start_Time
     *
     * @return the value of t_luding_mix_equipment.Start_Time
     *
     * @mbg.generated Tue Jan 03 21:18:55 CST 2017
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_mix_equipment.Start_Time
     *
     * @param startTime the value for t_luding_mix_equipment.Start_Time
     *
     * @mbg.generated Tue Jan 03 21:18:55 CST 2017
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_mix_equipment.Stop_Time
     *
     * @return the value of t_luding_mix_equipment.Stop_Time
     *
     * @mbg.generated Tue Jan 03 21:18:55 CST 2017
     */
    public Date getStopTime() {
        return stopTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_mix_equipment.Stop_Time
     *
     * @param stopTime the value for t_luding_mix_equipment.Stop_Time
     *
     * @mbg.generated Tue Jan 03 21:18:55 CST 2017
     */
    public void setStopTime(Date stopTime) {
        this.stopTime = stopTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_mix_equipment.Section_ID
     *
     * @return the value of t_luding_mix_equipment.Section_ID
     *
     * @mbg.generated Tue Jan 03 21:18:55 CST 2017
     */
    public Integer getSectionId() {
        return sectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_mix_equipment.Section_ID
     *
     * @param sectionId the value for t_luding_mix_equipment.Section_ID
     *
     * @mbg.generated Tue Jan 03 21:18:55 CST 2017
     */
    public void setSectionId(Integer sectionId) {
        this.sectionId = sectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_mix_equipment.Project_ID
     *
     * @return the value of t_luding_mix_equipment.Project_ID
     *
     * @mbg.generated Tue Jan 03 21:18:55 CST 2017
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_mix_equipment.Project_ID
     *
     * @param projectId the value for t_luding_mix_equipment.Project_ID
     *
     * @mbg.generated Tue Jan 03 21:18:55 CST 2017
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_mix_equipment.Equipment_Status
     *
     * @return the value of t_luding_mix_equipment.Equipment_Status
     *
     * @mbg.generated Tue Jan 03 21:18:55 CST 2017
     */
    public String getEquipmentStatus() {
        return equipmentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_mix_equipment.Equipment_Status
     *
     * @param equipmentStatus the value for t_luding_mix_equipment.Equipment_Status
     *
     * @mbg.generated Tue Jan 03 21:18:55 CST 2017
     */
    public void setEquipmentStatus(String equipmentStatus) {
        this.equipmentStatus = equipmentStatus == null ? null : equipmentStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_mix_equipment.Project_Status
     *
     * @return the value of t_luding_mix_equipment.Project_Status
     *
     * @mbg.generated Tue Jan 03 21:18:55 CST 2017
     */
    public String getProjectStatus() {
        return projectStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_mix_equipment.Project_Status
     *
     * @param projectStatus the value for t_luding_mix_equipment.Project_Status
     *
     * @mbg.generated Tue Jan 03 21:18:55 CST 2017
     */
    public void setProjectStatus(String projectStatus) {
        this.projectStatus = projectStatus == null ? null : projectStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_mix_equipment.Supervision_Status
     *
     * @return the value of t_luding_mix_equipment.Supervision_Status
     *
     * @mbg.generated Tue Jan 03 21:18:55 CST 2017
     */
    public String getSupervisionStatus() {
        return supervisionStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_mix_equipment.Supervision_Status
     *
     * @param supervisionStatus the value for t_luding_mix_equipment.Supervision_Status
     *
     * @mbg.generated Tue Jan 03 21:18:55 CST 2017
     */
    public void setSupervisionStatus(String supervisionStatus) {
        this.supervisionStatus = supervisionStatus == null ? null : supervisionStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_mix_equipment.Create_Time
     *
     * @return the value of t_luding_mix_equipment.Create_Time
     *
     * @mbg.generated Tue Jan 03 21:18:55 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_mix_equipment.Create_Time
     *
     * @param createTime the value for t_luding_mix_equipment.Create_Time
     *
     * @mbg.generated Tue Jan 03 21:18:55 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}