package com.device.business.equip.bean;

import java.math.BigDecimal;
import java.util.Date;

public class PileBean {
	
	private String mixStationNumber;


    public String getMixStationNumber() {
		return mixStationNumber;
	}

	public void setMixStationNumber(String mixStationNumber) {
		this.mixStationNumber = mixStationNumber;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_pile_info.id
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_pile_info.Pile_Number
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    private String pileNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_pile_info.Start_Time
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_pile_info.End_Time
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_pile_info.Pile_Length
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    private BigDecimal pileLength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_pile_info.Guniting_Second
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    private Short gunitingSecond;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_pile_info.Total_Liquid
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    private BigDecimal totalLiquid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_pile_info.Total_Cement
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    private BigDecimal totalCement;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_pile_info.Max_Down_Speed
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    private BigDecimal maxDownSpeed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_pile_info.Max_Up_Speed
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    private BigDecimal maxUpSpeed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_pile_info.Max_Inside_Power
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    private BigDecimal maxInsidePower;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_pile_info.Max_Outside_Power
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    private BigDecimal maxOutsidePower;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_pile_info.Max_Lean
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    private BigDecimal maxLean;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_pile_info.Guniting_Begin_Time
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    private Date gunitingBeginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_pile_info.Guniting_End_Time
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    private Date gunitingEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_pile_info.Pile_Driver_Number
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    private String pileDriverNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_pile_info.Create_Time
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_pile_info.Change_Time
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    private Date changeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_pile_info.Section_Number
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    private String sectionNumber;


    /**
    *
    * This field was generated by MyBatis Generator.
    * This field corresponds to the database column t_luding_pile_info.Project_ID
    *
    * @mbg.generated Fri Jan 06 20:24:15 CST 2017
    */
   private String projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_pile_info.Pile_Status
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    private Integer pileStatus;
    
    private Integer score;
    
    private String scoreMark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_pile_info.xmid
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    private Byte xmid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_pile_info.zjid
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    private Integer zjid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_pile_info.Enlarge_Top
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    private BigDecimal enlargeTop;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_pile_info.Enlarge_Bottom
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    private BigDecimal enlargeBottom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_pile_info.Enlarge_Height
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    private BigDecimal enlargeHeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_pile_info.t_yl
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    private Byte tYl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_pile_info.t_cxs
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    private BigDecimal tCxs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_pile_info.t_jxs
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    private BigDecimal tJxs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_pile_info.sjzc
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    private BigDecimal sjzc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_pile_info.zhl
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    private BigDecimal zhl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_pile_info.zjl
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    private BigDecimal zjl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_pile_info.sj_zc
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    private BigDecimal sjZc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_pile_info.sj_hl
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    private BigDecimal sjHl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_pile_info.sj_jl
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    private BigDecimal sjJl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_pile_info.upid
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    private Byte upid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_pile_info.id
     *
     * @return the value of t_luding_pile_info.id
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_pile_info.id
     *
     * @param id the value for t_luding_pile_info.id
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_pile_info.Pile_Number
     *
     * @return the value of t_luding_pile_info.Pile_Number
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public String getPileNumber() {
        return pileNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_pile_info.Pile_Number
     *
     * @param pileNumber the value for t_luding_pile_info.Pile_Number
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public void setPileNumber(String pileNumber) {
        this.pileNumber = pileNumber == null ? null : pileNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_pile_info.Start_Time
     *
     * @return the value of t_luding_pile_info.Start_Time
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_pile_info.Start_Time
     *
     * @param startTime the value for t_luding_pile_info.Start_Time
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_pile_info.End_Time
     *
     * @return the value of t_luding_pile_info.End_Time
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_pile_info.End_Time
     *
     * @param endTime the value for t_luding_pile_info.End_Time
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_pile_info.Pile_Length
     *
     * @return the value of t_luding_pile_info.Pile_Length
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public BigDecimal getPileLength() {
        return pileLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_pile_info.Pile_Length
     *
     * @param pileLength the value for t_luding_pile_info.Pile_Length
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public void setPileLength(BigDecimal pileLength) {
        this.pileLength = pileLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_pile_info.Guniting_Second
     *
     * @return the value of t_luding_pile_info.Guniting_Second
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public Short getGunitingSecond() {
        return gunitingSecond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_pile_info.Guniting_Second
     *
     * @param gunitingSecond the value for t_luding_pile_info.Guniting_Second
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public void setGunitingSecond(Short gunitingSecond) {
        this.gunitingSecond = gunitingSecond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_pile_info.Total_Liquid
     *
     * @return the value of t_luding_pile_info.Total_Liquid
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public BigDecimal getTotalLiquid() {
        return totalLiquid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_pile_info.Total_Liquid
     *
     * @param totalLiquid the value for t_luding_pile_info.Total_Liquid
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public void setTotalLiquid(BigDecimal totalLiquid) {
        this.totalLiquid = totalLiquid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_pile_info.Total_Cement
     *
     * @return the value of t_luding_pile_info.Total_Cement
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public BigDecimal getTotalCement() {
        return totalCement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_pile_info.Total_Cement
     *
     * @param totalCement the value for t_luding_pile_info.Total_Cement
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public void setTotalCement(BigDecimal totalCement) {
        this.totalCement = totalCement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_pile_info.Max_Down_Speed
     *
     * @return the value of t_luding_pile_info.Max_Down_Speed
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public BigDecimal getMaxDownSpeed() {
        return maxDownSpeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_pile_info.Max_Down_Speed
     *
     * @param maxDownSpeed the value for t_luding_pile_info.Max_Down_Speed
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public void setMaxDownSpeed(BigDecimal maxDownSpeed) {
        this.maxDownSpeed = maxDownSpeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_pile_info.Max_Up_Speed
     *
     * @return the value of t_luding_pile_info.Max_Up_Speed
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public BigDecimal getMaxUpSpeed() {
        return maxUpSpeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_pile_info.Max_Up_Speed
     *
     * @param maxUpSpeed the value for t_luding_pile_info.Max_Up_Speed
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public void setMaxUpSpeed(BigDecimal maxUpSpeed) {
        this.maxUpSpeed = maxUpSpeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_pile_info.Max_Inside_Power
     *
     * @return the value of t_luding_pile_info.Max_Inside_Power
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public BigDecimal getMaxInsidePower() {
        return maxInsidePower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_pile_info.Max_Inside_Power
     *
     * @param maxInsidePower the value for t_luding_pile_info.Max_Inside_Power
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public void setMaxInsidePower(BigDecimal maxInsidePower) {
        this.maxInsidePower = maxInsidePower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_pile_info.Max_Outside_Power
     *
     * @return the value of t_luding_pile_info.Max_Outside_Power
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public BigDecimal getMaxOutsidePower() {
        return maxOutsidePower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_pile_info.Max_Outside_Power
     *
     * @param maxOutsidePower the value for t_luding_pile_info.Max_Outside_Power
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public void setMaxOutsidePower(BigDecimal maxOutsidePower) {
        this.maxOutsidePower = maxOutsidePower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_pile_info.Max_Lean
     *
     * @return the value of t_luding_pile_info.Max_Lean
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public BigDecimal getMaxLean() {
        return maxLean;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_pile_info.Max_Lean
     *
     * @param maxLean the value for t_luding_pile_info.Max_Lean
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public void setMaxLean(BigDecimal maxLean) {
        this.maxLean = maxLean;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_pile_info.Guniting_Begin_Time
     *
     * @return the value of t_luding_pile_info.Guniting_Begin_Time
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public Date getGunitingBeginTime() {
        return gunitingBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_pile_info.Guniting_Begin_Time
     *
     * @param gunitingBeginTime the value for t_luding_pile_info.Guniting_Begin_Time
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public void setGunitingBeginTime(Date gunitingBeginTime) {
        this.gunitingBeginTime = gunitingBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_pile_info.Guniting_End_Time
     *
     * @return the value of t_luding_pile_info.Guniting_End_Time
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public Date getGunitingEndTime() {
        return gunitingEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_pile_info.Guniting_End_Time
     *
     * @param gunitingEndTime the value for t_luding_pile_info.Guniting_End_Time
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public void setGunitingEndTime(Date gunitingEndTime) {
        this.gunitingEndTime = gunitingEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_pile_info.Pile_Driver_Number
     *
     * @return the value of t_luding_pile_info.Pile_Driver_Number
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public String getPileDriverNumber() {
        return pileDriverNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_pile_info.Pile_Driver_Number
     *
     * @param pileDriverNumber the value for t_luding_pile_info.Pile_Driver_Number
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public void setPileDriverNumber(String pileDriverNumber) {
        this.pileDriverNumber = pileDriverNumber == null ? null : pileDriverNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_pile_info.Create_Time
     *
     * @return the value of t_luding_pile_info.Create_Time
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_pile_info.Create_Time
     *
     * @param createTime the value for t_luding_pile_info.Create_Time
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_pile_info.Change_Time
     *
     * @return the value of t_luding_pile_info.Change_Time
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public Date getChangeTime() {
        return changeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_pile_info.Change_Time
     *
     * @param changeTime the value for t_luding_pile_info.Change_Time
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public void setChangeTime(Date changeTime) {
        this.changeTime = changeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_pile_info.Section_Number
     *
     * @return the value of t_luding_pile_info.Section_Number
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public String getSectionNumber() {
        return sectionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_pile_info.Section_Number
     *
     * @param sectionNumber the value for t_luding_pile_info.Section_Number
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public void setSectionNumber(String sectionNumber) {
        this.sectionNumber = sectionNumber == null ? null : sectionNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_pile_info.Pile_Status
     *
     * @return the value of t_luding_pile_info.Pile_Status
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public Integer getPileStatus() {
        return pileStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_pile_info.Pile_Status
     *
     * @param pileStatus the value for t_luding_pile_info.Pile_Status
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public void setPileStatus(Integer pileStatus) {
        this.pileStatus = pileStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_pile_info.xmid
     *
     * @return the value of t_luding_pile_info.xmid
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public Byte getXmid() {
        return xmid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_pile_info.xmid
     *
     * @param xmid the value for t_luding_pile_info.xmid
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public void setXmid(Byte xmid) {
        this.xmid = xmid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_pile_info.zjid
     *
     * @return the value of t_luding_pile_info.zjid
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public Integer getZjid() {
        return zjid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_pile_info.zjid
     *
     * @param zjid the value for t_luding_pile_info.zjid
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public void setZjid(Integer zjid) {
        this.zjid = zjid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_pile_info.Enlarge_Top
     *
     * @return the value of t_luding_pile_info.Enlarge_Top
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public BigDecimal getEnlargeTop() {
        return enlargeTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_pile_info.Enlarge_Top
     *
     * @param enlargeTop the value for t_luding_pile_info.Enlarge_Top
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public void setEnlargeTop(BigDecimal enlargeTop) {
        this.enlargeTop = enlargeTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_pile_info.Enlarge_Bottom
     *
     * @return the value of t_luding_pile_info.Enlarge_Bottom
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public BigDecimal getEnlargeBottom() {
        return enlargeBottom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_pile_info.Enlarge_Bottom
     *
     * @param enlargeBottom the value for t_luding_pile_info.Enlarge_Bottom
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public void setEnlargeBottom(BigDecimal enlargeBottom) {
        this.enlargeBottom = enlargeBottom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_pile_info.Enlarge_Height
     *
     * @return the value of t_luding_pile_info.Enlarge_Height
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public BigDecimal getEnlargeHeight() {
        return enlargeHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_pile_info.Enlarge_Height
     *
     * @param enlargeHeight the value for t_luding_pile_info.Enlarge_Height
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public void setEnlargeHeight(BigDecimal enlargeHeight) {
        this.enlargeHeight = enlargeHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_pile_info.t_yl
     *
     * @return the value of t_luding_pile_info.t_yl
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public Byte gettYl() {
        return tYl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_pile_info.t_yl
     *
     * @param tYl the value for t_luding_pile_info.t_yl
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public void settYl(Byte tYl) {
        this.tYl = tYl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_pile_info.t_cxs
     *
     * @return the value of t_luding_pile_info.t_cxs
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public BigDecimal gettCxs() {
        return tCxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_pile_info.t_cxs
     *
     * @param tCxs the value for t_luding_pile_info.t_cxs
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public void settCxs(BigDecimal tCxs) {
        this.tCxs = tCxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_pile_info.t_jxs
     *
     * @return the value of t_luding_pile_info.t_jxs
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public BigDecimal gettJxs() {
        return tJxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_pile_info.t_jxs
     *
     * @param tJxs the value for t_luding_pile_info.t_jxs
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public void settJxs(BigDecimal tJxs) {
        this.tJxs = tJxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_pile_info.sjzc
     *
     * @return the value of t_luding_pile_info.sjzc
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public BigDecimal getSjzc() {
        return sjzc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_pile_info.sjzc
     *
     * @param sjzc the value for t_luding_pile_info.sjzc
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public void setSjzc(BigDecimal sjzc) {
        this.sjzc = sjzc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_pile_info.zhl
     *
     * @return the value of t_luding_pile_info.zhl
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public BigDecimal getZhl() {
        return zhl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_pile_info.zhl
     *
     * @param zhl the value for t_luding_pile_info.zhl
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public void setZhl(BigDecimal zhl) {
        this.zhl = zhl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_pile_info.zjl
     *
     * @return the value of t_luding_pile_info.zjl
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public BigDecimal getZjl() {
        return zjl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_pile_info.zjl
     *
     * @param zjl the value for t_luding_pile_info.zjl
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public void setZjl(BigDecimal zjl) {
        this.zjl = zjl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_pile_info.sj_zc
     *
     * @return the value of t_luding_pile_info.sj_zc
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public BigDecimal getSjZc() {
        return sjZc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_pile_info.sj_zc
     *
     * @param sjZc the value for t_luding_pile_info.sj_zc
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public void setSjZc(BigDecimal sjZc) {
        this.sjZc = sjZc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_pile_info.sj_hl
     *
     * @return the value of t_luding_pile_info.sj_hl
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public BigDecimal getSjHl() {
        return sjHl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_pile_info.sj_hl
     *
     * @param sjHl the value for t_luding_pile_info.sj_hl
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public void setSjHl(BigDecimal sjHl) {
        this.sjHl = sjHl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_pile_info.sj_jl
     *
     * @return the value of t_luding_pile_info.sj_jl
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public BigDecimal getSjJl() {
        return sjJl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_pile_info.sj_jl
     *
     * @param sjJl the value for t_luding_pile_info.sj_jl
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public void setSjJl(BigDecimal sjJl) {
        this.sjJl = sjJl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_pile_info.upid
     *
     * @return the value of t_luding_pile_info.upid
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public Byte getUpid() {
        return upid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_pile_info.upid
     *
     * @param upid the value for t_luding_pile_info.upid
     *
     * @mbg.generated Fri Jan 06 20:24:15 CST 2017
     */
    public void setUpid(Byte upid) {
        this.upid = upid;
    }

	public Integer getScore() {
		return score;
	}

	public void setScore(Integer score) {
		this.score = score;
	}

    public String getScoreMark() {
        return scoreMark;
    }

    public void setScoreMark(String scoreMark) {
        this.scoreMark = scoreMark;
    }


    public String getProjectId() {
		return projectId;
	}

	public void setProjectId(String projectId) {
		this.projectId = projectId;
	}


    
    
}