package com.device.business.equip.bean;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PileBeanExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_luding_pile_info
     *
     * @mbg.generated Sat Jan 14 21:44:26 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_luding_pile_info
     *
     * @mbg.generated Sat Jan 14 21:44:26 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_luding_pile_info
     *
     * @mbg.generated Sat Jan 14 21:44:26 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_pile_info
     *
     * @mbg.generated Sat Jan 14 21:44:26 CST 2017
     */
    public PileBeanExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_pile_info
     *
     * @mbg.generated Sat Jan 14 21:44:26 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_pile_info
     *
     * @mbg.generated Sat Jan 14 21:44:26 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_pile_info
     *
     * @mbg.generated Sat Jan 14 21:44:26 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_pile_info
     *
     * @mbg.generated Sat Jan 14 21:44:26 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_pile_info
     *
     * @mbg.generated Sat Jan 14 21:44:26 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_pile_info
     *
     * @mbg.generated Sat Jan 14 21:44:26 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_pile_info
     *
     * @mbg.generated Sat Jan 14 21:44:26 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_pile_info
     *
     * @mbg.generated Sat Jan 14 21:44:26 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_pile_info
     *
     * @mbg.generated Sat Jan 14 21:44:26 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_pile_info
     *
     * @mbg.generated Sat Jan 14 21:44:26 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_luding_pile_info
     *
     * @mbg.generated Sat Jan 14 21:44:26 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }
        
        

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPileNumberIsNull() {
            addCriterion("Pile_Number is null");
            return (Criteria) this;
        }

        public Criteria andPileNumberIsNotNull() {
            addCriterion("Pile_Number is not null");
            return (Criteria) this;
        }

        public Criteria andPileNumberEqualTo(String value) {
            addCriterion("Pile_Number =", value, "pileNumber");
            return (Criteria) this;
        }

        public Criteria andPileNumberNotEqualTo(String value) {
            addCriterion("Pile_Number <>", value, "pileNumber");
            return (Criteria) this;
        }

        public Criteria andPileNumberGreaterThan(String value) {
            addCriterion("Pile_Number >", value, "pileNumber");
            return (Criteria) this;
        }

        public Criteria andPileNumberGreaterThanOrEqualTo(String value) {
            addCriterion("Pile_Number >=", value, "pileNumber");
            return (Criteria) this;
        }

        public Criteria andPileNumberLessThan(String value) {
            addCriterion("Pile_Number <", value, "pileNumber");
            return (Criteria) this;
        }

        public Criteria andPileNumberLessThanOrEqualTo(String value) {
            addCriterion("Pile_Number <=", value, "pileNumber");
            return (Criteria) this;
        }

        public Criteria andPileNumberLike(String value) {
            addCriterion("Pile_Number like", value, "pileNumber");
            return (Criteria) this;
        }

        public Criteria andProjectIdEqualTo(String value) {
            addCriterion("Project_ID =", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andPileNumberNotLike(String value) {
            addCriterion("Pile_Number not like", value, "pileNumber");
            return (Criteria) this;
        }

        public Criteria andPileNumberIn(List<String> values) {
            addCriterion("Pile_Number in", values, "pileNumber");
            return (Criteria) this;
        }

        public Criteria andPileNumberNotIn(List<String> values) {
            addCriterion("Pile_Number not in", values, "pileNumber");
            return (Criteria) this;
        }

        public Criteria andPileNumberBetween(String value1, String value2) {
            addCriterion("Pile_Number between", value1, value2, "pileNumber");
            return (Criteria) this;
        }

        public Criteria andPileNumberNotBetween(String value1, String value2) {
            addCriterion("Pile_Number not between", value1, value2, "pileNumber");
            return (Criteria) this;
        }

        public Criteria andPileDriverNumberIsNull() {
            addCriterion("Pile_Driver_Number is null");
            return (Criteria) this;
        }

        public Criteria andPileDriverNumberIsNotNull() {
            addCriterion("Pile_Driver_Number is not null");
            return (Criteria) this;
        }

        public Criteria andPileDriverNumberEqualTo(String value) {
            addCriterion("Pile_Driver_Number =", value, "pileDriverNumber");
            return (Criteria) this;
        }

        public Criteria andPileDriverNumberNotEqualTo(String value) {
            addCriterion("Pile_Driver_Number <>", value, "pileDriverNumber");
            return (Criteria) this;
        }

        public Criteria andPileDriverNumberGreaterThan(String value) {
            addCriterion("Pile_Driver_Number >", value, "pileDriverNumber");
            return (Criteria) this;
        }

        public Criteria andPileDriverNumberGreaterThanOrEqualTo(String value) {
            addCriterion("Pile_Driver_Number >=", value, "pileDriverNumber");
            return (Criteria) this;
        }

        public Criteria andPileDriverNumberLessThan(String value) {
            addCriterion("Pile_Driver_Number <", value, "pileDriverNumber");
            return (Criteria) this;
        }
        
        public Criteria andPileDriverNumberLessThanOrEqualTo(String value) {
            addCriterion("Pile_Driver_Number <=", value, "pileDriverNumber");
            return (Criteria) this;
        }

        public Criteria andPileDriverNumberLike(String value) {
            addCriterion("Pile_Driver_Number like", value, "pileDriverNumber");
            return (Criteria) this;
        }

        public Criteria andPileDriverNumberNotLike(String value) {
            addCriterion("Pile_Driver_Number not like", value, "pileDriverNumber");
            return (Criteria) this;
        }

        public Criteria andPileDriverNumberIn(List<String> values) {
            addCriterion("Pile_Driver_Number in", values, "pileDriverNumber");
            return (Criteria) this;
        }

        public Criteria andPileDriverNumberNotIn(List<String> values) {
            addCriterion("Pile_Driver_Number not in", values, "pileDriverNumber");
            return (Criteria) this;
        }

        public Criteria andPileDriverNumberBetween(String value1, String value2) {
            addCriterion("Pile_Driver_Number between", value1, value2, "pileDriverNumber");
            return (Criteria) this;
        }

        public Criteria andPileDriverNumberNotBetween(String value1, String value2) {
            addCriterion("Pile_Driver_Number not between", value1, value2, "pileDriverNumber");
            return (Criteria) this;
        }

        public Criteria andMixStationNumberIsNull() {
            addCriterion("Mix_Station_Number is null");
            return (Criteria) this;
        }

        public Criteria andMixStationNumberIsNotNull() {
            addCriterion("Mix_Station_Number is not null");
            return (Criteria) this;
        }

        public Criteria andMixStationNumberEqualTo(String value) {
            addCriterion("Mix_Station_Number =", value, "mixStationNumber");
            return (Criteria) this;
        }

        public Criteria andMixStationNumberNotEqualTo(String value) {
            addCriterion("Mix_Station_Number <>", value, "mixStationNumber");
            return (Criteria) this;
        }

        public Criteria andMixStationNumberGreaterThan(String value) {
            addCriterion("Mix_Station_Number >", value, "mixStationNumber");
            return (Criteria) this;
        }

        public Criteria andMixStationNumberGreaterThanOrEqualTo(String value) {
            addCriterion("Mix_Station_Number >=", value, "mixStationNumber");
            return (Criteria) this;
        }

        public Criteria andMixStationNumberLessThan(String value) {
            addCriterion("Mix_Station_Number <", value, "mixStationNumber");
            return (Criteria) this;
        }

        public Criteria andMixStationNumberLessThanOrEqualTo(String value) {
            addCriterion("Mix_Station_Number <=", value, "mixStationNumber");
            return (Criteria) this;
        }

        public Criteria andMixStationNumberLike(String value) {
            addCriterion("Mix_Station_Number like", value, "mixStationNumber");
            return (Criteria) this;
        }

        public Criteria andMixStationNumberNotLike(String value) {
            addCriterion("Mix_Station_Number not like", value, "mixStationNumber");
            return (Criteria) this;
        }

        public Criteria andMixStationNumberIn(List<String> values) {
            addCriterion("Mix_Station_Number in", values, "mixStationNumber");
            return (Criteria) this;
        }

        public Criteria andMixStationNumberNotIn(List<String> values) {
            addCriterion("Mix_Station_Number not in", values, "mixStationNumber");
            return (Criteria) this;
        }

        public Criteria andMixStationNumberBetween(String value1, String value2) {
            addCriterion("Mix_Station_Number between", value1, value2, "mixStationNumber");
            return (Criteria) this;
        }

        public Criteria andMixStationNumberNotBetween(String value1, String value2) {
            addCriterion("Mix_Station_Number not between", value1, value2, "mixStationNumber");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNull() {
            addCriterion("Start_Time is null");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNotNull() {
            addCriterion("Start_Time is not null");
            return (Criteria) this;
        }

        public Criteria andStartTimeEqualTo(Date value) {
            addCriterion("Start_Time =", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotEqualTo(Date value) {
            addCriterion("Start_Time <>", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThan(Date value) {
            addCriterion("Start_Time >", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("Start_Time >=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThan(Date value) {
            addCriterion("Start_Time <", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("Start_Time <=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeIn(List<Date> values) {
            addCriterion("Start_Time in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotIn(List<Date> values) {
            addCriterion("Start_Time not in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeBetween(Date value1, Date value2) {
            addCriterion("Start_Time between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("Start_Time not between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNull() {
            addCriterion("End_Time is null");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNotNull() {
            addCriterion("End_Time is not null");
            return (Criteria) this;
        }

        public Criteria andEndTimeEqualTo(Date value) {
            addCriterion("End_Time =", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotEqualTo(Date value) {
            addCriterion("End_Time <>", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThan(Date value) {
            addCriterion("End_Time >", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("End_Time >=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThan(Date value) {
            addCriterion("End_Time <", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("End_Time <=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIn(List<Date> values) {
            addCriterion("End_Time in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotIn(List<Date> values) {
            addCriterion("End_Time not in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeBetween(Date value1, Date value2) {
            addCriterion("End_Time between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("End_Time not between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andPileLengthIsNull() {
            addCriterion("Pile_Length is null");
            return (Criteria) this;
        }

        public Criteria andPileLengthIsNotNull() {
            addCriterion("Pile_Length is not null");
            return (Criteria) this;
        }

        public Criteria andPileLengthEqualTo(BigDecimal value) {
            addCriterion("Pile_Length =", value, "pileLength");
            return (Criteria) this;
        }

        public Criteria andPileLengthNotEqualTo(BigDecimal value) {
            addCriterion("Pile_Length <>", value, "pileLength");
            return (Criteria) this;
        }

        public Criteria andPileLengthGreaterThan(BigDecimal value) {
            addCriterion("Pile_Length >", value, "pileLength");
            return (Criteria) this;
        }

        public Criteria andPileLengthGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("Pile_Length >=", value, "pileLength");
            return (Criteria) this;
        }

        public Criteria andPileLengthLessThan(BigDecimal value) {
            addCriterion("Pile_Length <", value, "pileLength");
            return (Criteria) this;
        }

        public Criteria andPileLengthLessThanOrEqualTo(BigDecimal value) {
            addCriterion("Pile_Length <=", value, "pileLength");
            return (Criteria) this;
        }

        public Criteria andPileLengthIn(List<BigDecimal> values) {
            addCriterion("Pile_Length in", values, "pileLength");
            return (Criteria) this;
        }

        public Criteria andPileLengthNotIn(List<BigDecimal> values) {
            addCriterion("Pile_Length not in", values, "pileLength");
            return (Criteria) this;
        }

        public Criteria andPileLengthBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Pile_Length between", value1, value2, "pileLength");
            return (Criteria) this;
        }

        public Criteria andPileLengthNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Pile_Length not between", value1, value2, "pileLength");
            return (Criteria) this;
        }

        public Criteria andGunitingSecondIsNull() {
            addCriterion("Guniting_Second is null");
            return (Criteria) this;
        }

        public Criteria andGunitingSecondIsNotNull() {
            addCriterion("Guniting_Second is not null");
            return (Criteria) this;
        }

        public Criteria andGunitingSecondEqualTo(Short value) {
            addCriterion("Guniting_Second =", value, "gunitingSecond");
            return (Criteria) this;
        }

        public Criteria andGunitingSecondNotEqualTo(Short value) {
            addCriterion("Guniting_Second <>", value, "gunitingSecond");
            return (Criteria) this;
        }

        public Criteria andGunitingSecondGreaterThan(Short value) {
            addCriterion("Guniting_Second >", value, "gunitingSecond");
            return (Criteria) this;
        }

        public Criteria andGunitingSecondGreaterThanOrEqualTo(Short value) {
            addCriterion("Guniting_Second >=", value, "gunitingSecond");
            return (Criteria) this;
        }

        public Criteria andGunitingSecondLessThan(Short value) {
            addCriterion("Guniting_Second <", value, "gunitingSecond");
            return (Criteria) this;
        }

        public Criteria andGunitingSecondLessThanOrEqualTo(Short value) {
            addCriterion("Guniting_Second <=", value, "gunitingSecond");
            return (Criteria) this;
        }

        public Criteria andGunitingSecondIn(List<Short> values) {
            addCriterion("Guniting_Second in", values, "gunitingSecond");
            return (Criteria) this;
        }

        public Criteria andGunitingSecondNotIn(List<Short> values) {
            addCriterion("Guniting_Second not in", values, "gunitingSecond");
            return (Criteria) this;
        }

        public Criteria andGunitingSecondBetween(Short value1, Short value2) {
            addCriterion("Guniting_Second between", value1, value2, "gunitingSecond");
            return (Criteria) this;
        }

        public Criteria andGunitingSecondNotBetween(Short value1, Short value2) {
            addCriterion("Guniting_Second not between", value1, value2, "gunitingSecond");
            return (Criteria) this;
        }

        public Criteria andTotalLiquidIsNull() {
            addCriterion("Total_Liquid is null");
            return (Criteria) this;
        }

        public Criteria andTotalLiquidIsNotNull() {
            addCriterion("Total_Liquid is not null");
            return (Criteria) this;
        }

        public Criteria andTotalLiquidEqualTo(BigDecimal value) {
            addCriterion("Total_Liquid =", value, "totalLiquid");
            return (Criteria) this;
        }

        public Criteria andTotalLiquidNotEqualTo(BigDecimal value) {
            addCriterion("Total_Liquid <>", value, "totalLiquid");
            return (Criteria) this;
        }

        public Criteria andTotalLiquidGreaterThan(BigDecimal value) {
            addCriterion("Total_Liquid >", value, "totalLiquid");
            return (Criteria) this;
        }

        public Criteria andTotalLiquidGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("Total_Liquid >=", value, "totalLiquid");
            return (Criteria) this;
        }

        public Criteria andTotalLiquidLessThan(BigDecimal value) {
            addCriterion("Total_Liquid <", value, "totalLiquid");
            return (Criteria) this;
        }

        public Criteria andTotalLiquidLessThanOrEqualTo(BigDecimal value) {
            addCriterion("Total_Liquid <=", value, "totalLiquid");
            return (Criteria) this;
        }

        public Criteria andTotalLiquidIn(List<BigDecimal> values) {
            addCriterion("Total_Liquid in", values, "totalLiquid");
            return (Criteria) this;
        }

        public Criteria andTotalLiquidNotIn(List<BigDecimal> values) {
            addCriterion("Total_Liquid not in", values, "totalLiquid");
            return (Criteria) this;
        }

        public Criteria andTotalLiquidBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Total_Liquid between", value1, value2, "totalLiquid");
            return (Criteria) this;
        }

        public Criteria andTotalLiquidNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Total_Liquid not between", value1, value2, "totalLiquid");
            return (Criteria) this;
        }

        public Criteria andTotalCementIsNull() {
            addCriterion("Total_Cement is null");
            return (Criteria) this;
        }

        public Criteria andTotalCementIsNotNull() {
            addCriterion("Total_Cement is not null");
            return (Criteria) this;
        }

        public Criteria andTotalCementEqualTo(BigDecimal value) {
            addCriterion("Total_Cement =", value, "totalCement");
            return (Criteria) this;
        }

        public Criteria andTotalCementNotEqualTo(BigDecimal value) {
            addCriterion("Total_Cement <>", value, "totalCement");
            return (Criteria) this;
        }

        public Criteria andTotalCementGreaterThan(BigDecimal value) {
            addCriterion("Total_Cement >", value, "totalCement");
            return (Criteria) this;
        }

        public Criteria andTotalCementGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("Total_Cement >=", value, "totalCement");
            return (Criteria) this;
        }

        public Criteria andTotalCementLessThan(BigDecimal value) {
            addCriterion("Total_Cement <", value, "totalCement");
            return (Criteria) this;
        }

        public Criteria andTotalCementLessThanOrEqualTo(BigDecimal value) {
            addCriterion("Total_Cement <=", value, "totalCement");
            return (Criteria) this;
        }

        public Criteria andTotalCementIn(List<BigDecimal> values) {
            addCriterion("Total_Cement in", values, "totalCement");
            return (Criteria) this;
        }

        public Criteria andTotalCementNotIn(List<BigDecimal> values) {
            addCriterion("Total_Cement not in", values, "totalCement");
            return (Criteria) this;
        }

        public Criteria andTotalCementBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Total_Cement between", value1, value2, "totalCement");
            return (Criteria) this;
        }

        public Criteria andTotalCementNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Total_Cement not between", value1, value2, "totalCement");
            return (Criteria) this;
        }

        public Criteria andMaxDownSpeedIsNull() {
            addCriterion("Max_Down_Speed is null");
            return (Criteria) this;
        }

        public Criteria andMaxDownSpeedIsNotNull() {
            addCriterion("Max_Down_Speed is not null");
            return (Criteria) this;
        }

        public Criteria andMaxDownSpeedEqualTo(BigDecimal value) {
            addCriterion("Max_Down_Speed =", value, "maxDownSpeed");
            return (Criteria) this;
        }

        public Criteria andMaxDownSpeedNotEqualTo(BigDecimal value) {
            addCriterion("Max_Down_Speed <>", value, "maxDownSpeed");
            return (Criteria) this;
        }

        public Criteria andMaxDownSpeedGreaterThan(BigDecimal value) {
            addCriterion("Max_Down_Speed >", value, "maxDownSpeed");
            return (Criteria) this;
        }

        public Criteria andMaxDownSpeedGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("Max_Down_Speed >=", value, "maxDownSpeed");
            return (Criteria) this;
        }

        public Criteria andMaxDownSpeedLessThan(BigDecimal value) {
            addCriterion("Max_Down_Speed <", value, "maxDownSpeed");
            return (Criteria) this;
        }

        public Criteria andMaxDownSpeedLessThanOrEqualTo(BigDecimal value) {
            addCriterion("Max_Down_Speed <=", value, "maxDownSpeed");
            return (Criteria) this;
        }

        public Criteria andMaxDownSpeedIn(List<BigDecimal> values) {
            addCriterion("Max_Down_Speed in", values, "maxDownSpeed");
            return (Criteria) this;
        }

        public Criteria andMaxDownSpeedNotIn(List<BigDecimal> values) {
            addCriterion("Max_Down_Speed not in", values, "maxDownSpeed");
            return (Criteria) this;
        }

        public Criteria andMaxDownSpeedBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Max_Down_Speed between", value1, value2, "maxDownSpeed");
            return (Criteria) this;
        }

        public Criteria andMaxDownSpeedNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Max_Down_Speed not between", value1, value2, "maxDownSpeed");
            return (Criteria) this;
        }

        public Criteria andMaxUpSpeedIsNull() {
            addCriterion("Max_Up_Speed is null");
            return (Criteria) this;
        }

        public Criteria andMaxUpSpeedIsNotNull() {
            addCriterion("Max_Up_Speed is not null");
            return (Criteria) this;
        }

        public Criteria andMaxUpSpeedEqualTo(BigDecimal value) {
            addCriterion("Max_Up_Speed =", value, "maxUpSpeed");
            return (Criteria) this;
        }

        public Criteria andMaxUpSpeedNotEqualTo(BigDecimal value) {
            addCriterion("Max_Up_Speed <>", value, "maxUpSpeed");
            return (Criteria) this;
        }

        public Criteria andMaxUpSpeedGreaterThan(BigDecimal value) {
            addCriterion("Max_Up_Speed >", value, "maxUpSpeed");
            return (Criteria) this;
        }

        public Criteria andMaxUpSpeedGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("Max_Up_Speed >=", value, "maxUpSpeed");
            return (Criteria) this;
        }

        public Criteria andMaxUpSpeedLessThan(BigDecimal value) {
            addCriterion("Max_Up_Speed <", value, "maxUpSpeed");
            return (Criteria) this;
        }

        public Criteria andMaxUpSpeedLessThanOrEqualTo(BigDecimal value) {
            addCriterion("Max_Up_Speed <=", value, "maxUpSpeed");
            return (Criteria) this;
        }

        public Criteria andMaxUpSpeedIn(List<BigDecimal> values) {
            addCriterion("Max_Up_Speed in", values, "maxUpSpeed");
            return (Criteria) this;
        }

        public Criteria andMaxUpSpeedNotIn(List<BigDecimal> values) {
            addCriterion("Max_Up_Speed not in", values, "maxUpSpeed");
            return (Criteria) this;
        }

        public Criteria andMaxUpSpeedBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Max_Up_Speed between", value1, value2, "maxUpSpeed");
            return (Criteria) this;
        }

        public Criteria andMaxUpSpeedNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Max_Up_Speed not between", value1, value2, "maxUpSpeed");
            return (Criteria) this;
        }

        public Criteria andMaxInsidePowerIsNull() {
            addCriterion("Max_Inside_Power is null");
            return (Criteria) this;
        }

        public Criteria andMaxInsidePowerIsNotNull() {
            addCriterion("Max_Inside_Power is not null");
            return (Criteria) this;
        }

        public Criteria andMaxInsidePowerEqualTo(BigDecimal value) {
            addCriterion("Max_Inside_Power =", value, "maxInsidePower");
            return (Criteria) this;
        }

        public Criteria andMaxInsidePowerNotEqualTo(BigDecimal value) {
            addCriterion("Max_Inside_Power <>", value, "maxInsidePower");
            return (Criteria) this;
        }

        public Criteria andMaxInsidePowerGreaterThan(BigDecimal value) {
            addCriterion("Max_Inside_Power >", value, "maxInsidePower");
            return (Criteria) this;
        }

        public Criteria andMaxInsidePowerGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("Max_Inside_Power >=", value, "maxInsidePower");
            return (Criteria) this;
        }

        public Criteria andMaxInsidePowerLessThan(BigDecimal value) {
            addCriterion("Max_Inside_Power <", value, "maxInsidePower");
            return (Criteria) this;
        }

        public Criteria andMaxInsidePowerLessThanOrEqualTo(BigDecimal value) {
            addCriterion("Max_Inside_Power <=", value, "maxInsidePower");
            return (Criteria) this;
        }

        public Criteria andMaxInsidePowerIn(List<BigDecimal> values) {
            addCriterion("Max_Inside_Power in", values, "maxInsidePower");
            return (Criteria) this;
        }

        public Criteria andMaxInsidePowerNotIn(List<BigDecimal> values) {
            addCriterion("Max_Inside_Power not in", values, "maxInsidePower");
            return (Criteria) this;
        }

        public Criteria andMaxInsidePowerBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Max_Inside_Power between", value1, value2, "maxInsidePower");
            return (Criteria) this;
        }

        public Criteria andMaxInsidePowerNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Max_Inside_Power not between", value1, value2, "maxInsidePower");
            return (Criteria) this;
        }

        public Criteria andMaxOutsidePowerIsNull() {
            addCriterion("Max_Outside_Power is null");
            return (Criteria) this;
        }

        public Criteria andMaxOutsidePowerIsNotNull() {
            addCriterion("Max_Outside_Power is not null");
            return (Criteria) this;
        }

        public Criteria andMaxOutsidePowerEqualTo(BigDecimal value) {
            addCriterion("Max_Outside_Power =", value, "maxOutsidePower");
            return (Criteria) this;
        }

        public Criteria andMaxOutsidePowerNotEqualTo(BigDecimal value) {
            addCriterion("Max_Outside_Power <>", value, "maxOutsidePower");
            return (Criteria) this;
        }

        public Criteria andMaxOutsidePowerGreaterThan(BigDecimal value) {
            addCriterion("Max_Outside_Power >", value, "maxOutsidePower");
            return (Criteria) this;
        }

        public Criteria andMaxOutsidePowerGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("Max_Outside_Power >=", value, "maxOutsidePower");
            return (Criteria) this;
        }

        public Criteria andMaxOutsidePowerLessThan(BigDecimal value) {
            addCriterion("Max_Outside_Power <", value, "maxOutsidePower");
            return (Criteria) this;
        }

        public Criteria andMaxOutsidePowerLessThanOrEqualTo(BigDecimal value) {
            addCriterion("Max_Outside_Power <=", value, "maxOutsidePower");
            return (Criteria) this;
        }

        public Criteria andMaxOutsidePowerIn(List<BigDecimal> values) {
            addCriterion("Max_Outside_Power in", values, "maxOutsidePower");
            return (Criteria) this;
        }

        public Criteria andMaxOutsidePowerNotIn(List<BigDecimal> values) {
            addCriterion("Max_Outside_Power not in", values, "maxOutsidePower");
            return (Criteria) this;
        }

        public Criteria andMaxOutsidePowerBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Max_Outside_Power between", value1, value2, "maxOutsidePower");
            return (Criteria) this;
        }

        public Criteria andMaxOutsidePowerNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Max_Outside_Power not between", value1, value2, "maxOutsidePower");
            return (Criteria) this;
        }

        public Criteria andMaxLeanIsNull() {
            addCriterion("Max_Lean is null");
            return (Criteria) this;
        }

        public Criteria andMaxLeanIsNotNull() {
            addCriterion("Max_Lean is not null");
            return (Criteria) this;
        }

        public Criteria andMaxLeanEqualTo(BigDecimal value) {
            addCriterion("Max_Lean =", value, "maxLean");
            return (Criteria) this;
        }

        public Criteria andMaxLeanNotEqualTo(BigDecimal value) {
            addCriterion("Max_Lean <>", value, "maxLean");
            return (Criteria) this;
        }

        public Criteria andMaxLeanGreaterThan(BigDecimal value) {
            addCriterion("Max_Lean >", value, "maxLean");
            return (Criteria) this;
        }

        public Criteria andMaxLeanGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("Max_Lean >=", value, "maxLean");
            return (Criteria) this;
        }

        public Criteria andMaxLeanLessThan(BigDecimal value) {
            addCriterion("Max_Lean <", value, "maxLean");
            return (Criteria) this;
        }

        public Criteria andMaxLeanLessThanOrEqualTo(BigDecimal value) {
            addCriterion("Max_Lean <=", value, "maxLean");
            return (Criteria) this;
        }

        public Criteria andMaxLeanIn(List<BigDecimal> values) {
            addCriterion("Max_Lean in", values, "maxLean");
            return (Criteria) this;
        }

        public Criteria andMaxLeanNotIn(List<BigDecimal> values) {
            addCriterion("Max_Lean not in", values, "maxLean");
            return (Criteria) this;
        }

        public Criteria andMaxLeanBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Max_Lean between", value1, value2, "maxLean");
            return (Criteria) this;
        }

        public Criteria andMaxLeanNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Max_Lean not between", value1, value2, "maxLean");
            return (Criteria) this;
        }

        public Criteria andGunitingBeginTimeIsNull() {
            addCriterion("Guniting_Begin_Time is null");
            return (Criteria) this;
        }

        public Criteria andGunitingBeginTimeIsNotNull() {
            addCriterion("Guniting_Begin_Time is not null");
            return (Criteria) this;
        }

        public Criteria andGunitingBeginTimeEqualTo(Date value) {
            addCriterion("Guniting_Begin_Time =", value, "gunitingBeginTime");
            return (Criteria) this;
        }

        public Criteria andGunitingBeginTimeNotEqualTo(Date value) {
            addCriterion("Guniting_Begin_Time <>", value, "gunitingBeginTime");
            return (Criteria) this;
        }

        public Criteria andGunitingBeginTimeGreaterThan(Date value) {
            addCriterion("Guniting_Begin_Time >", value, "gunitingBeginTime");
            return (Criteria) this;
        }

        public Criteria andGunitingBeginTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("Guniting_Begin_Time >=", value, "gunitingBeginTime");
            return (Criteria) this;
        }

        public Criteria andGunitingBeginTimeLessThan(Date value) {
            addCriterion("Guniting_Begin_Time <", value, "gunitingBeginTime");
            return (Criteria) this;
        }

        public Criteria andGunitingBeginTimeLessThanOrEqualTo(Date value) {
            addCriterion("Guniting_Begin_Time <=", value, "gunitingBeginTime");
            return (Criteria) this;
        }

        public Criteria andGunitingBeginTimeIn(List<Date> values) {
            addCriterion("Guniting_Begin_Time in", values, "gunitingBeginTime");
            return (Criteria) this;
        }

        public Criteria andGunitingBeginTimeNotIn(List<Date> values) {
            addCriterion("Guniting_Begin_Time not in", values, "gunitingBeginTime");
            return (Criteria) this;
        }

        public Criteria andGunitingBeginTimeBetween(Date value1, Date value2) {
            addCriterion("Guniting_Begin_Time between", value1, value2, "gunitingBeginTime");
            return (Criteria) this;
        }

        public Criteria andGunitingBeginTimeNotBetween(Date value1, Date value2) {
            addCriterion("Guniting_Begin_Time not between", value1, value2, "gunitingBeginTime");
            return (Criteria) this;
        }

        public Criteria andGunitingEndTimeIsNull() {
            addCriterion("Guniting_End_Time is null");
            return (Criteria) this;
        }

        public Criteria andGunitingEndTimeIsNotNull() {
            addCriterion("Guniting_End_Time is not null");
            return (Criteria) this;
        }

        public Criteria andGunitingEndTimeEqualTo(Date value) {
            addCriterion("Guniting_End_Time =", value, "gunitingEndTime");
            return (Criteria) this;
        }

        public Criteria andGunitingEndTimeNotEqualTo(Date value) {
            addCriterion("Guniting_End_Time <>", value, "gunitingEndTime");
            return (Criteria) this;
        }

        public Criteria andGunitingEndTimeGreaterThan(Date value) {
            addCriterion("Guniting_End_Time >", value, "gunitingEndTime");
            return (Criteria) this;
        }

        public Criteria andGunitingEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("Guniting_End_Time >=", value, "gunitingEndTime");
            return (Criteria) this;
        }

        public Criteria andGunitingEndTimeLessThan(Date value) {
            addCriterion("Guniting_End_Time <", value, "gunitingEndTime");
            return (Criteria) this;
        }

        public Criteria andGunitingEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("Guniting_End_Time <=", value, "gunitingEndTime");
            return (Criteria) this;
        }

        public Criteria andGunitingEndTimeIn(List<Date> values) {
            addCriterion("Guniting_End_Time in", values, "gunitingEndTime");
            return (Criteria) this;
        }

        public Criteria andGunitingEndTimeNotIn(List<Date> values) {
            addCriterion("Guniting_End_Time not in", values, "gunitingEndTime");
            return (Criteria) this;
        }

        public Criteria andGunitingEndTimeBetween(Date value1, Date value2) {
            addCriterion("Guniting_End_Time between", value1, value2, "gunitingEndTime");
            return (Criteria) this;
        }

        public Criteria andGunitingEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("Guniting_End_Time not between", value1, value2, "gunitingEndTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("Create_Time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("Create_Time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("Create_Time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("Create_Time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("Create_Time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("Create_Time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("Create_Time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("Create_Time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("Create_Time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("Create_Time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("Create_Time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("Create_Time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andChangeTimeIsNull() {
            addCriterion("Change_Time is null");
            return (Criteria) this;
        }

        public Criteria andChangeTimeIsNotNull() {
            addCriterion("Change_Time is not null");
            return (Criteria) this;
        }

        public Criteria andChangeTimeEqualTo(Date value) {
            addCriterion("Change_Time =", value, "changeTime");
            return (Criteria) this;
        }

        public Criteria andChangeTimeNotEqualTo(Date value) {
            addCriterion("Change_Time <>", value, "changeTime");
            return (Criteria) this;
        }

        public Criteria andChangeTimeGreaterThan(Date value) {
            addCriterion("Change_Time >", value, "changeTime");
            return (Criteria) this;
        }

        public Criteria andChangeTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("Change_Time >=", value, "changeTime");
            return (Criteria) this;
        }

        public Criteria andChangeTimeLessThan(Date value) {
            addCriterion("Change_Time <", value, "changeTime");
            return (Criteria) this;
        }

        public Criteria andChangeTimeLessThanOrEqualTo(Date value) {
            addCriterion("Change_Time <=", value, "changeTime");
            return (Criteria) this;
        }

        public Criteria andChangeTimeIn(List<Date> values) {
            addCriterion("Change_Time in", values, "changeTime");
            return (Criteria) this;
        }

        public Criteria andChangeTimeNotIn(List<Date> values) {
            addCriterion("Change_Time not in", values, "changeTime");
            return (Criteria) this;
        }

        public Criteria andChangeTimeBetween(Date value1, Date value2) {
            addCriterion("Change_Time between", value1, value2, "changeTime");
            return (Criteria) this;
        }

        public Criteria andChangeTimeNotBetween(Date value1, Date value2) {
            addCriterion("Change_Time not between", value1, value2, "changeTime");
            return (Criteria) this;
        }

        public Criteria andSectionNumberIsNull() {
            addCriterion("Section_Number is null");
            return (Criteria) this;
        }

        public Criteria andSectionNumberIsNotNull() {
            addCriterion("Section_Number is not null");
            return (Criteria) this;
        }

        public Criteria andSectionNumberEqualTo(String value) {
            addCriterion("Section_Number =", value, "sectionNumber");
            return (Criteria) this;
        }

        public Criteria andSectionNumberNotEqualTo(String value) {
            addCriterion("Section_Number <>", value, "sectionNumber");
            return (Criteria) this;
        }

        public Criteria andSectionNumberGreaterThan(String value) {
            addCriterion("Section_Number >", value, "sectionNumber");
            return (Criteria) this;
        }

        public Criteria andSectionNumberGreaterThanOrEqualTo(String value) {
            addCriterion("Section_Number >=", value, "sectionNumber");
            return (Criteria) this;
        }

        public Criteria andSectionNumberLessThan(String value) {
            addCriterion("Section_Number <", value, "sectionNumber");
            return (Criteria) this;
        }

        public Criteria andSectionNumberLessThanOrEqualTo(String value) {
            addCriterion("Section_Number <=", value, "sectionNumber");
            return (Criteria) this;
        }

        public Criteria andSectionNumberLike(String value) {
            addCriterion("Section_Number like", value, "sectionNumber");
            return (Criteria) this;
        }

        public Criteria andSectionNumberNotLike(String value) {
            addCriterion("Section_Number not like", value, "sectionNumber");
            return (Criteria) this;
        }

        public Criteria andSectionNumberIn(List<String> values) {
            addCriterion("Section_Number in", values, "sectionNumber");
            return (Criteria) this;
        }

        public Criteria andSectionNumberNotIn(List<String> values) {
            addCriterion("Section_Number not in", values, "sectionNumber");
            return (Criteria) this;
        }

        public Criteria andSectionNumberBetween(String value1, String value2) {
            addCriterion("Section_Number between", value1, value2, "sectionNumber");
            return (Criteria) this;
        }

        public Criteria andSectionNumberNotBetween(String value1, String value2) {
            addCriterion("Section_Number not between", value1, value2, "sectionNumber");
            return (Criteria) this;
        }

        public Criteria andPileStatusIsNull() {
            addCriterion("Pile_status is null");
            return (Criteria) this;
        }

        public Criteria andPileStatusIsNotNull() {
            addCriterion("Pile_status is not null");
            return (Criteria) this;
        }

        public Criteria andPileStatusEqualTo(Integer value) {
            addCriterion("Pile_status =", value, "pileStatus");
            return (Criteria) this;
        }

        public Criteria andPileStatusNotEqualTo(Integer value) {
            addCriterion("Pile_status <>", value, "pileStatus");
            return (Criteria) this;
        }

        public Criteria andPileStatusGreaterThan(Integer value) {
            addCriterion("Pile_status >", value, "pileStatus");
            return (Criteria) this;
        }

        public Criteria andPileStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("Pile_status >=", value, "pileStatus");
            return (Criteria) this;
        }

        public Criteria andPileStatusLessThan(Integer value) {
            addCriterion("Pile_status <", value, "pileStatus");
            return (Criteria) this;
        }

        public Criteria andPileStatusLessThanOrEqualTo(Integer value) {
            addCriterion("Pile_status <=", value, "pileStatus");
            return (Criteria) this;
        }

        public Criteria andPileStatusIn(List<Integer> values) {
            addCriterion("Pile_status in", values, "pileStatus");
            return (Criteria) this;
        }

        public Criteria andPileStatusNotIn(List<Integer> values) {
            addCriterion("Pile_status not in", values, "pileStatus");
            return (Criteria) this;
        }

        public Criteria andPileStatusBetween(Integer value1, Integer value2) {
            addCriterion("Pile_status between", value1, value2, "pileStatus");
            return (Criteria) this;
        }

        public Criteria andPileStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("Pile_status not between", value1, value2, "pileStatus");
            return (Criteria) this;
        }

        public Criteria andXmidIsNull() {
            addCriterion("xmid is null");
            return (Criteria) this;
        }

        public Criteria andXmidIsNotNull() {
            addCriterion("xmid is not null");
            return (Criteria) this;
        }

        public Criteria andXmidEqualTo(Byte value) {
            addCriterion("xmid =", value, "xmid");
            return (Criteria) this;
        }

        public Criteria andXmidNotEqualTo(Byte value) {
            addCriterion("xmid <>", value, "xmid");
            return (Criteria) this;
        }

        public Criteria andXmidGreaterThan(Byte value) {
            addCriterion("xmid >", value, "xmid");
            return (Criteria) this;
        }

        public Criteria andXmidGreaterThanOrEqualTo(Byte value) {
            addCriterion("xmid >=", value, "xmid");
            return (Criteria) this;
        }

        public Criteria andXmidLessThan(Byte value) {
            addCriterion("xmid <", value, "xmid");
            return (Criteria) this;
        }

        public Criteria andXmidLessThanOrEqualTo(Byte value) {
            addCriterion("xmid <=", value, "xmid");
            return (Criteria) this;
        }

        public Criteria andXmidIn(List<Byte> values) {
            addCriterion("xmid in", values, "xmid");
            return (Criteria) this;
        }

        public Criteria andXmidNotIn(List<Byte> values) {
            addCriterion("xmid not in", values, "xmid");
            return (Criteria) this;
        }

        public Criteria andXmidBetween(Byte value1, Byte value2) {
            addCriterion("xmid between", value1, value2, "xmid");
            return (Criteria) this;
        }

        public Criteria andXmidNotBetween(Byte value1, Byte value2) {
            addCriterion("xmid not between", value1, value2, "xmid");
            return (Criteria) this;
        }

        public Criteria andZjidIsNull() {
            addCriterion("zjid is null");
            return (Criteria) this;
        }

        public Criteria andZjidIsNotNull() {
            addCriterion("zjid is not null");
            return (Criteria) this;
        }

        public Criteria andZjidEqualTo(Integer value) {
            addCriterion("zjid =", value, "zjid");
            return (Criteria) this;
        }

        public Criteria andZjidNotEqualTo(Integer value) {
            addCriterion("zjid <>", value, "zjid");
            return (Criteria) this;
        }

        public Criteria andZjidGreaterThan(Integer value) {
            addCriterion("zjid >", value, "zjid");
            return (Criteria) this;
        }

        public Criteria andZjidGreaterThanOrEqualTo(Integer value) {
            addCriterion("zjid >=", value, "zjid");
            return (Criteria) this;
        }

        public Criteria andZjidLessThan(Integer value) {
            addCriterion("zjid <", value, "zjid");
            return (Criteria) this;
        }

        public Criteria andZjidLessThanOrEqualTo(Integer value) {
            addCriterion("zjid <=", value, "zjid");
            return (Criteria) this;
        }

        public Criteria andZjidIn(List<Integer> values) {
            addCriterion("zjid in", values, "zjid");
            return (Criteria) this;
        }

        public Criteria andZjidNotIn(List<Integer> values) {
            addCriterion("zjid not in", values, "zjid");
            return (Criteria) this;
        }

        public Criteria andZjidBetween(Integer value1, Integer value2) {
            addCriterion("zjid between", value1, value2, "zjid");
            return (Criteria) this;
        }

        public Criteria andZjidNotBetween(Integer value1, Integer value2) {
            addCriterion("zjid not between", value1, value2, "zjid");
            return (Criteria) this;
        }

        public Criteria andEnlargeTopIsNull() {
            addCriterion("Enlarge_Top is null");
            return (Criteria) this;
        }

        public Criteria andEnlargeTopIsNotNull() {
            addCriterion("Enlarge_Top is not null");
            return (Criteria) this;
        }

        public Criteria andEnlargeTopEqualTo(BigDecimal value) {
            addCriterion("Enlarge_Top =", value, "enlargeTop");
            return (Criteria) this;
        }

        public Criteria andEnlargeTopNotEqualTo(BigDecimal value) {
            addCriterion("Enlarge_Top <>", value, "enlargeTop");
            return (Criteria) this;
        }

        public Criteria andEnlargeTopGreaterThan(BigDecimal value) {
            addCriterion("Enlarge_Top >", value, "enlargeTop");
            return (Criteria) this;
        }

        public Criteria andEnlargeTopGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("Enlarge_Top >=", value, "enlargeTop");
            return (Criteria) this;
        }

        public Criteria andEnlargeTopLessThan(BigDecimal value) {
            addCriterion("Enlarge_Top <", value, "enlargeTop");
            return (Criteria) this;
        }

        public Criteria andEnlargeTopLessThanOrEqualTo(BigDecimal value) {
            addCriterion("Enlarge_Top <=", value, "enlargeTop");
            return (Criteria) this;
        }

        public Criteria andEnlargeTopIn(List<BigDecimal> values) {
            addCriterion("Enlarge_Top in", values, "enlargeTop");
            return (Criteria) this;
        }

        public Criteria andEnlargeTopNotIn(List<BigDecimal> values) {
            addCriterion("Enlarge_Top not in", values, "enlargeTop");
            return (Criteria) this;
        }

        public Criteria andEnlargeTopBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Enlarge_Top between", value1, value2, "enlargeTop");
            return (Criteria) this;
        }

        public Criteria andEnlargeTopNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Enlarge_Top not between", value1, value2, "enlargeTop");
            return (Criteria) this;
        }

        public Criteria andEnlargeBottomIsNull() {
            addCriterion("Enlarge_Bottom is null");
            return (Criteria) this;
        }

        public Criteria andEnlargeBottomIsNotNull() {
            addCriterion("Enlarge_Bottom is not null");
            return (Criteria) this;
        }

        public Criteria andEnlargeBottomEqualTo(BigDecimal value) {
            addCriterion("Enlarge_Bottom =", value, "enlargeBottom");
            return (Criteria) this;
        }

        public Criteria andEnlargeBottomNotEqualTo(BigDecimal value) {
            addCriterion("Enlarge_Bottom <>", value, "enlargeBottom");
            return (Criteria) this;
        }

        public Criteria andEnlargeBottomGreaterThan(BigDecimal value) {
            addCriterion("Enlarge_Bottom >", value, "enlargeBottom");
            return (Criteria) this;
        }

        public Criteria andEnlargeBottomGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("Enlarge_Bottom >=", value, "enlargeBottom");
            return (Criteria) this;
        }

        public Criteria andEnlargeBottomLessThan(BigDecimal value) {
            addCriterion("Enlarge_Bottom <", value, "enlargeBottom");
            return (Criteria) this;
        }

        public Criteria andEnlargeBottomLessThanOrEqualTo(BigDecimal value) {
            addCriterion("Enlarge_Bottom <=", value, "enlargeBottom");
            return (Criteria) this;
        }

        public Criteria andEnlargeBottomIn(List<BigDecimal> values) {
            addCriterion("Enlarge_Bottom in", values, "enlargeBottom");
            return (Criteria) this;
        }

        public Criteria andEnlargeBottomNotIn(List<BigDecimal> values) {
            addCriterion("Enlarge_Bottom not in", values, "enlargeBottom");
            return (Criteria) this;
        }

        public Criteria andEnlargeBottomBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Enlarge_Bottom between", value1, value2, "enlargeBottom");
            return (Criteria) this;
        }

        public Criteria andEnlargeBottomNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Enlarge_Bottom not between", value1, value2, "enlargeBottom");
            return (Criteria) this;
        }

        public Criteria andEnlargeHeightIsNull() {
            addCriterion("Enlarge_Height is null");
            return (Criteria) this;
        }

        public Criteria andEnlargeHeightIsNotNull() {
            addCriterion("Enlarge_Height is not null");
            return (Criteria) this;
        }

        public Criteria andEnlargeHeightEqualTo(BigDecimal value) {
            addCriterion("Enlarge_Height =", value, "enlargeHeight");
            return (Criteria) this;
        }

        public Criteria andEnlargeHeightNotEqualTo(BigDecimal value) {
            addCriterion("Enlarge_Height <>", value, "enlargeHeight");
            return (Criteria) this;
        }

        public Criteria andEnlargeHeightGreaterThan(BigDecimal value) {
            addCriterion("Enlarge_Height >", value, "enlargeHeight");
            return (Criteria) this;
        }

        public Criteria andEnlargeHeightGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("Enlarge_Height >=", value, "enlargeHeight");
            return (Criteria) this;
        }

        public Criteria andEnlargeHeightLessThan(BigDecimal value) {
            addCriterion("Enlarge_Height <", value, "enlargeHeight");
            return (Criteria) this;
        }

        public Criteria andEnlargeHeightLessThanOrEqualTo(BigDecimal value) {
            addCriterion("Enlarge_Height <=", value, "enlargeHeight");
            return (Criteria) this;
        }

        public Criteria andEnlargeHeightIn(List<BigDecimal> values) {
            addCriterion("Enlarge_Height in", values, "enlargeHeight");
            return (Criteria) this;
        }

        public Criteria andEnlargeHeightNotIn(List<BigDecimal> values) {
            addCriterion("Enlarge_Height not in", values, "enlargeHeight");
            return (Criteria) this;
        }

        public Criteria andEnlargeHeightBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Enlarge_Height between", value1, value2, "enlargeHeight");
            return (Criteria) this;
        }

        public Criteria andEnlargeHeightNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Enlarge_Height not between", value1, value2, "enlargeHeight");
            return (Criteria) this;
        }

        public Criteria andTYlIsNull() {
            addCriterion("t_yl is null");
            return (Criteria) this;
        }

        public Criteria andTYlIsNotNull() {
            addCriterion("t_yl is not null");
            return (Criteria) this;
        }

        public Criteria andTYlEqualTo(Byte value) {
            addCriterion("t_yl =", value, "tYl");
            return (Criteria) this;
        }

        public Criteria andTYlNotEqualTo(Byte value) {
            addCriterion("t_yl <>", value, "tYl");
            return (Criteria) this;
        }

        public Criteria andTYlGreaterThan(Byte value) {
            addCriterion("t_yl >", value, "tYl");
            return (Criteria) this;
        }

        public Criteria andTYlGreaterThanOrEqualTo(Byte value) {
            addCriterion("t_yl >=", value, "tYl");
            return (Criteria) this;
        }

        public Criteria andTYlLessThan(Byte value) {
            addCriterion("t_yl <", value, "tYl");
            return (Criteria) this;
        }

        public Criteria andTYlLessThanOrEqualTo(Byte value) {
            addCriterion("t_yl <=", value, "tYl");
            return (Criteria) this;
        }

        public Criteria andTYlIn(List<Byte> values) {
            addCriterion("t_yl in", values, "tYl");
            return (Criteria) this;
        }

        public Criteria andTYlNotIn(List<Byte> values) {
            addCriterion("t_yl not in", values, "tYl");
            return (Criteria) this;
        }

        public Criteria andTYlBetween(Byte value1, Byte value2) {
            addCriterion("t_yl between", value1, value2, "tYl");
            return (Criteria) this;
        }

        public Criteria andTYlNotBetween(Byte value1, Byte value2) {
            addCriterion("t_yl not between", value1, value2, "tYl");
            return (Criteria) this;
        }

        public Criteria andTCxsIsNull() {
            addCriterion("t_cxs is null");
            return (Criteria) this;
        }

        public Criteria andTCxsIsNotNull() {
            addCriterion("t_cxs is not null");
            return (Criteria) this;
        }

        public Criteria andTCxsEqualTo(BigDecimal value) {
            addCriterion("t_cxs =", value, "tCxs");
            return (Criteria) this;
        }

        public Criteria andTCxsNotEqualTo(BigDecimal value) {
            addCriterion("t_cxs <>", value, "tCxs");
            return (Criteria) this;
        }

        public Criteria andTCxsGreaterThan(BigDecimal value) {
            addCriterion("t_cxs >", value, "tCxs");
            return (Criteria) this;
        }

        public Criteria andTCxsGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("t_cxs >=", value, "tCxs");
            return (Criteria) this;
        }

        public Criteria andTCxsLessThan(BigDecimal value) {
            addCriterion("t_cxs <", value, "tCxs");
            return (Criteria) this;
        }

        public Criteria andTCxsLessThanOrEqualTo(BigDecimal value) {
            addCriterion("t_cxs <=", value, "tCxs");
            return (Criteria) this;
        }

        public Criteria andTCxsIn(List<BigDecimal> values) {
            addCriterion("t_cxs in", values, "tCxs");
            return (Criteria) this;
        }

        public Criteria andTCxsNotIn(List<BigDecimal> values) {
            addCriterion("t_cxs not in", values, "tCxs");
            return (Criteria) this;
        }

        public Criteria andTCxsBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("t_cxs between", value1, value2, "tCxs");
            return (Criteria) this;
        }

        public Criteria andTCxsNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("t_cxs not between", value1, value2, "tCxs");
            return (Criteria) this;
        }

        public Criteria andTJxsIsNull() {
            addCriterion("t_jxs is null");
            return (Criteria) this;
        }

        public Criteria andTJxsIsNotNull() {
            addCriterion("t_jxs is not null");
            return (Criteria) this;
        }

        public Criteria andTJxsEqualTo(BigDecimal value) {
            addCriterion("t_jxs =", value, "tJxs");
            return (Criteria) this;
        }

        public Criteria andTJxsNotEqualTo(BigDecimal value) {
            addCriterion("t_jxs <>", value, "tJxs");
            return (Criteria) this;
        }

        public Criteria andTJxsGreaterThan(BigDecimal value) {
            addCriterion("t_jxs >", value, "tJxs");
            return (Criteria) this;
        }

        public Criteria andTJxsGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("t_jxs >=", value, "tJxs");
            return (Criteria) this;
        }

        public Criteria andTJxsLessThan(BigDecimal value) {
            addCriterion("t_jxs <", value, "tJxs");
            return (Criteria) this;
        }

        public Criteria andTJxsLessThanOrEqualTo(BigDecimal value) {
            addCriterion("t_jxs <=", value, "tJxs");
            return (Criteria) this;
        }

        public Criteria andTJxsIn(List<BigDecimal> values) {
            addCriterion("t_jxs in", values, "tJxs");
            return (Criteria) this;
        }

        public Criteria andTJxsNotIn(List<BigDecimal> values) {
            addCriterion("t_jxs not in", values, "tJxs");
            return (Criteria) this;
        }

        public Criteria andTJxsBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("t_jxs between", value1, value2, "tJxs");
            return (Criteria) this;
        }

        public Criteria andTJxsNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("t_jxs not between", value1, value2, "tJxs");
            return (Criteria) this;
        }

        public Criteria andSjzcIsNull() {
            addCriterion("sjzc is null");
            return (Criteria) this;
        }

        public Criteria andSjzcIsNotNull() {
            addCriterion("sjzc is not null");
            return (Criteria) this;
        }

        public Criteria andSjzcEqualTo(BigDecimal value) {
            addCriterion("sjzc =", value, "sjzc");
            return (Criteria) this;
        }

        public Criteria andSjzcNotEqualTo(BigDecimal value) {
            addCriterion("sjzc <>", value, "sjzc");
            return (Criteria) this;
        }

        public Criteria andSjzcGreaterThan(BigDecimal value) {
            addCriterion("sjzc >", value, "sjzc");
            return (Criteria) this;
        }

        public Criteria andSjzcGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("sjzc >=", value, "sjzc");
            return (Criteria) this;
        }

        public Criteria andSjzcLessThan(BigDecimal value) {
            addCriterion("sjzc <", value, "sjzc");
            return (Criteria) this;
        }

        public Criteria andSjzcLessThanOrEqualTo(BigDecimal value) {
            addCriterion("sjzc <=", value, "sjzc");
            return (Criteria) this;
        }

        public Criteria andSjzcIn(List<BigDecimal> values) {
            addCriterion("sjzc in", values, "sjzc");
            return (Criteria) this;
        }

        public Criteria andSjzcNotIn(List<BigDecimal> values) {
            addCriterion("sjzc not in", values, "sjzc");
            return (Criteria) this;
        }

        public Criteria andSjzcBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sjzc between", value1, value2, "sjzc");
            return (Criteria) this;
        }

        public Criteria andSjzcNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sjzc not between", value1, value2, "sjzc");
            return (Criteria) this;
        }

        public Criteria andZhlIsNull() {
            addCriterion("zhl is null");
            return (Criteria) this;
        }

        public Criteria andZhlIsNotNull() {
            addCriterion("zhl is not null");
            return (Criteria) this;
        }

        public Criteria andZhlEqualTo(BigDecimal value) {
            addCriterion("zhl =", value, "zhl");
            return (Criteria) this;
        }

        public Criteria andZhlNotEqualTo(BigDecimal value) {
            addCriterion("zhl <>", value, "zhl");
            return (Criteria) this;
        }

        public Criteria andZhlGreaterThan(BigDecimal value) {
            addCriterion("zhl >", value, "zhl");
            return (Criteria) this;
        }

        public Criteria andZhlGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("zhl >=", value, "zhl");
            return (Criteria) this;
        }

        public Criteria andZhlLessThan(BigDecimal value) {
            addCriterion("zhl <", value, "zhl");
            return (Criteria) this;
        }

        public Criteria andZhlLessThanOrEqualTo(BigDecimal value) {
            addCriterion("zhl <=", value, "zhl");
            return (Criteria) this;
        }

        public Criteria andZhlIn(List<BigDecimal> values) {
            addCriterion("zhl in", values, "zhl");
            return (Criteria) this;
        }

        public Criteria andZhlNotIn(List<BigDecimal> values) {
            addCriterion("zhl not in", values, "zhl");
            return (Criteria) this;
        }

        public Criteria andZhlBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("zhl between", value1, value2, "zhl");
            return (Criteria) this;
        }

        public Criteria andZhlNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("zhl not between", value1, value2, "zhl");
            return (Criteria) this;
        }

        public Criteria andZjlIsNull() {
            addCriterion("zjl is null");
            return (Criteria) this;
        }

        public Criteria andZjlIsNotNull() {
            addCriterion("zjl is not null");
            return (Criteria) this;
        }

        public Criteria andZjlEqualTo(BigDecimal value) {
            addCriterion("zjl =", value, "zjl");
            return (Criteria) this;
        }

        public Criteria andZjlNotEqualTo(BigDecimal value) {
            addCriterion("zjl <>", value, "zjl");
            return (Criteria) this;
        }

        public Criteria andZjlGreaterThan(BigDecimal value) {
            addCriterion("zjl >", value, "zjl");
            return (Criteria) this;
        }

        public Criteria andZjlGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("zjl >=", value, "zjl");
            return (Criteria) this;
        }

        public Criteria andZjlLessThan(BigDecimal value) {
            addCriterion("zjl <", value, "zjl");
            return (Criteria) this;
        }

        public Criteria andZjlLessThanOrEqualTo(BigDecimal value) {
            addCriterion("zjl <=", value, "zjl");
            return (Criteria) this;
        }

        public Criteria andZjlIn(List<BigDecimal> values) {
            addCriterion("zjl in", values, "zjl");
            return (Criteria) this;
        }

        public Criteria andZjlNotIn(List<BigDecimal> values) {
            addCriterion("zjl not in", values, "zjl");
            return (Criteria) this;
        }

        public Criteria andZjlBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("zjl between", value1, value2, "zjl");
            return (Criteria) this;
        }

        public Criteria andZjlNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("zjl not between", value1, value2, "zjl");
            return (Criteria) this;
        }

        public Criteria andSjZcIsNull() {
            addCriterion("sj_zc is null");
            return (Criteria) this;
        }

        public Criteria andSjZcIsNotNull() {
            addCriterion("sj_zc is not null");
            return (Criteria) this;
        }

        public Criteria andSjZcEqualTo(BigDecimal value) {
            addCriterion("sj_zc =", value, "sjZc");
            return (Criteria) this;
        }

        public Criteria andSjZcNotEqualTo(BigDecimal value) {
            addCriterion("sj_zc <>", value, "sjZc");
            return (Criteria) this;
        }

        public Criteria andSjZcGreaterThan(BigDecimal value) {
            addCriterion("sj_zc >", value, "sjZc");
            return (Criteria) this;
        }

        public Criteria andSjZcGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("sj_zc >=", value, "sjZc");
            return (Criteria) this;
        }

        public Criteria andSjZcLessThan(BigDecimal value) {
            addCriterion("sj_zc <", value, "sjZc");
            return (Criteria) this;
        }

        public Criteria andSjZcLessThanOrEqualTo(BigDecimal value) {
            addCriterion("sj_zc <=", value, "sjZc");
            return (Criteria) this;
        }

        public Criteria andSjZcIn(List<BigDecimal> values) {
            addCriterion("sj_zc in", values, "sjZc");
            return (Criteria) this;
        }

        public Criteria andSjZcNotIn(List<BigDecimal> values) {
            addCriterion("sj_zc not in", values, "sjZc");
            return (Criteria) this;
        }

        public Criteria andSjZcBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sj_zc between", value1, value2, "sjZc");
            return (Criteria) this;
        }

        public Criteria andSjZcNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sj_zc not between", value1, value2, "sjZc");
            return (Criteria) this;
        }

        public Criteria andSjHlIsNull() {
            addCriterion("sj_hl is null");
            return (Criteria) this;
        }

        public Criteria andSjHlIsNotNull() {
            addCriterion("sj_hl is not null");
            return (Criteria) this;
        }

        public Criteria andSjHlEqualTo(BigDecimal value) {
            addCriterion("sj_hl =", value, "sjHl");
            return (Criteria) this;
        }

        public Criteria andSjHlNotEqualTo(BigDecimal value) {
            addCriterion("sj_hl <>", value, "sjHl");
            return (Criteria) this;
        }

        public Criteria andSjHlGreaterThan(BigDecimal value) {
            addCriterion("sj_hl >", value, "sjHl");
            return (Criteria) this;
        }

        public Criteria andSjHlGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("sj_hl >=", value, "sjHl");
            return (Criteria) this;
        }

        public Criteria andSjHlLessThan(BigDecimal value) {
            addCriterion("sj_hl <", value, "sjHl");
            return (Criteria) this;
        }

        public Criteria andSjHlLessThanOrEqualTo(BigDecimal value) {
            addCriterion("sj_hl <=", value, "sjHl");
            return (Criteria) this;
        }

        public Criteria andSjHlIn(List<BigDecimal> values) {
            addCriterion("sj_hl in", values, "sjHl");
            return (Criteria) this;
        }

        public Criteria andSjHlNotIn(List<BigDecimal> values) {
            addCriterion("sj_hl not in", values, "sjHl");
            return (Criteria) this;
        }

        public Criteria andSjHlBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sj_hl between", value1, value2, "sjHl");
            return (Criteria) this;
        }

        public Criteria andSjHlNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sj_hl not between", value1, value2, "sjHl");
            return (Criteria) this;
        }

        public Criteria andSjJlIsNull() {
            addCriterion("sj_jl is null");
            return (Criteria) this;
        }

        public Criteria andSjJlIsNotNull() {
            addCriterion("sj_jl is not null");
            return (Criteria) this;
        }

        public Criteria andSjJlEqualTo(BigDecimal value) {
            addCriterion("sj_jl =", value, "sjJl");
            return (Criteria) this;
        }

        public Criteria andSjJlNotEqualTo(BigDecimal value) {
            addCriterion("sj_jl <>", value, "sjJl");
            return (Criteria) this;
        }

        public Criteria andSjJlGreaterThan(BigDecimal value) {
            addCriterion("sj_jl >", value, "sjJl");
            return (Criteria) this;
        }

        public Criteria andSjJlGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("sj_jl >=", value, "sjJl");
            return (Criteria) this;
        }

        public Criteria andSjJlLessThan(BigDecimal value) {
            addCriterion("sj_jl <", value, "sjJl");
            return (Criteria) this;
        }

        public Criteria andSjJlLessThanOrEqualTo(BigDecimal value) {
            addCriterion("sj_jl <=", value, "sjJl");
            return (Criteria) this;
        }

        public Criteria andSjJlIn(List<BigDecimal> values) {
            addCriterion("sj_jl in", values, "sjJl");
            return (Criteria) this;
        }

        public Criteria andSjJlNotIn(List<BigDecimal> values) {
            addCriterion("sj_jl not in", values, "sjJl");
            return (Criteria) this;
        }

        public Criteria andSjJlBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sj_jl between", value1, value2, "sjJl");
            return (Criteria) this;
        }

        public Criteria andSjJlNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sj_jl not between", value1, value2, "sjJl");
            return (Criteria) this;
        }

        public Criteria andUpidIsNull() {
            addCriterion("upid is null");
            return (Criteria) this;
        }

        public Criteria andUpidIsNotNull() {
            addCriterion("upid is not null");
            return (Criteria) this;
        }

        public Criteria andUpidEqualTo(Byte value) {
            addCriterion("upid =", value, "upid");
            return (Criteria) this;
        }

        public Criteria andUpidNotEqualTo(Byte value) {
            addCriterion("upid <>", value, "upid");
            return (Criteria) this;
        }

        public Criteria andUpidGreaterThan(Byte value) {
            addCriterion("upid >", value, "upid");
            return (Criteria) this;
        }

        public Criteria andUpidGreaterThanOrEqualTo(Byte value) {
            addCriterion("upid >=", value, "upid");
            return (Criteria) this;
        }

        public Criteria andUpidLessThan(Byte value) {
            addCriterion("upid <", value, "upid");
            return (Criteria) this;
        }

        public Criteria andUpidLessThanOrEqualTo(Byte value) {
            addCriterion("upid <=", value, "upid");
            return (Criteria) this;
        }

        public Criteria andUpidIn(List<Byte> values) {
            addCriterion("upid in", values, "upid");
            return (Criteria) this;
        }

        public Criteria andUpidNotIn(List<Byte> values) {
            addCriterion("upid not in", values, "upid");
            return (Criteria) this;
        }

        public Criteria andUpidBetween(Byte value1, Byte value2) {
            addCriterion("upid between", value1, value2, "upid");
            return (Criteria) this;
        }

        public Criteria andUpidNotBetween(Byte value1, Byte value2) {
            addCriterion("upid not between", value1, value2, "upid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_luding_pile_info
     *
     * @mbg.generated do_not_delete_during_merge Sat Jan 14 21:44:26 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_luding_pile_info
     *
     * @mbg.generated Sat Jan 14 21:44:26 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}