package com.device.business.equip.bean;

public class SectionBeanKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_section_info.Section_ID
     *
     * @mbg.generated Tue Jan 03 19:48:23 CST 2017
     */
    private String sectionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_section_info.Project_ID
     *
     * @mbg.generated Tue Jan 03 19:48:23 CST 2017
     */
    private Integer projectId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_section_info.Section_ID
     *
     * @return the value of t_luding_section_info.Section_ID
     *
     * @mbg.generated Tue Jan 03 19:48:23 CST 2017
     */
    public String getSectionId() {
        return sectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_section_info.Section_ID
     *
     * @param sectionId the value for t_luding_section_info.Section_ID
     *
     * @mbg.generated Tue Jan 03 19:48:23 CST 2017
     */
    public void setSectionId(String sectionId) {
        this.sectionId = sectionId == null ? null : sectionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_section_info.Project_ID
     *
     * @return the value of t_luding_section_info.Project_ID
     *
     * @mbg.generated Tue Jan 03 19:48:23 CST 2017
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_section_info.Project_ID
     *
     * @param projectId the value for t_luding_section_info.Project_ID
     *
     * @mbg.generated Tue Jan 03 19:48:23 CST 2017
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }
}