package com.device.business.equip.bean;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class SlurryPerdayBeanExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_luding_slurry_perday
     *
     * @mbg.generated Sat Jan 14 13:41:07 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_luding_slurry_perday
     *
     * @mbg.generated Sat Jan 14 13:41:07 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_luding_slurry_perday
     *
     * @mbg.generated Sat Jan 14 13:41:07 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_slurry_perday
     *
     * @mbg.generated Sat Jan 14 13:41:07 CST 2017
     */
    public SlurryPerdayBeanExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_slurry_perday
     *
     * @mbg.generated Sat Jan 14 13:41:07 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_slurry_perday
     *
     * @mbg.generated Sat Jan 14 13:41:07 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_slurry_perday
     *
     * @mbg.generated Sat Jan 14 13:41:07 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_slurry_perday
     *
     * @mbg.generated Sat Jan 14 13:41:07 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_slurry_perday
     *
     * @mbg.generated Sat Jan 14 13:41:07 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_slurry_perday
     *
     * @mbg.generated Sat Jan 14 13:41:07 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_slurry_perday
     *
     * @mbg.generated Sat Jan 14 13:41:07 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_slurry_perday
     *
     * @mbg.generated Sat Jan 14 13:41:07 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_slurry_perday
     *
     * @mbg.generated Sat Jan 14 13:41:07 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_slurry_perday
     *
     * @mbg.generated Sat Jan 14 13:41:07 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_luding_slurry_perday
     *
     * @mbg.generated Sat Jan 14 13:41:07 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andProjectIdIsNull() {
            addCriterion("Project_ID is null");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNotNull() {
            addCriterion("Project_ID is not null");
            return (Criteria) this;
        }

        public Criteria andProjectIdEqualTo(Integer value) {
            addCriterion("Project_ID =", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotEqualTo(Integer value) {
            addCriterion("Project_ID <>", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThan(Integer value) {
            addCriterion("Project_ID >", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("Project_ID >=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThan(Integer value) {
            addCriterion("Project_ID <", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThanOrEqualTo(Integer value) {
            addCriterion("Project_ID <=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdIn(List<Integer> values) {
            addCriterion("Project_ID in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotIn(List<Integer> values) {
            addCriterion("Project_ID not in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdBetween(Integer value1, Integer value2) {
            addCriterion("Project_ID between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotBetween(Integer value1, Integer value2) {
            addCriterion("Project_ID not between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andSectionIdIsNull() {
            addCriterion("Section_ID is null");
            return (Criteria) this;
        }

        public Criteria andSectionIdIsNotNull() {
            addCriterion("Section_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSectionIdEqualTo(String value) {
            addCriterion("Section_ID =", value, "sectionId");
            return (Criteria) this;
        }

        public Criteria andSectionIdNotEqualTo(String value) {
            addCriterion("Section_ID <>", value, "sectionId");
            return (Criteria) this;
        }

        public Criteria andSectionIdGreaterThan(String value) {
            addCriterion("Section_ID >", value, "sectionId");
            return (Criteria) this;
        }

        public Criteria andSectionIdGreaterThanOrEqualTo(String value) {
            addCriterion("Section_ID >=", value, "sectionId");
            return (Criteria) this;
        }

        public Criteria andSectionIdLessThan(String value) {
            addCriterion("Section_ID <", value, "sectionId");
            return (Criteria) this;
        }

        public Criteria andSectionIdLessThanOrEqualTo(String value) {
            addCriterion("Section_ID <=", value, "sectionId");
            return (Criteria) this;
        }

        public Criteria andSectionIdLike(String value) {
            addCriterion("Section_ID like", value, "sectionId");
            return (Criteria) this;
        }

        public Criteria andSectionIdNotLike(String value) {
            addCriterion("Section_ID not like", value, "sectionId");
            return (Criteria) this;
        }

        public Criteria andSectionIdIn(List<String> values) {
            addCriterion("Section_ID in", values, "sectionId");
            return (Criteria) this;
        }

        public Criteria andSectionIdNotIn(List<String> values) {
            addCriterion("Section_ID not in", values, "sectionId");
            return (Criteria) this;
        }

        public Criteria andSectionIdBetween(String value1, String value2) {
            addCriterion("Section_ID between", value1, value2, "sectionId");
            return (Criteria) this;
        }

        public Criteria andSectionIdNotBetween(String value1, String value2) {
            addCriterion("Section_ID not between", value1, value2, "sectionId");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdIsNull() {
            addCriterion("Equipment_ID is null");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdIsNotNull() {
            addCriterion("Equipment_ID is not null");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdEqualTo(String value) {
            addCriterion("Equipment_ID =", value, "equipmentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdNotEqualTo(String value) {
            addCriterion("Equipment_ID <>", value, "equipmentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdGreaterThan(String value) {
            addCriterion("Equipment_ID >", value, "equipmentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdGreaterThanOrEqualTo(String value) {
            addCriterion("Equipment_ID >=", value, "equipmentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdLessThan(String value) {
            addCriterion("Equipment_ID <", value, "equipmentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdLessThanOrEqualTo(String value) {
            addCriterion("Equipment_ID <=", value, "equipmentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdLike(String value) {
            addCriterion("Equipment_ID like", value, "equipmentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdNotLike(String value) {
            addCriterion("Equipment_ID not like", value, "equipmentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdIn(List<String> values) {
            addCriterion("Equipment_ID in", values, "equipmentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdNotIn(List<String> values) {
            addCriterion("Equipment_ID not in", values, "equipmentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdBetween(String value1, String value2) {
            addCriterion("Equipment_ID between", value1, value2, "equipmentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdNotBetween(String value1, String value2) {
            addCriterion("Equipment_ID not between", value1, value2, "equipmentId");
            return (Criteria) this;
        }

        public Criteria andDateAmountIsNull() {
            addCriterion("Date_Amount is null");
            return (Criteria) this;
        }

        public Criteria andDateAmountIsNotNull() {
            addCriterion("Date_Amount is not null");
            return (Criteria) this;
        }

        public Criteria andDateAmountEqualTo(Date value) {
            addCriterionForJDBCDate("Date_Amount =", value, "dateAmount");
            return (Criteria) this;
        }

        public Criteria andDateAmountNotEqualTo(Date value) {
            addCriterionForJDBCDate("Date_Amount <>", value, "dateAmount");
            return (Criteria) this;
        }

        public Criteria andDateAmountGreaterThan(Date value) {
            addCriterionForJDBCDate("Date_Amount >", value, "dateAmount");
            return (Criteria) this;
        }

        public Criteria andDateAmountGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("Date_Amount >=", value, "dateAmount");
            return (Criteria) this;
        }

        public Criteria andDateAmountLessThan(Date value) {
            addCriterionForJDBCDate("Date_Amount <", value, "dateAmount");
            return (Criteria) this;
        }

        public Criteria andDateAmountLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("Date_Amount <=", value, "dateAmount");
            return (Criteria) this;
        }

        public Criteria andDateAmountIn(List<Date> values) {
            addCriterionForJDBCDate("Date_Amount in", values, "dateAmount");
            return (Criteria) this;
        }

        public Criteria andDateAmountNotIn(List<Date> values) {
            addCriterionForJDBCDate("Date_Amount not in", values, "dateAmount");
            return (Criteria) this;
        }

        public Criteria andDateAmountBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("Date_Amount between", value1, value2, "dateAmount");
            return (Criteria) this;
        }

        public Criteria andDateAmountNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("Date_Amount not between", value1, value2, "dateAmount");
            return (Criteria) this;
        }

        public Criteria andExpectWaterAmountIsNull() {
            addCriterion("Expect_Water_Amount is null");
            return (Criteria) this;
        }

        public Criteria andExpectWaterAmountIsNotNull() {
            addCriterion("Expect_Water_Amount is not null");
            return (Criteria) this;
        }

        public Criteria andExpectWaterAmountEqualTo(Integer value) {
            addCriterion("Expect_Water_Amount =", value, "expectWaterAmount");
            return (Criteria) this;
        }

        public Criteria andExpectWaterAmountNotEqualTo(Integer value) {
            addCriterion("Expect_Water_Amount <>", value, "expectWaterAmount");
            return (Criteria) this;
        }

        public Criteria andExpectWaterAmountGreaterThan(Integer value) {
            addCriterion("Expect_Water_Amount >", value, "expectWaterAmount");
            return (Criteria) this;
        }

        public Criteria andExpectWaterAmountGreaterThanOrEqualTo(Integer value) {
            addCriterion("Expect_Water_Amount >=", value, "expectWaterAmount");
            return (Criteria) this;
        }

        public Criteria andExpectWaterAmountLessThan(Integer value) {
            addCriterion("Expect_Water_Amount <", value, "expectWaterAmount");
            return (Criteria) this;
        }

        public Criteria andExpectWaterAmountLessThanOrEqualTo(Integer value) {
            addCriterion("Expect_Water_Amount <=", value, "expectWaterAmount");
            return (Criteria) this;
        }

        public Criteria andExpectWaterAmountIn(List<Integer> values) {
            addCriterion("Expect_Water_Amount in", values, "expectWaterAmount");
            return (Criteria) this;
        }

        public Criteria andExpectWaterAmountNotIn(List<Integer> values) {
            addCriterion("Expect_Water_Amount not in", values, "expectWaterAmount");
            return (Criteria) this;
        }

        public Criteria andExpectWaterAmountBetween(Integer value1, Integer value2) {
            addCriterion("Expect_Water_Amount between", value1, value2, "expectWaterAmount");
            return (Criteria) this;
        }

        public Criteria andExpectWaterAmountNotBetween(Integer value1, Integer value2) {
            addCriterion("Expect_Water_Amount not between", value1, value2, "expectWaterAmount");
            return (Criteria) this;
        }

        public Criteria andExpectCementAmountIsNull() {
            addCriterion("Expect_Cement_Amount is null");
            return (Criteria) this;
        }

        public Criteria andExpectCementAmountIsNotNull() {
            addCriterion("Expect_Cement_Amount is not null");
            return (Criteria) this;
        }

        public Criteria andExpectCementAmountEqualTo(Integer value) {
            addCriterion("Expect_Cement_Amount =", value, "expectCementAmount");
            return (Criteria) this;
        }

        public Criteria andExpectCementAmountNotEqualTo(Integer value) {
            addCriterion("Expect_Cement_Amount <>", value, "expectCementAmount");
            return (Criteria) this;
        }

        public Criteria andExpectCementAmountGreaterThan(Integer value) {
            addCriterion("Expect_Cement_Amount >", value, "expectCementAmount");
            return (Criteria) this;
        }

        public Criteria andExpectCementAmountGreaterThanOrEqualTo(Integer value) {
            addCriterion("Expect_Cement_Amount >=", value, "expectCementAmount");
            return (Criteria) this;
        }

        public Criteria andExpectCementAmountLessThan(Integer value) {
            addCriterion("Expect_Cement_Amount <", value, "expectCementAmount");
            return (Criteria) this;
        }

        public Criteria andExpectCementAmountLessThanOrEqualTo(Integer value) {
            addCriterion("Expect_Cement_Amount <=", value, "expectCementAmount");
            return (Criteria) this;
        }

        public Criteria andExpectCementAmountIn(List<Integer> values) {
            addCriterion("Expect_Cement_Amount in", values, "expectCementAmount");
            return (Criteria) this;
        }

        public Criteria andExpectCementAmountNotIn(List<Integer> values) {
            addCriterion("Expect_Cement_Amount not in", values, "expectCementAmount");
            return (Criteria) this;
        }

        public Criteria andExpectCementAmountBetween(Integer value1, Integer value2) {
            addCriterion("Expect_Cement_Amount between", value1, value2, "expectCementAmount");
            return (Criteria) this;
        }

        public Criteria andExpectCementAmountNotBetween(Integer value1, Integer value2) {
            addCriterion("Expect_Cement_Amount not between", value1, value2, "expectCementAmount");
            return (Criteria) this;
        }

        public Criteria andExpectSlurryAmountIsNull() {
            addCriterion("Expect_Slurry_Amount is null");
            return (Criteria) this;
        }

        public Criteria andExpectSlurryAmountIsNotNull() {
            addCriterion("Expect_Slurry_Amount is not null");
            return (Criteria) this;
        }

        public Criteria andExpectSlurryAmountEqualTo(Integer value) {
            addCriterion("Expect_Slurry_Amount =", value, "expectSlurryAmount");
            return (Criteria) this;
        }

        public Criteria andExpectSlurryAmountNotEqualTo(Integer value) {
            addCriterion("Expect_Slurry_Amount <>", value, "expectSlurryAmount");
            return (Criteria) this;
        }

        public Criteria andExpectSlurryAmountGreaterThan(Integer value) {
            addCriterion("Expect_Slurry_Amount >", value, "expectSlurryAmount");
            return (Criteria) this;
        }

        public Criteria andExpectSlurryAmountGreaterThanOrEqualTo(Integer value) {
            addCriterion("Expect_Slurry_Amount >=", value, "expectSlurryAmount");
            return (Criteria) this;
        }

        public Criteria andExpectSlurryAmountLessThan(Integer value) {
            addCriterion("Expect_Slurry_Amount <", value, "expectSlurryAmount");
            return (Criteria) this;
        }

        public Criteria andExpectSlurryAmountLessThanOrEqualTo(Integer value) {
            addCriterion("Expect_Slurry_Amount <=", value, "expectSlurryAmount");
            return (Criteria) this;
        }

        public Criteria andExpectSlurryAmountIn(List<Integer> values) {
            addCriterion("Expect_Slurry_Amount in", values, "expectSlurryAmount");
            return (Criteria) this;
        }

        public Criteria andExpectSlurryAmountNotIn(List<Integer> values) {
            addCriterion("Expect_Slurry_Amount not in", values, "expectSlurryAmount");
            return (Criteria) this;
        }

        public Criteria andExpectSlurryAmountBetween(Integer value1, Integer value2) {
            addCriterion("Expect_Slurry_Amount between", value1, value2, "expectSlurryAmount");
            return (Criteria) this;
        }

        public Criteria andExpectSlurryAmountNotBetween(Integer value1, Integer value2) {
            addCriterion("Expect_Slurry_Amount not between", value1, value2, "expectSlurryAmount");
            return (Criteria) this;
        }

        public Criteria andExpectPileAmountIsNull() {
            addCriterion("Expect_Pile_Amount is null");
            return (Criteria) this;
        }

        public Criteria andExpectPileAmountIsNotNull() {
            addCriterion("Expect_Pile_Amount is not null");
            return (Criteria) this;
        }

        public Criteria andExpectPileAmountEqualTo(Integer value) {
            addCriterion("Expect_Pile_Amount =", value, "expectPileAmount");
            return (Criteria) this;
        }

        public Criteria andExpectPileAmountNotEqualTo(Integer value) {
            addCriterion("Expect_Pile_Amount <>", value, "expectPileAmount");
            return (Criteria) this;
        }

        public Criteria andExpectPileAmountGreaterThan(Integer value) {
            addCriterion("Expect_Pile_Amount >", value, "expectPileAmount");
            return (Criteria) this;
        }

        public Criteria andExpectPileAmountGreaterThanOrEqualTo(Integer value) {
            addCriterion("Expect_Pile_Amount >=", value, "expectPileAmount");
            return (Criteria) this;
        }

        public Criteria andExpectPileAmountLessThan(Integer value) {
            addCriterion("Expect_Pile_Amount <", value, "expectPileAmount");
            return (Criteria) this;
        }

        public Criteria andExpectPileAmountLessThanOrEqualTo(Integer value) {
            addCriterion("Expect_Pile_Amount <=", value, "expectPileAmount");
            return (Criteria) this;
        }

        public Criteria andExpectPileAmountIn(List<Integer> values) {
            addCriterion("Expect_Pile_Amount in", values, "expectPileAmount");
            return (Criteria) this;
        }

        public Criteria andExpectPileAmountNotIn(List<Integer> values) {
            addCriterion("Expect_Pile_Amount not in", values, "expectPileAmount");
            return (Criteria) this;
        }

        public Criteria andExpectPileAmountBetween(Integer value1, Integer value2) {
            addCriterion("Expect_Pile_Amount between", value1, value2, "expectPileAmount");
            return (Criteria) this;
        }

        public Criteria andExpectPileAmountNotBetween(Integer value1, Integer value2) {
            addCriterion("Expect_Pile_Amount not between", value1, value2, "expectPileAmount");
            return (Criteria) this;
        }

        public Criteria andRealWaterAmountIsNull() {
            addCriterion("Real_Water_Amount is null");
            return (Criteria) this;
        }

        public Criteria andRealWaterAmountIsNotNull() {
            addCriterion("Real_Water_Amount is not null");
            return (Criteria) this;
        }

        public Criteria andRealWaterAmountEqualTo(Integer value) {
            addCriterion("Real_Water_Amount =", value, "realWaterAmount");
            return (Criteria) this;
        }

        public Criteria andRealWaterAmountNotEqualTo(Integer value) {
            addCriterion("Real_Water_Amount <>", value, "realWaterAmount");
            return (Criteria) this;
        }

        public Criteria andRealWaterAmountGreaterThan(Integer value) {
            addCriterion("Real_Water_Amount >", value, "realWaterAmount");
            return (Criteria) this;
        }

        public Criteria andRealWaterAmountGreaterThanOrEqualTo(Integer value) {
            addCriterion("Real_Water_Amount >=", value, "realWaterAmount");
            return (Criteria) this;
        }

        public Criteria andRealWaterAmountLessThan(Integer value) {
            addCriterion("Real_Water_Amount <", value, "realWaterAmount");
            return (Criteria) this;
        }

        public Criteria andRealWaterAmountLessThanOrEqualTo(Integer value) {
            addCriterion("Real_Water_Amount <=", value, "realWaterAmount");
            return (Criteria) this;
        }

        public Criteria andRealWaterAmountIn(List<Integer> values) {
            addCriterion("Real_Water_Amount in", values, "realWaterAmount");
            return (Criteria) this;
        }

        public Criteria andRealWaterAmountNotIn(List<Integer> values) {
            addCriterion("Real_Water_Amount not in", values, "realWaterAmount");
            return (Criteria) this;
        }

        public Criteria andRealWaterAmountBetween(Integer value1, Integer value2) {
            addCriterion("Real_Water_Amount between", value1, value2, "realWaterAmount");
            return (Criteria) this;
        }

        public Criteria andRealWaterAmountNotBetween(Integer value1, Integer value2) {
            addCriterion("Real_Water_Amount not between", value1, value2, "realWaterAmount");
            return (Criteria) this;
        }

        public Criteria andRealCementAmountIsNull() {
            addCriterion("Real_Cement_Amount is null");
            return (Criteria) this;
        }

        public Criteria andRealCementAmountIsNotNull() {
            addCriterion("Real_Cement_Amount is not null");
            return (Criteria) this;
        }

        public Criteria andRealCementAmountEqualTo(Integer value) {
            addCriterion("Real_Cement_Amount =", value, "realCementAmount");
            return (Criteria) this;
        }

        public Criteria andRealCementAmountNotEqualTo(Integer value) {
            addCriterion("Real_Cement_Amount <>", value, "realCementAmount");
            return (Criteria) this;
        }

        public Criteria andRealCementAmountGreaterThan(Integer value) {
            addCriterion("Real_Cement_Amount >", value, "realCementAmount");
            return (Criteria) this;
        }

        public Criteria andRealCementAmountGreaterThanOrEqualTo(Integer value) {
            addCriterion("Real_Cement_Amount >=", value, "realCementAmount");
            return (Criteria) this;
        }

        public Criteria andRealCementAmountLessThan(Integer value) {
            addCriterion("Real_Cement_Amount <", value, "realCementAmount");
            return (Criteria) this;
        }

        public Criteria andRealCementAmountLessThanOrEqualTo(Integer value) {
            addCriterion("Real_Cement_Amount <=", value, "realCementAmount");
            return (Criteria) this;
        }

        public Criteria andRealCementAmountIn(List<Integer> values) {
            addCriterion("Real_Cement_Amount in", values, "realCementAmount");
            return (Criteria) this;
        }

        public Criteria andRealCementAmountNotIn(List<Integer> values) {
            addCriterion("Real_Cement_Amount not in", values, "realCementAmount");
            return (Criteria) this;
        }

        public Criteria andRealCementAmountBetween(Integer value1, Integer value2) {
            addCriterion("Real_Cement_Amount between", value1, value2, "realCementAmount");
            return (Criteria) this;
        }

        public Criteria andRealCementAmountNotBetween(Integer value1, Integer value2) {
            addCriterion("Real_Cement_Amount not between", value1, value2, "realCementAmount");
            return (Criteria) this;
        }

        public Criteria andRealSlurryAmountIsNull() {
            addCriterion("Real_Slurry_Amount is null");
            return (Criteria) this;
        }

        public Criteria andRealSlurryAmountIsNotNull() {
            addCriterion("Real_Slurry_Amount is not null");
            return (Criteria) this;
        }

        public Criteria andRealSlurryAmountEqualTo(Integer value) {
            addCriterion("Real_Slurry_Amount =", value, "realSlurryAmount");
            return (Criteria) this;
        }

        public Criteria andRealSlurryAmountNotEqualTo(Integer value) {
            addCriterion("Real_Slurry_Amount <>", value, "realSlurryAmount");
            return (Criteria) this;
        }

        public Criteria andRealSlurryAmountGreaterThan(Integer value) {
            addCriterion("Real_Slurry_Amount >", value, "realSlurryAmount");
            return (Criteria) this;
        }

        public Criteria andRealSlurryAmountGreaterThanOrEqualTo(Integer value) {
            addCriterion("Real_Slurry_Amount >=", value, "realSlurryAmount");
            return (Criteria) this;
        }

        public Criteria andRealSlurryAmountLessThan(Integer value) {
            addCriterion("Real_Slurry_Amount <", value, "realSlurryAmount");
            return (Criteria) this;
        }

        public Criteria andRealSlurryAmountLessThanOrEqualTo(Integer value) {
            addCriterion("Real_Slurry_Amount <=", value, "realSlurryAmount");
            return (Criteria) this;
        }

        public Criteria andRealSlurryAmountIn(List<Integer> values) {
            addCriterion("Real_Slurry_Amount in", values, "realSlurryAmount");
            return (Criteria) this;
        }

        public Criteria andRealSlurryAmountNotIn(List<Integer> values) {
            addCriterion("Real_Slurry_Amount not in", values, "realSlurryAmount");
            return (Criteria) this;
        }

        public Criteria andRealSlurryAmountBetween(Integer value1, Integer value2) {
            addCriterion("Real_Slurry_Amount between", value1, value2, "realSlurryAmount");
            return (Criteria) this;
        }

        public Criteria andRealSlurryAmountNotBetween(Integer value1, Integer value2) {
            addCriterion("Real_Slurry_Amount not between", value1, value2, "realSlurryAmount");
            return (Criteria) this;
        }

        public Criteria andRealPileAmountIsNull() {
            addCriterion("Real_Pile_Amount is null");
            return (Criteria) this;
        }

        public Criteria andRealPileAmountIsNotNull() {
            addCriterion("Real_Pile_Amount is not null");
            return (Criteria) this;
        }

        public Criteria andRealPileAmountEqualTo(Integer value) {
            addCriterion("Real_Pile_Amount =", value, "realPileAmount");
            return (Criteria) this;
        }

        public Criteria andRealPileAmountNotEqualTo(Integer value) {
            addCriterion("Real_Pile_Amount <>", value, "realPileAmount");
            return (Criteria) this;
        }

        public Criteria andRealPileAmountGreaterThan(Integer value) {
            addCriterion("Real_Pile_Amount >", value, "realPileAmount");
            return (Criteria) this;
        }

        public Criteria andRealPileAmountGreaterThanOrEqualTo(Integer value) {
            addCriterion("Real_Pile_Amount >=", value, "realPileAmount");
            return (Criteria) this;
        }

        public Criteria andRealPileAmountLessThan(Integer value) {
            addCriterion("Real_Pile_Amount <", value, "realPileAmount");
            return (Criteria) this;
        }

        public Criteria andRealPileAmountLessThanOrEqualTo(Integer value) {
            addCriterion("Real_Pile_Amount <=", value, "realPileAmount");
            return (Criteria) this;
        }

        public Criteria andRealPileAmountIn(List<Integer> values) {
            addCriterion("Real_Pile_Amount in", values, "realPileAmount");
            return (Criteria) this;
        }

        public Criteria andRealPileAmountNotIn(List<Integer> values) {
            addCriterion("Real_Pile_Amount not in", values, "realPileAmount");
            return (Criteria) this;
        }

        public Criteria andRealPileAmountBetween(Integer value1, Integer value2) {
            addCriterion("Real_Pile_Amount between", value1, value2, "realPileAmount");
            return (Criteria) this;
        }

        public Criteria andRealPileAmountNotBetween(Integer value1, Integer value2) {
            addCriterion("Real_Pile_Amount not between", value1, value2, "realPileAmount");
            return (Criteria) this;
        }

        public Criteria andSectionNameIsNull() {
            addCriterion("Section_Name is null");
            return (Criteria) this;
        }

        public Criteria andSectionNameIsNotNull() {
            addCriterion("Section_Name is not null");
            return (Criteria) this;
        }

        public Criteria andSectionNameEqualTo(String value) {
            addCriterion("Section_Name =", value, "sectionName");
            return (Criteria) this;
        }

        public Criteria andSectionNameNotEqualTo(String value) {
            addCriterion("Section_Name <>", value, "sectionName");
            return (Criteria) this;
        }

        public Criteria andSectionNameGreaterThan(String value) {
            addCriterion("Section_Name >", value, "sectionName");
            return (Criteria) this;
        }

        public Criteria andSectionNameGreaterThanOrEqualTo(String value) {
            addCriterion("Section_Name >=", value, "sectionName");
            return (Criteria) this;
        }

        public Criteria andSectionNameLessThan(String value) {
            addCriterion("Section_Name <", value, "sectionName");
            return (Criteria) this;
        }

        public Criteria andSectionNameLessThanOrEqualTo(String value) {
            addCriterion("Section_Name <=", value, "sectionName");
            return (Criteria) this;
        }

        public Criteria andSectionNameLike(String value) {
            addCriterion("Section_Name like", value, "sectionName");
            return (Criteria) this;
        }

        public Criteria andSectionNameNotLike(String value) {
            addCriterion("Section_Name not like", value, "sectionName");
            return (Criteria) this;
        }

        public Criteria andSectionNameIn(List<String> values) {
            addCriterion("Section_Name in", values, "sectionName");
            return (Criteria) this;
        }

        public Criteria andSectionNameNotIn(List<String> values) {
            addCriterion("Section_Name not in", values, "sectionName");
            return (Criteria) this;
        }

        public Criteria andSectionNameBetween(String value1, String value2) {
            addCriterion("Section_Name between", value1, value2, "sectionName");
            return (Criteria) this;
        }

        public Criteria andSectionNameNotBetween(String value1, String value2) {
            addCriterion("Section_Name not between", value1, value2, "sectionName");
            return (Criteria) this;
        }

        public Criteria andProjectNameIsNull() {
            addCriterion("Project_Name is null");
            return (Criteria) this;
        }

        public Criteria andProjectNameIsNotNull() {
            addCriterion("Project_Name is not null");
            return (Criteria) this;
        }

        public Criteria andProjectNameEqualTo(String value) {
            addCriterion("Project_Name =", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameNotEqualTo(String value) {
            addCriterion("Project_Name <>", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameGreaterThan(String value) {
            addCriterion("Project_Name >", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameGreaterThanOrEqualTo(String value) {
            addCriterion("Project_Name >=", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameLessThan(String value) {
            addCriterion("Project_Name <", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameLessThanOrEqualTo(String value) {
            addCriterion("Project_Name <=", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameLike(String value) {
            addCriterion("Project_Name like", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameNotLike(String value) {
            addCriterion("Project_Name not like", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameIn(List<String> values) {
            addCriterion("Project_Name in", values, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameNotIn(List<String> values) {
            addCriterion("Project_Name not in", values, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameBetween(String value1, String value2) {
            addCriterion("Project_Name between", value1, value2, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameNotBetween(String value1, String value2) {
            addCriterion("Project_Name not between", value1, value2, "projectName");
            return (Criteria) this;
        }

        public Criteria andWaterCementRatioIsNull() {
            addCriterion("Water_Cement_Ratio is null");
            return (Criteria) this;
        }

        public Criteria andWaterCementRatioIsNotNull() {
            addCriterion("Water_Cement_Ratio is not null");
            return (Criteria) this;
        }

        public Criteria andWaterCementRatioEqualTo(BigDecimal value) {
            addCriterion("Water_Cement_Ratio =", value, "waterCementRatio");
            return (Criteria) this;
        }

        public Criteria andWaterCementRatioNotEqualTo(BigDecimal value) {
            addCriterion("Water_Cement_Ratio <>", value, "waterCementRatio");
            return (Criteria) this;
        }

        public Criteria andWaterCementRatioGreaterThan(BigDecimal value) {
            addCriterion("Water_Cement_Ratio >", value, "waterCementRatio");
            return (Criteria) this;
        }

        public Criteria andWaterCementRatioGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("Water_Cement_Ratio >=", value, "waterCementRatio");
            return (Criteria) this;
        }

        public Criteria andWaterCementRatioLessThan(BigDecimal value) {
            addCriterion("Water_Cement_Ratio <", value, "waterCementRatio");
            return (Criteria) this;
        }

        public Criteria andWaterCementRatioLessThanOrEqualTo(BigDecimal value) {
            addCriterion("Water_Cement_Ratio <=", value, "waterCementRatio");
            return (Criteria) this;
        }

        public Criteria andWaterCementRatioIn(List<BigDecimal> values) {
            addCriterion("Water_Cement_Ratio in", values, "waterCementRatio");
            return (Criteria) this;
        }

        public Criteria andWaterCementRatioNotIn(List<BigDecimal> values) {
            addCriterion("Water_Cement_Ratio not in", values, "waterCementRatio");
            return (Criteria) this;
        }

        public Criteria andWaterCementRatioBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Water_Cement_Ratio between", value1, value2, "waterCementRatio");
            return (Criteria) this;
        }

        public Criteria andWaterCementRatioNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Water_Cement_Ratio not between", value1, value2, "waterCementRatio");
            return (Criteria) this;
        }

        public Criteria andDensityIsNull() {
            addCriterion("Density is null");
            return (Criteria) this;
        }

        public Criteria andDensityIsNotNull() {
            addCriterion("Density is not null");
            return (Criteria) this;
        }

        public Criteria andDensityEqualTo(BigDecimal value) {
            addCriterion("Density =", value, "density");
            return (Criteria) this;
        }

        public Criteria andDensityNotEqualTo(BigDecimal value) {
            addCriterion("Density <>", value, "density");
            return (Criteria) this;
        }

        public Criteria andDensityGreaterThan(BigDecimal value) {
            addCriterion("Density >", value, "density");
            return (Criteria) this;
        }

        public Criteria andDensityGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("Density >=", value, "density");
            return (Criteria) this;
        }

        public Criteria andDensityLessThan(BigDecimal value) {
            addCriterion("Density <", value, "density");
            return (Criteria) this;
        }

        public Criteria andDensityLessThanOrEqualTo(BigDecimal value) {
            addCriterion("Density <=", value, "density");
            return (Criteria) this;
        }

        public Criteria andDensityIn(List<BigDecimal> values) {
            addCriterion("Density in", values, "density");
            return (Criteria) this;
        }

        public Criteria andDensityNotIn(List<BigDecimal> values) {
            addCriterion("Density not in", values, "density");
            return (Criteria) this;
        }

        public Criteria andDensityBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Density between", value1, value2, "density");
            return (Criteria) this;
        }

        public Criteria andDensityNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Density not between", value1, value2, "density");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_luding_slurry_perday
     *
     * @mbg.generated do_not_delete_during_merge Sat Jan 14 13:41:07 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_luding_slurry_perday
     *
     * @mbg.generated Sat Jan 14 13:41:07 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}