package com.device.business.equip.bean;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SlurryRecordBeanExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_luding_slurry_mix_record
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_luding_slurry_mix_record
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_luding_slurry_mix_record
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_slurry_mix_record
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public SlurryRecordBeanExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_slurry_mix_record
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_slurry_mix_record
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_slurry_mix_record
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_slurry_mix_record
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_slurry_mix_record
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_slurry_mix_record
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_slurry_mix_record
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_slurry_mix_record
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_slurry_mix_record
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_slurry_mix_record
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_luding_slurry_mix_record
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andMixTimeIsNull() {
            addCriterion("MIx_Time is null");
            return (Criteria) this;
        }

        public Criteria andMixTimeIsNotNull() {
            addCriterion("MIx_Time is not null");
            return (Criteria) this;
        }

        public Criteria andMixTimeEqualTo(Date value) {
            addCriterion("MIx_Time =", value, "mixTime");
            return (Criteria) this;
        }

        public Criteria andMixTimeNotEqualTo(Date value) {
            addCriterion("MIx_Time <>", value, "mixTime");
            return (Criteria) this;
        }

        public Criteria andMixTimeGreaterThan(Date value) {
            addCriterion("MIx_Time >", value, "mixTime");
            return (Criteria) this;
        }

        public Criteria andMixTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("MIx_Time >=", value, "mixTime");
            return (Criteria) this;
        }

        public Criteria andMixTimeLessThan(Date value) {
            addCriterion("MIx_Time <", value, "mixTime");
            return (Criteria) this;
        }

        public Criteria andMixTimeLessThanOrEqualTo(Date value) {
            addCriterion("MIx_Time <=", value, "mixTime");
            return (Criteria) this;
        }

        public Criteria andMixTimeIn(List<Date> values) {
            addCriterion("MIx_Time in", values, "mixTime");
            return (Criteria) this;
        }

        public Criteria andMixTimeNotIn(List<Date> values) {
            addCriterion("MIx_Time not in", values, "mixTime");
            return (Criteria) this;
        }

        public Criteria andMixTimeBetween(Date value1, Date value2) {
            addCriterion("MIx_Time between", value1, value2, "mixTime");
            return (Criteria) this;
        }

        public Criteria andMixTimeNotBetween(Date value1, Date value2) {
            addCriterion("MIx_Time not between", value1, value2, "mixTime");
            return (Criteria) this;
        }

        public Criteria andDataUploadTimeIsNull() {
            addCriterion("Data_Upload_Time is null");
            return (Criteria) this;
        }

        public Criteria andDataUploadTimeIsNotNull() {
            addCriterion("Data_Upload_Time is not null");
            return (Criteria) this;
        }

        public Criteria andDataUploadTimeEqualTo(Date value) {
            addCriterion("Data_Upload_Time =", value, "dataUploadTime");
            return (Criteria) this;
        }

        public Criteria andDataUploadTimeNotEqualTo(Date value) {
            addCriterion("Data_Upload_Time <>", value, "dataUploadTime");
            return (Criteria) this;
        }

        public Criteria andDataUploadTimeGreaterThan(Date value) {
            addCriterion("Data_Upload_Time >", value, "dataUploadTime");
            return (Criteria) this;
        }

        public Criteria andDataUploadTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("Data_Upload_Time >=", value, "dataUploadTime");
            return (Criteria) this;
        }

        public Criteria andDataUploadTimeLessThan(Date value) {
            addCriterion("Data_Upload_Time <", value, "dataUploadTime");
            return (Criteria) this;
        }

        public Criteria andDataUploadTimeLessThanOrEqualTo(Date value) {
            addCriterion("Data_Upload_Time <=", value, "dataUploadTime");
            return (Criteria) this;
        }

        public Criteria andDataUploadTimeIn(List<Date> values) {
            addCriterion("Data_Upload_Time in", values, "dataUploadTime");
            return (Criteria) this;
        }

        public Criteria andDataUploadTimeNotIn(List<Date> values) {
            addCriterion("Data_Upload_Time not in", values, "dataUploadTime");
            return (Criteria) this;
        }

        public Criteria andDataUploadTimeBetween(Date value1, Date value2) {
            addCriterion("Data_Upload_Time between", value1, value2, "dataUploadTime");
            return (Criteria) this;
        }

        public Criteria andDataUploadTimeNotBetween(Date value1, Date value2) {
            addCriterion("Data_Upload_Time not between", value1, value2, "dataUploadTime");
            return (Criteria) this;
        }

        public Criteria andSequenceNumberIsNull() {
            addCriterion("Sequence_number is null");
            return (Criteria) this;
        }

        public Criteria andSequenceNumberIsNotNull() {
            addCriterion("Sequence_number is not null");
            return (Criteria) this;
        }

        public Criteria andSequenceNumberEqualTo(Short value) {
            addCriterion("Sequence_number =", value, "sequenceNumber");
            return (Criteria) this;
        }

        public Criteria andSequenceNumberNotEqualTo(Short value) {
            addCriterion("Sequence_number <>", value, "sequenceNumber");
            return (Criteria) this;
        }

        public Criteria andSequenceNumberGreaterThan(Short value) {
            addCriterion("Sequence_number >", value, "sequenceNumber");
            return (Criteria) this;
        }

        public Criteria andSequenceNumberGreaterThanOrEqualTo(Short value) {
            addCriterion("Sequence_number >=", value, "sequenceNumber");
            return (Criteria) this;
        }

        public Criteria andSequenceNumberLessThan(Short value) {
            addCriterion("Sequence_number <", value, "sequenceNumber");
            return (Criteria) this;
        }

        public Criteria andSequenceNumberLessThanOrEqualTo(Short value) {
            addCriterion("Sequence_number <=", value, "sequenceNumber");
            return (Criteria) this;
        }

        public Criteria andSequenceNumberIn(List<Short> values) {
            addCriterion("Sequence_number in", values, "sequenceNumber");
            return (Criteria) this;
        }

        public Criteria andSequenceNumberNotIn(List<Short> values) {
            addCriterion("Sequence_number not in", values, "sequenceNumber");
            return (Criteria) this;
        }

        public Criteria andSequenceNumberBetween(Short value1, Short value2) {
            addCriterion("Sequence_number between", value1, value2, "sequenceNumber");
            return (Criteria) this;
        }

        public Criteria andSequenceNumberNotBetween(Short value1, Short value2) {
            addCriterion("Sequence_number not between", value1, value2, "sequenceNumber");
            return (Criteria) this;
        }

        public Criteria andExpectWaterIsNull() {
            addCriterion("Expect_Water is null");
            return (Criteria) this;
        }

        public Criteria andExpectWaterIsNotNull() {
            addCriterion("Expect_Water is not null");
            return (Criteria) this;
        }

        public Criteria andExpectWaterEqualTo(Short value) {
            addCriterion("Expect_Water =", value, "expectWater");
            return (Criteria) this;
        }

        public Criteria andExpectWaterNotEqualTo(Short value) {
            addCriterion("Expect_Water <>", value, "expectWater");
            return (Criteria) this;
        }

        public Criteria andExpectWaterGreaterThan(Short value) {
            addCriterion("Expect_Water >", value, "expectWater");
            return (Criteria) this;
        }

        public Criteria andExpectWaterGreaterThanOrEqualTo(Short value) {
            addCriterion("Expect_Water >=", value, "expectWater");
            return (Criteria) this;
        }

        public Criteria andExpectWaterLessThan(Short value) {
            addCriterion("Expect_Water <", value, "expectWater");
            return (Criteria) this;
        }

        public Criteria andExpectWaterLessThanOrEqualTo(Short value) {
            addCriterion("Expect_Water <=", value, "expectWater");
            return (Criteria) this;
        }

        public Criteria andExpectWaterIn(List<Short> values) {
            addCriterion("Expect_Water in", values, "expectWater");
            return (Criteria) this;
        }

        public Criteria andExpectWaterNotIn(List<Short> values) {
            addCriterion("Expect_Water not in", values, "expectWater");
            return (Criteria) this;
        }

        public Criteria andExpectWaterBetween(Short value1, Short value2) {
            addCriterion("Expect_Water between", value1, value2, "expectWater");
            return (Criteria) this;
        }

        public Criteria andExpectWaterNotBetween(Short value1, Short value2) {
            addCriterion("Expect_Water not between", value1, value2, "expectWater");
            return (Criteria) this;
        }

        public Criteria andExpectCementIsNull() {
            addCriterion("Expect_Cement is null");
            return (Criteria) this;
        }

        public Criteria andExpectCementIsNotNull() {
            addCriterion("Expect_Cement is not null");
            return (Criteria) this;
        }

        public Criteria andExpectCementEqualTo(Short value) {
            addCriterion("Expect_Cement =", value, "expectCement");
            return (Criteria) this;
        }

        public Criteria andExpectCementNotEqualTo(Short value) {
            addCriterion("Expect_Cement <>", value, "expectCement");
            return (Criteria) this;
        }

        public Criteria andExpectCementGreaterThan(Short value) {
            addCriterion("Expect_Cement >", value, "expectCement");
            return (Criteria) this;
        }

        public Criteria andExpectCementGreaterThanOrEqualTo(Short value) {
            addCriterion("Expect_Cement >=", value, "expectCement");
            return (Criteria) this;
        }

        public Criteria andExpectCementLessThan(Short value) {
            addCriterion("Expect_Cement <", value, "expectCement");
            return (Criteria) this;
        }

        public Criteria andExpectCementLessThanOrEqualTo(Short value) {
            addCriterion("Expect_Cement <=", value, "expectCement");
            return (Criteria) this;
        }

        public Criteria andExpectCementIn(List<Short> values) {
            addCriterion("Expect_Cement in", values, "expectCement");
            return (Criteria) this;
        }

        public Criteria andExpectCementNotIn(List<Short> values) {
            addCriterion("Expect_Cement not in", values, "expectCement");
            return (Criteria) this;
        }

        public Criteria andExpectCementBetween(Short value1, Short value2) {
            addCriterion("Expect_Cement between", value1, value2, "expectCement");
            return (Criteria) this;
        }

        public Criteria andExpectCementNotBetween(Short value1, Short value2) {
            addCriterion("Expect_Cement not between", value1, value2, "expectCement");
            return (Criteria) this;
        }

        public Criteria andRealWaterIsNull() {
            addCriterion("Real_Water is null");
            return (Criteria) this;
        }

        public Criteria andRealWaterIsNotNull() {
            addCriterion("Real_Water is not null");
            return (Criteria) this;
        }

        public Criteria andRealWaterEqualTo(Short value) {
            addCriterion("Real_Water =", value, "realWater");
            return (Criteria) this;
        }

        public Criteria andRealWaterNotEqualTo(Short value) {
            addCriterion("Real_Water <>", value, "realWater");
            return (Criteria) this;
        }

        public Criteria andRealWaterGreaterThan(Short value) {
            addCriterion("Real_Water >", value, "realWater");
            return (Criteria) this;
        }

        public Criteria andRealWaterGreaterThanOrEqualTo(Short value) {
            addCriterion("Real_Water >=", value, "realWater");
            return (Criteria) this;
        }

        public Criteria andRealWaterLessThan(Short value) {
            addCriterion("Real_Water <", value, "realWater");
            return (Criteria) this;
        }

        public Criteria andRealWaterLessThanOrEqualTo(Short value) {
            addCriterion("Real_Water <=", value, "realWater");
            return (Criteria) this;
        }

        public Criteria andRealWaterIn(List<Short> values) {
            addCriterion("Real_Water in", values, "realWater");
            return (Criteria) this;
        }

        public Criteria andRealWaterNotIn(List<Short> values) {
            addCriterion("Real_Water not in", values, "realWater");
            return (Criteria) this;
        }

        public Criteria andRealWaterBetween(Short value1, Short value2) {
            addCriterion("Real_Water between", value1, value2, "realWater");
            return (Criteria) this;
        }

        public Criteria andRealWaterNotBetween(Short value1, Short value2) {
            addCriterion("Real_Water not between", value1, value2, "realWater");
            return (Criteria) this;
        }

        public Criteria andRealCementIsNull() {
            addCriterion("Real_Cement is null");
            return (Criteria) this;
        }

        public Criteria andRealCementIsNotNull() {
            addCriterion("Real_Cement is not null");
            return (Criteria) this;
        }

        public Criteria andRealCementEqualTo(Short value) {
            addCriterion("Real_Cement =", value, "realCement");
            return (Criteria) this;
        }

        public Criteria andRealCementNotEqualTo(Short value) {
            addCriterion("Real_Cement <>", value, "realCement");
            return (Criteria) this;
        }

        public Criteria andRealCementGreaterThan(Short value) {
            addCriterion("Real_Cement >", value, "realCement");
            return (Criteria) this;
        }

        public Criteria andRealCementGreaterThanOrEqualTo(Short value) {
            addCriterion("Real_Cement >=", value, "realCement");
            return (Criteria) this;
        }

        public Criteria andRealCementLessThan(Short value) {
            addCriterion("Real_Cement <", value, "realCement");
            return (Criteria) this;
        }

        public Criteria andRealCementLessThanOrEqualTo(Short value) {
            addCriterion("Real_Cement <=", value, "realCement");
            return (Criteria) this;
        }

        public Criteria andRealCementIn(List<Short> values) {
            addCriterion("Real_Cement in", values, "realCement");
            return (Criteria) this;
        }

        public Criteria andRealCementNotIn(List<Short> values) {
            addCriterion("Real_Cement not in", values, "realCement");
            return (Criteria) this;
        }

        public Criteria andRealCementBetween(Short value1, Short value2) {
            addCriterion("Real_Cement between", value1, value2, "realCement");
            return (Criteria) this;
        }

        public Criteria andRealCementNotBetween(Short value1, Short value2) {
            addCriterion("Real_Cement not between", value1, value2, "realCement");
            return (Criteria) this;
        }

        public Criteria andRealCement2IsNull() {
            addCriterion("Real_Cement2 is null");
            return (Criteria) this;
        }

        public Criteria andRealCement2IsNotNull() {
            addCriterion("Real_Cement2 is not null");
            return (Criteria) this;
        }

        public Criteria andRealCement2EqualTo(Short value) {
            addCriterion("Real_Cement2 =", value, "realCement2");
            return (Criteria) this;
        }

        public Criteria andRealCement2NotEqualTo(Short value) {
            addCriterion("Real_Cement2 <>", value, "realCement2");
            return (Criteria) this;
        }

        public Criteria andRealCement2GreaterThan(Short value) {
            addCriterion("Real_Cement2 >", value, "realCement2");
            return (Criteria) this;
        }

        public Criteria andRealCement2GreaterThanOrEqualTo(Short value) {
            addCriterion("Real_Cement2 >=", value, "realCement2");
            return (Criteria) this;
        }

        public Criteria andRealCement2LessThan(Short value) {
            addCriterion("Real_Cement2 <", value, "realCement2");
            return (Criteria) this;
        }

        public Criteria andRealCement2LessThanOrEqualTo(Short value) {
            addCriterion("Real_Cement2 <=", value, "realCement2");
            return (Criteria) this;
        }

        public Criteria andRealCement2In(List<Short> values) {
            addCriterion("Real_Cement2 in", values, "realCement2");
            return (Criteria) this;
        }

        public Criteria andRealCement2NotIn(List<Short> values) {
            addCriterion("Real_Cement2 not in", values, "realCement2");
            return (Criteria) this;
        }

        public Criteria andRealCement2Between(Short value1, Short value2) {
            addCriterion("Real_Cement2 between", value1, value2, "realCement2");
            return (Criteria) this;
        }

        public Criteria andRealCement2NotBetween(Short value1, Short value2) {
            addCriterion("Real_Cement2 not between", value1, value2, "realCement2");
            return (Criteria) this;
        }

        public Criteria andRealSlurryIsNull() {
            addCriterion("Real_Slurry is null");
            return (Criteria) this;
        }

        public Criteria andRealSlurryIsNotNull() {
            addCriterion("Real_Slurry is not null");
            return (Criteria) this;
        }

        public Criteria andRealSlurryEqualTo(Short value) {
            addCriterion("Real_Slurry =", value, "realSlurry");
            return (Criteria) this;
        }

        public Criteria andRealSlurryNotEqualTo(Short value) {
            addCriterion("Real_Slurry <>", value, "realSlurry");
            return (Criteria) this;
        }

        public Criteria andRealSlurryGreaterThan(Short value) {
            addCriterion("Real_Slurry >", value, "realSlurry");
            return (Criteria) this;
        }

        public Criteria andRealSlurryGreaterThanOrEqualTo(Short value) {
            addCriterion("Real_Slurry >=", value, "realSlurry");
            return (Criteria) this;
        }

        public Criteria andRealSlurryLessThan(Short value) {
            addCriterion("Real_Slurry <", value, "realSlurry");
            return (Criteria) this;
        }

        public Criteria andRealSlurryLessThanOrEqualTo(Short value) {
            addCriterion("Real_Slurry <=", value, "realSlurry");
            return (Criteria) this;
        }

        public Criteria andRealSlurryIn(List<Short> values) {
            addCriterion("Real_Slurry in", values, "realSlurry");
            return (Criteria) this;
        }

        public Criteria andRealSlurryNotIn(List<Short> values) {
            addCriterion("Real_Slurry not in", values, "realSlurry");
            return (Criteria) this;
        }

        public Criteria andRealSlurryBetween(Short value1, Short value2) {
            addCriterion("Real_Slurry between", value1, value2, "realSlurry");
            return (Criteria) this;
        }

        public Criteria andRealSlurryNotBetween(Short value1, Short value2) {
            addCriterion("Real_Slurry not between", value1, value2, "realSlurry");
            return (Criteria) this;
        }

        public Criteria andWaterCementRatioIsNull() {
            addCriterion("Water_Cement_Ratio is null");
            return (Criteria) this;
        }

        public Criteria andWaterCementRatioIsNotNull() {
            addCriterion("Water_Cement_Ratio is not null");
            return (Criteria) this;
        }

        public Criteria andWaterCementRatioEqualTo(BigDecimal value) {
            addCriterion("Water_Cement_Ratio =", value, "waterCementRatio");
            return (Criteria) this;
        }

        public Criteria andWaterCementRatioNotEqualTo(BigDecimal value) {
            addCriterion("Water_Cement_Ratio <>", value, "waterCementRatio");
            return (Criteria) this;
        }

        public Criteria andWaterCementRatioGreaterThan(BigDecimal value) {
            addCriterion("Water_Cement_Ratio >", value, "waterCementRatio");
            return (Criteria) this;
        }

        public Criteria andWaterCementRatioGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("Water_Cement_Ratio >=", value, "waterCementRatio");
            return (Criteria) this;
        }

        public Criteria andWaterCementRatioLessThan(BigDecimal value) {
            addCriterion("Water_Cement_Ratio <", value, "waterCementRatio");
            return (Criteria) this;
        }

        public Criteria andWaterCementRatioLessThanOrEqualTo(BigDecimal value) {
            addCriterion("Water_Cement_Ratio <=", value, "waterCementRatio");
            return (Criteria) this;
        }

        public Criteria andWaterCementRatioIn(List<BigDecimal> values) {
            addCriterion("Water_Cement_Ratio in", values, "waterCementRatio");
            return (Criteria) this;
        }

        public Criteria andWaterCementRatioNotIn(List<BigDecimal> values) {
            addCriterion("Water_Cement_Ratio not in", values, "waterCementRatio");
            return (Criteria) this;
        }

        public Criteria andWaterCementRatioBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Water_Cement_Ratio between", value1, value2, "waterCementRatio");
            return (Criteria) this;
        }

        public Criteria andWaterCementRatioNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Water_Cement_Ratio not between", value1, value2, "waterCementRatio");
            return (Criteria) this;
        }

        public Criteria andDensityIsNull() {
            addCriterion("Density is null");
            return (Criteria) this;
        }

        public Criteria andDensityIsNotNull() {
            addCriterion("Density is not null");
            return (Criteria) this;
        }

        public Criteria andDensityEqualTo(BigDecimal value) {
            addCriterion("Density =", value, "density");
            return (Criteria) this;
        }

        public Criteria andDensityNotEqualTo(BigDecimal value) {
            addCriterion("Density <>", value, "density");
            return (Criteria) this;
        }

        public Criteria andDensityGreaterThan(BigDecimal value) {
            addCriterion("Density >", value, "density");
            return (Criteria) this;
        }

        public Criteria andDensityGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("Density >=", value, "density");
            return (Criteria) this;
        }

        public Criteria andDensityLessThan(BigDecimal value) {
            addCriterion("Density <", value, "density");
            return (Criteria) this;
        }

        public Criteria andDensityLessThanOrEqualTo(BigDecimal value) {
            addCriterion("Density <=", value, "density");
            return (Criteria) this;
        }

        public Criteria andDensityIn(List<BigDecimal> values) {
            addCriterion("Density in", values, "density");
            return (Criteria) this;
        }

        public Criteria andDensityNotIn(List<BigDecimal> values) {
            addCriterion("Density not in", values, "density");
            return (Criteria) this;
        }

        public Criteria andDensityBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Density between", value1, value2, "density");
            return (Criteria) this;
        }

        public Criteria andDensityNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Density not between", value1, value2, "density");
            return (Criteria) this;
        }

        public Criteria andMixEquipmentIdIsNull() {
            addCriterion("Mix_Equipment_ID is null");
            return (Criteria) this;
        }

        public Criteria andMixEquipmentIdIsNotNull() {
            addCriterion("Mix_Equipment_ID is not null");
            return (Criteria) this;
        }

        public Criteria andMixEquipmentIdEqualTo(String value) {
            addCriterion("Mix_Equipment_ID =", value, "mixEquipmentId");
            return (Criteria) this;
        }

        public Criteria andMixEquipmentIdNotEqualTo(String value) {
            addCriterion("Mix_Equipment_ID <>", value, "mixEquipmentId");
            return (Criteria) this;
        }

        public Criteria andMixEquipmentIdGreaterThan(String value) {
            addCriterion("Mix_Equipment_ID >", value, "mixEquipmentId");
            return (Criteria) this;
        }

        public Criteria andMixEquipmentIdGreaterThanOrEqualTo(String value) {
            addCriterion("Mix_Equipment_ID >=", value, "mixEquipmentId");
            return (Criteria) this;
        }

        public Criteria andMixEquipmentIdLessThan(String value) {
            addCriterion("Mix_Equipment_ID <", value, "mixEquipmentId");
            return (Criteria) this;
        }

        public Criteria andMixEquipmentIdLessThanOrEqualTo(String value) {
            addCriterion("Mix_Equipment_ID <=", value, "mixEquipmentId");
            return (Criteria) this;
        }

        public Criteria andMixEquipmentIdLike(String value) {
            addCriterion("Mix_Equipment_ID like", value, "mixEquipmentId");
            return (Criteria) this;
        }

        public Criteria andMixEquipmentIdNotLike(String value) {
            addCriterion("Mix_Equipment_ID not like", value, "mixEquipmentId");
            return (Criteria) this;
        }

        public Criteria andMixEquipmentIdIn(List<String> values) {
            addCriterion("Mix_Equipment_ID in", values, "mixEquipmentId");
            return (Criteria) this;
        }

        public Criteria andMixEquipmentIdNotIn(List<String> values) {
            addCriterion("Mix_Equipment_ID not in", values, "mixEquipmentId");
            return (Criteria) this;
        }

        public Criteria andMixEquipmentIdBetween(String value1, String value2) {
            addCriterion("Mix_Equipment_ID between", value1, value2, "mixEquipmentId");
            return (Criteria) this;
        }

        public Criteria andMixEquipmentIdNotBetween(String value1, String value2) {
            addCriterion("Mix_Equipment_ID not between", value1, value2, "mixEquipmentId");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNull() {
            addCriterion("Project_ID is null");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNotNull() {
            addCriterion("Project_ID is not null");
            return (Criteria) this;
        }

        public Criteria andProjectIdEqualTo(String value) {
            addCriterion("Project_ID =", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotEqualTo(String value) {
            addCriterion("Project_ID <>", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThan(String value) {
            addCriterion("Project_ID >", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThanOrEqualTo(String value) {
            addCriterion("Project_ID >=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThan(String value) {
            addCriterion("Project_ID <", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThanOrEqualTo(String value) {
            addCriterion("Project_ID <=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLike(String value) {
            addCriterion("Project_ID like", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotLike(String value) {
            addCriterion("Project_ID not like", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdIn(List<String> values) {
            addCriterion("Project_ID in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotIn(List<String> values) {
            addCriterion("Project_ID not in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdBetween(String value1, String value2) {
            addCriterion("Project_ID between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotBetween(String value1, String value2) {
            addCriterion("Project_ID not between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andSectionIdIsNull() {
            addCriterion("Section_ID is null");
            return (Criteria) this;
        }

        public Criteria andSectionIdIsNotNull() {
            addCriterion("Section_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSectionIdEqualTo(Integer value) {
            addCriterion("Section_ID =", value, "sectionId");
            return (Criteria) this;
        }

        public Criteria andSectionIdNotEqualTo(Integer value) {
            addCriterion("Section_ID <>", value, "sectionId");
            return (Criteria) this;
        }

        public Criteria andSectionIdGreaterThan(Integer value) {
            addCriterion("Section_ID >", value, "sectionId");
            return (Criteria) this;
        }

        public Criteria andSectionIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("Section_ID >=", value, "sectionId");
            return (Criteria) this;
        }

        public Criteria andSectionIdLessThan(Integer value) {
            addCriterion("Section_ID <", value, "sectionId");
            return (Criteria) this;
        }

        public Criteria andSectionIdLessThanOrEqualTo(Integer value) {
            addCriterion("Section_ID <=", value, "sectionId");
            return (Criteria) this;
        }

        public Criteria andSectionIdIn(List<Integer> values) {
            addCriterion("Section_ID in", values, "sectionId");
            return (Criteria) this;
        }

        public Criteria andSectionIdNotIn(List<Integer> values) {
            addCriterion("Section_ID not in", values, "sectionId");
            return (Criteria) this;
        }

        public Criteria andSectionIdBetween(Integer value1, Integer value2) {
            addCriterion("Section_ID between", value1, value2, "sectionId");
            return (Criteria) this;
        }

        public Criteria andSectionIdNotBetween(Integer value1, Integer value2) {
            addCriterion("Section_ID not between", value1, value2, "sectionId");
            return (Criteria) this;
        }

        public Criteria andMixEquipmentCodeIsNull() {
            addCriterion("Mix_Equipment_Code is null");
            return (Criteria) this;
        }

        public Criteria andMixEquipmentCodeIsNotNull() {
            addCriterion("Mix_Equipment_Code is not null");
            return (Criteria) this;
        }

        public Criteria andMixEquipmentCodeEqualTo(String value) {
            addCriterion("Mix_Equipment_Code =", value, "mixEquipmentCode");
            return (Criteria) this;
        }

        public Criteria andMixEquipmentCodeNotEqualTo(String value) {
            addCriterion("Mix_Equipment_Code <>", value, "mixEquipmentCode");
            return (Criteria) this;
        }

        public Criteria andMixEquipmentCodeGreaterThan(String value) {
            addCriterion("Mix_Equipment_Code >", value, "mixEquipmentCode");
            return (Criteria) this;
        }

        public Criteria andMixEquipmentCodeGreaterThanOrEqualTo(String value) {
            addCriterion("Mix_Equipment_Code >=", value, "mixEquipmentCode");
            return (Criteria) this;
        }

        public Criteria andMixEquipmentCodeLessThan(String value) {
            addCriterion("Mix_Equipment_Code <", value, "mixEquipmentCode");
            return (Criteria) this;
        }

        public Criteria andMixEquipmentCodeLessThanOrEqualTo(String value) {
            addCriterion("Mix_Equipment_Code <=", value, "mixEquipmentCode");
            return (Criteria) this;
        }

        public Criteria andMixEquipmentCodeLike(String value) {
            addCriterion("Mix_Equipment_Code like", value, "mixEquipmentCode");
            return (Criteria) this;
        }

        public Criteria andMixEquipmentCodeNotLike(String value) {
            addCriterion("Mix_Equipment_Code not like", value, "mixEquipmentCode");
            return (Criteria) this;
        }

        public Criteria andMixEquipmentCodeIn(List<String> values) {
            addCriterion("Mix_Equipment_Code in", values, "mixEquipmentCode");
            return (Criteria) this;
        }

        public Criteria andMixEquipmentCodeNotIn(List<String> values) {
            addCriterion("Mix_Equipment_Code not in", values, "mixEquipmentCode");
            return (Criteria) this;
        }

        public Criteria andMixEquipmentCodeBetween(String value1, String value2) {
            addCriterion("Mix_Equipment_Code between", value1, value2, "mixEquipmentCode");
            return (Criteria) this;
        }

        public Criteria andMixEquipmentCodeNotBetween(String value1, String value2) {
            addCriterion("Mix_Equipment_Code not between", value1, value2, "mixEquipmentCode");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_luding_slurry_mix_record
     *
     * @mbg.generated do_not_delete_during_merge Tue Dec 27 12:28:42 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_luding_slurry_mix_record
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}