package com.device.business.equip.bean;

import java.math.BigDecimal;
import java.util.Date;

public class SlurryPerdayBean {
	
	private String equipmentName;
	
	
	
    public String getEquipmentName() {
		return equipmentName;
	}

	public void setEquipmentName(String equipmentName) {
		this.equipmentName = equipmentName;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_slurry_perday.Project_ID
     *
     * @mbg.generated Sat Jan 14 13:41:07 CST 2017
     */
    private Integer projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_slurry_perday.Section_ID
     *
     * @mbg.generated Sat Jan 14 13:41:07 CST 2017
     */
    private String sectionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_slurry_perday.Equipment_ID
     *
     * @mbg.generated Sat Jan 14 13:41:07 CST 2017
     */
    private String equipmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_slurry_perday.Date_Amount
     *
     * @mbg.generated Sat Jan 14 13:41:07 CST 2017
     */
    private Date dateAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_slurry_perday.Expect_Water_Amount
     *
     * @mbg.generated Sat Jan 14 13:41:07 CST 2017
     */
    private Integer expectWaterAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_slurry_perday.Expect_Cement_Amount
     *
     * @mbg.generated Sat Jan 14 13:41:07 CST 2017
     */
    private Integer expectCementAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_slurry_perday.Expect_Slurry_Amount
     *
     * @mbg.generated Sat Jan 14 13:41:07 CST 2017
     */
    private Integer expectSlurryAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_slurry_perday.Expect_Pile_Amount
     *
     * @mbg.generated Sat Jan 14 13:41:07 CST 2017
     */
    private Integer expectPileAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_slurry_perday.Real_Water_Amount
     *
     * @mbg.generated Sat Jan 14 13:41:07 CST 2017
     */
    private Integer realWaterAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_slurry_perday.Real_Cement_Amount
     *
     * @mbg.generated Sat Jan 14 13:41:07 CST 2017
     */
    private Integer realCementAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_slurry_perday.Real_Slurry_Amount
     *
     * @mbg.generated Sat Jan 14 13:41:07 CST 2017
     */
    private Integer realSlurryAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_slurry_perday.Real_Pile_Amount
     *
     * @mbg.generated Sat Jan 14 13:41:07 CST 2017
     */
    private Integer realPileAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_slurry_perday.Section_Name
     *
     * @mbg.generated Sat Jan 14 13:41:07 CST 2017
     */
    private String sectionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_slurry_perday.Project_Name
     *
     * @mbg.generated Sat Jan 14 13:41:07 CST 2017
     */
    private String projectName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_slurry_perday.Water_Cement_Ratio
     *
     * @mbg.generated Sat Jan 14 13:41:07 CST 2017
     */
    private BigDecimal waterCementRatio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_slurry_perday.Density
     *
     * @mbg.generated Sat Jan 14 13:41:07 CST 2017
     */
    private BigDecimal density;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_slurry_perday.Project_ID
     *
     * @return the value of t_luding_slurry_perday.Project_ID
     *
     * @mbg.generated Sat Jan 14 13:41:07 CST 2017
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_slurry_perday.Project_ID
     *
     * @param projectId the value for t_luding_slurry_perday.Project_ID
     *
     * @mbg.generated Sat Jan 14 13:41:07 CST 2017
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_slurry_perday.Section_ID
     *
     * @return the value of t_luding_slurry_perday.Section_ID
     *
     * @mbg.generated Sat Jan 14 13:41:07 CST 2017
     */
    public String getSectionId() {
        return sectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_slurry_perday.Section_ID
     *
     * @param sectionId the value for t_luding_slurry_perday.Section_ID
     *
     * @mbg.generated Sat Jan 14 13:41:07 CST 2017
     */
    public void setSectionId(String sectionId) {
        this.sectionId = sectionId == null ? null : sectionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_slurry_perday.Equipment_ID
     *
     * @return the value of t_luding_slurry_perday.Equipment_ID
     *
     * @mbg.generated Sat Jan 14 13:41:07 CST 2017
     */
    public String getEquipmentId() {
        return equipmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_slurry_perday.Equipment_ID
     *
     * @param equipmentId the value for t_luding_slurry_perday.Equipment_ID
     *
     * @mbg.generated Sat Jan 14 13:41:07 CST 2017
     */
    public void setEquipmentId(String equipmentId) {
        this.equipmentId = equipmentId == null ? null : equipmentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_slurry_perday.Date_Amount
     *
     * @return the value of t_luding_slurry_perday.Date_Amount
     *
     * @mbg.generated Sat Jan 14 13:41:07 CST 2017
     */
    public Date getDateAmount() {
        return dateAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_slurry_perday.Date_Amount
     *
     * @param dateAmount the value for t_luding_slurry_perday.Date_Amount
     *
     * @mbg.generated Sat Jan 14 13:41:07 CST 2017
     */
    public void setDateAmount(Date dateAmount) {
        this.dateAmount = dateAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_slurry_perday.Expect_Water_Amount
     *
     * @return the value of t_luding_slurry_perday.Expect_Water_Amount
     *
     * @mbg.generated Sat Jan 14 13:41:07 CST 2017
     */
    public Integer getExpectWaterAmount() {
        return expectWaterAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_slurry_perday.Expect_Water_Amount
     *
     * @param expectWaterAmount the value for t_luding_slurry_perday.Expect_Water_Amount
     *
     * @mbg.generated Sat Jan 14 13:41:07 CST 2017
     */
    public void setExpectWaterAmount(Integer expectWaterAmount) {
        this.expectWaterAmount = expectWaterAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_slurry_perday.Expect_Cement_Amount
     *
     * @return the value of t_luding_slurry_perday.Expect_Cement_Amount
     *
     * @mbg.generated Sat Jan 14 13:41:07 CST 2017
     */
    public Integer getExpectCementAmount() {
        return expectCementAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_slurry_perday.Expect_Cement_Amount
     *
     * @param expectCementAmount the value for t_luding_slurry_perday.Expect_Cement_Amount
     *
     * @mbg.generated Sat Jan 14 13:41:07 CST 2017
     */
    public void setExpectCementAmount(Integer expectCementAmount) {
        this.expectCementAmount = expectCementAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_slurry_perday.Expect_Slurry_Amount
     *
     * @return the value of t_luding_slurry_perday.Expect_Slurry_Amount
     *
     * @mbg.generated Sat Jan 14 13:41:07 CST 2017
     */
    public Integer getExpectSlurryAmount() {
        return expectSlurryAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_slurry_perday.Expect_Slurry_Amount
     *
     * @param expectSlurryAmount the value for t_luding_slurry_perday.Expect_Slurry_Amount
     *
     * @mbg.generated Sat Jan 14 13:41:07 CST 2017
     */
    public void setExpectSlurryAmount(Integer expectSlurryAmount) {
        this.expectSlurryAmount = expectSlurryAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_slurry_perday.Expect_Pile_Amount
     *
     * @return the value of t_luding_slurry_perday.Expect_Pile_Amount
     *
     * @mbg.generated Sat Jan 14 13:41:07 CST 2017
     */
    public Integer getExpectPileAmount() {
        return expectPileAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_slurry_perday.Expect_Pile_Amount
     *
     * @param expectPileAmount the value for t_luding_slurry_perday.Expect_Pile_Amount
     *
     * @mbg.generated Sat Jan 14 13:41:07 CST 2017
     */
    public void setExpectPileAmount(Integer expectPileAmount) {
        this.expectPileAmount = expectPileAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_slurry_perday.Real_Water_Amount
     *
     * @return the value of t_luding_slurry_perday.Real_Water_Amount
     *
     * @mbg.generated Sat Jan 14 13:41:07 CST 2017
     */
    public Integer getRealWaterAmount() {
        return realWaterAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_slurry_perday.Real_Water_Amount
     *
     * @param realWaterAmount the value for t_luding_slurry_perday.Real_Water_Amount
     *
     * @mbg.generated Sat Jan 14 13:41:07 CST 2017
     */
    public void setRealWaterAmount(Integer realWaterAmount) {
        this.realWaterAmount = realWaterAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_slurry_perday.Real_Cement_Amount
     *
     * @return the value of t_luding_slurry_perday.Real_Cement_Amount
     *
     * @mbg.generated Sat Jan 14 13:41:07 CST 2017
     */
    public Integer getRealCementAmount() {
        return realCementAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_slurry_perday.Real_Cement_Amount
     *
     * @param realCementAmount the value for t_luding_slurry_perday.Real_Cement_Amount
     *
     * @mbg.generated Sat Jan 14 13:41:07 CST 2017
     */
    public void setRealCementAmount(Integer realCementAmount) {
        this.realCementAmount = realCementAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_slurry_perday.Real_Slurry_Amount
     *
     * @return the value of t_luding_slurry_perday.Real_Slurry_Amount
     *
     * @mbg.generated Sat Jan 14 13:41:07 CST 2017
     */
    public Integer getRealSlurryAmount() {
        return realSlurryAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_slurry_perday.Real_Slurry_Amount
     *
     * @param realSlurryAmount the value for t_luding_slurry_perday.Real_Slurry_Amount
     *
     * @mbg.generated Sat Jan 14 13:41:07 CST 2017
     */
    public void setRealSlurryAmount(Integer realSlurryAmount) {
        this.realSlurryAmount = realSlurryAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_slurry_perday.Real_Pile_Amount
     *
     * @return the value of t_luding_slurry_perday.Real_Pile_Amount
     *
     * @mbg.generated Sat Jan 14 13:41:07 CST 2017
     */
    public Integer getRealPileAmount() {
        return realPileAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_slurry_perday.Real_Pile_Amount
     *
     * @param realPileAmount the value for t_luding_slurry_perday.Real_Pile_Amount
     *
     * @mbg.generated Sat Jan 14 13:41:07 CST 2017
     */
    public void setRealPileAmount(Integer realPileAmount) {
        this.realPileAmount = realPileAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_slurry_perday.Section_Name
     *
     * @return the value of t_luding_slurry_perday.Section_Name
     *
     * @mbg.generated Sat Jan 14 13:41:07 CST 2017
     */
    public String getSectionName() {
        return sectionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_slurry_perday.Section_Name
     *
     * @param sectionName the value for t_luding_slurry_perday.Section_Name
     *
     * @mbg.generated Sat Jan 14 13:41:07 CST 2017
     */
    public void setSectionName(String sectionName) {
        this.sectionName = sectionName == null ? null : sectionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_slurry_perday.Project_Name
     *
     * @return the value of t_luding_slurry_perday.Project_Name
     *
     * @mbg.generated Sat Jan 14 13:41:07 CST 2017
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_slurry_perday.Project_Name
     *
     * @param projectName the value for t_luding_slurry_perday.Project_Name
     *
     * @mbg.generated Sat Jan 14 13:41:07 CST 2017
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_slurry_perday.Water_Cement_Ratio
     *
     * @return the value of t_luding_slurry_perday.Water_Cement_Ratio
     *
     * @mbg.generated Sat Jan 14 13:41:07 CST 2017
     */
    public BigDecimal getWaterCementRatio() {
        return waterCementRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_slurry_perday.Water_Cement_Ratio
     *
     * @param waterCementRatio the value for t_luding_slurry_perday.Water_Cement_Ratio
     *
     * @mbg.generated Sat Jan 14 13:41:07 CST 2017
     */
    public void setWaterCementRatio(BigDecimal waterCementRatio) {
        this.waterCementRatio = waterCementRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_slurry_perday.Density
     *
     * @return the value of t_luding_slurry_perday.Density
     *
     * @mbg.generated Sat Jan 14 13:41:07 CST 2017
     */
    public BigDecimal getDensity() {
        return density;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_slurry_perday.Density
     *
     * @param density the value for t_luding_slurry_perday.Density
     *
     * @mbg.generated Sat Jan 14 13:41:07 CST 2017
     */
    public void setDensity(BigDecimal density) {
        this.density = density;
    }
}