package com.device.business.equip.bean;

import java.math.BigDecimal;
import java.util.Date;

public class SlurryRecordBean {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_slurry_mix_record.ID
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_slurry_mix_record.MIx_Time
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    private Date mixTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_slurry_mix_record.Data_Upload_Time
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    private Date dataUploadTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_slurry_mix_record.Sequence_number
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    private Short sequenceNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_slurry_mix_record.Expect_Water
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    private Short expectWater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_slurry_mix_record.Expect_Cement
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    private Short expectCement;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_slurry_mix_record.Real_Water
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    private Short realWater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_slurry_mix_record.Real_Cement
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    private Short realCement;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_slurry_mix_record.Real_Cement2
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    private Short realCement2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_slurry_mix_record.Real_Slurry
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    private Short realSlurry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_slurry_mix_record.Water_Cement_Ratio
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    private BigDecimal waterCementRatio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_slurry_mix_record.Density
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    private BigDecimal density;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_slurry_mix_record.Mix_Equipment_ID
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    private String mixEquipmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_slurry_mix_record.Project_ID
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    private String projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_slurry_mix_record.Section_ID
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    private Integer sectionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_slurry_mix_record.Mix_Equipment_Code
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    private String mixEquipmentCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_slurry_mix_record.ID
     *
     * @return the value of t_luding_slurry_mix_record.ID
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_slurry_mix_record.ID
     *
     * @param id the value for t_luding_slurry_mix_record.ID
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_slurry_mix_record.MIx_Time
     *
     * @return the value of t_luding_slurry_mix_record.MIx_Time
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public Date getMixTime() {
        return mixTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_slurry_mix_record.MIx_Time
     *
     * @param mixTime the value for t_luding_slurry_mix_record.MIx_Time
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public void setMixTime(Date mixTime) {
        this.mixTime = mixTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_slurry_mix_record.Data_Upload_Time
     *
     * @return the value of t_luding_slurry_mix_record.Data_Upload_Time
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public Date getDataUploadTime() {
        return dataUploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_slurry_mix_record.Data_Upload_Time
     *
     * @param dataUploadTime the value for t_luding_slurry_mix_record.Data_Upload_Time
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public void setDataUploadTime(Date dataUploadTime) {
        this.dataUploadTime = dataUploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_slurry_mix_record.Sequence_number
     *
     * @return the value of t_luding_slurry_mix_record.Sequence_number
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public Short getSequenceNumber() {
        return sequenceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_slurry_mix_record.Sequence_number
     *
     * @param sequenceNumber the value for t_luding_slurry_mix_record.Sequence_number
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public void setSequenceNumber(Short sequenceNumber) {
        this.sequenceNumber = sequenceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_slurry_mix_record.Expect_Water
     *
     * @return the value of t_luding_slurry_mix_record.Expect_Water
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public Short getExpectWater() {
        return expectWater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_slurry_mix_record.Expect_Water
     *
     * @param expectWater the value for t_luding_slurry_mix_record.Expect_Water
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public void setExpectWater(Short expectWater) {
        this.expectWater = expectWater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_slurry_mix_record.Expect_Cement
     *
     * @return the value of t_luding_slurry_mix_record.Expect_Cement
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public Short getExpectCement() {
        return expectCement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_slurry_mix_record.Expect_Cement
     *
     * @param expectCement the value for t_luding_slurry_mix_record.Expect_Cement
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public void setExpectCement(Short expectCement) {
        this.expectCement = expectCement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_slurry_mix_record.Real_Water
     *
     * @return the value of t_luding_slurry_mix_record.Real_Water
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public Short getRealWater() {
        return realWater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_slurry_mix_record.Real_Water
     *
     * @param realWater the value for t_luding_slurry_mix_record.Real_Water
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public void setRealWater(Short realWater) {
        this.realWater = realWater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_slurry_mix_record.Real_Cement
     *
     * @return the value of t_luding_slurry_mix_record.Real_Cement
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public Short getRealCement() {
        return realCement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_slurry_mix_record.Real_Cement
     *
     * @param realCement the value for t_luding_slurry_mix_record.Real_Cement
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public void setRealCement(Short realCement) {
        this.realCement = realCement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_slurry_mix_record.Real_Cement2
     *
     * @return the value of t_luding_slurry_mix_record.Real_Cement2
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public Short getRealCement2() {
        return realCement2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_slurry_mix_record.Real_Cement2
     *
     * @param realCement2 the value for t_luding_slurry_mix_record.Real_Cement2
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public void setRealCement2(Short realCement2) {
        this.realCement2 = realCement2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_slurry_mix_record.Real_Slurry
     *
     * @return the value of t_luding_slurry_mix_record.Real_Slurry
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public Short getRealSlurry() {
        return realSlurry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_slurry_mix_record.Real_Slurry
     *
     * @param realSlurry the value for t_luding_slurry_mix_record.Real_Slurry
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public void setRealSlurry(Short realSlurry) {
        this.realSlurry = realSlurry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_slurry_mix_record.Water_Cement_Ratio
     *
     * @return the value of t_luding_slurry_mix_record.Water_Cement_Ratio
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public BigDecimal getWaterCementRatio() {
        return waterCementRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_slurry_mix_record.Water_Cement_Ratio
     *
     * @param waterCementRatio the value for t_luding_slurry_mix_record.Water_Cement_Ratio
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public void setWaterCementRatio(BigDecimal waterCementRatio) {
        this.waterCementRatio = waterCementRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_slurry_mix_record.Density
     *
     * @return the value of t_luding_slurry_mix_record.Density
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public BigDecimal getDensity() {
        return density;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_slurry_mix_record.Density
     *
     * @param density the value for t_luding_slurry_mix_record.Density
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public void setDensity(BigDecimal density) {
        this.density = density;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_slurry_mix_record.Mix_Equipment_ID
     *
     * @return the value of t_luding_slurry_mix_record.Mix_Equipment_ID
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public String getMixEquipmentId() {
        return mixEquipmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_slurry_mix_record.Mix_Equipment_ID
     *
     * @param mixEquipmentId the value for t_luding_slurry_mix_record.Mix_Equipment_ID
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public void setMixEquipmentId(String mixEquipmentId) {
        this.mixEquipmentId = mixEquipmentId == null ? null : mixEquipmentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_slurry_mix_record.Project_ID
     *
     * @return the value of t_luding_slurry_mix_record.Project_ID
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_slurry_mix_record.Project_ID
     *
     * @param projectId the value for t_luding_slurry_mix_record.Project_ID
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId == null ? null : projectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_slurry_mix_record.Section_ID
     *
     * @return the value of t_luding_slurry_mix_record.Section_ID
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public Integer getSectionId() {
        return sectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_slurry_mix_record.Section_ID
     *
     * @param sectionId the value for t_luding_slurry_mix_record.Section_ID
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public void setSectionId(Integer sectionId) {
        this.sectionId = sectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_slurry_mix_record.Mix_Equipment_Code
     *
     * @return the value of t_luding_slurry_mix_record.Mix_Equipment_Code
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public String getMixEquipmentCode() {
        return mixEquipmentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_slurry_mix_record.Mix_Equipment_Code
     *
     * @param mixEquipmentCode the value for t_luding_slurry_mix_record.Mix_Equipment_Code
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public void setMixEquipmentCode(String mixEquipmentCode) {
        this.mixEquipmentCode = mixEquipmentCode == null ? null : mixEquipmentCode.trim();
    }
}