package com.device.business.equip.bean;

import java.math.BigDecimal;

public class SlurryAmountBean extends SlurryAmountBeanKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_slurry_amount.Section_Name
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    private String sectionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_slurry_amount.Section_Leader
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    private String sectionLeader;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_slurry_amount.Project_Name
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    private String projectName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_slurry_amount.Expect_Water_Amount
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    private Integer expectWaterAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_slurry_amount.Expect_Cement_Amount
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    private Integer expectCementAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_slurry_amount.Real_Water_Amount
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    private Integer realWaterAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_slurry_amount.Real_Cement_Amount
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    private Integer realCementAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_slurry_amount.Real_Cement2_Amount
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    private Integer realCement2Amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_slurry_amount.Real_Slurry_Amount
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    private Integer realSlurryAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_slurry_amount.Water_Cement_Ratio
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    private BigDecimal waterCementRatio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_luding_slurry_amount.Density
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    private BigDecimal density;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_slurry_amount.Section_Name
     *
     * @return the value of t_luding_slurry_amount.Section_Name
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public String getSectionName() {
        return sectionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_slurry_amount.Section_Name
     *
     * @param sectionName the value for t_luding_slurry_amount.Section_Name
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public void setSectionName(String sectionName) {
        this.sectionName = sectionName == null ? null : sectionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_slurry_amount.Section_Leader
     *
     * @return the value of t_luding_slurry_amount.Section_Leader
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public String getSectionLeader() {
        return sectionLeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_slurry_amount.Section_Leader
     *
     * @param sectionLeader the value for t_luding_slurry_amount.Section_Leader
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public void setSectionLeader(String sectionLeader) {
        this.sectionLeader = sectionLeader == null ? null : sectionLeader.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_slurry_amount.Project_Name
     *
     * @return the value of t_luding_slurry_amount.Project_Name
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_slurry_amount.Project_Name
     *
     * @param projectName the value for t_luding_slurry_amount.Project_Name
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_slurry_amount.Expect_Water_Amount
     *
     * @return the value of t_luding_slurry_amount.Expect_Water_Amount
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public Integer getExpectWaterAmount() {
        return expectWaterAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_slurry_amount.Expect_Water_Amount
     *
     * @param expectWaterAmount the value for t_luding_slurry_amount.Expect_Water_Amount
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public void setExpectWaterAmount(Integer expectWaterAmount) {
        this.expectWaterAmount = expectWaterAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_slurry_amount.Expect_Cement_Amount
     *
     * @return the value of t_luding_slurry_amount.Expect_Cement_Amount
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public Integer getExpectCementAmount() {
        return expectCementAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_slurry_amount.Expect_Cement_Amount
     *
     * @param expectCementAmount the value for t_luding_slurry_amount.Expect_Cement_Amount
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public void setExpectCementAmount(Integer expectCementAmount) {
        this.expectCementAmount = expectCementAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_slurry_amount.Real_Water_Amount
     *
     * @return the value of t_luding_slurry_amount.Real_Water_Amount
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public Integer getRealWaterAmount() {
        return realWaterAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_slurry_amount.Real_Water_Amount
     *
     * @param realWaterAmount the value for t_luding_slurry_amount.Real_Water_Amount
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public void setRealWaterAmount(Integer realWaterAmount) {
        this.realWaterAmount = realWaterAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_slurry_amount.Real_Cement_Amount
     *
     * @return the value of t_luding_slurry_amount.Real_Cement_Amount
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public Integer getRealCementAmount() {
        return realCementAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_slurry_amount.Real_Cement_Amount
     *
     * @param realCementAmount the value for t_luding_slurry_amount.Real_Cement_Amount
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public void setRealCementAmount(Integer realCementAmount) {
        this.realCementAmount = realCementAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_slurry_amount.Real_Cement2_Amount
     *
     * @return the value of t_luding_slurry_amount.Real_Cement2_Amount
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public Integer getRealCement2Amount() {
        return realCement2Amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_slurry_amount.Real_Cement2_Amount
     *
     * @param realCement2Amount the value for t_luding_slurry_amount.Real_Cement2_Amount
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public void setRealCement2Amount(Integer realCement2Amount) {
        this.realCement2Amount = realCement2Amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_slurry_amount.Real_Slurry_Amount
     *
     * @return the value of t_luding_slurry_amount.Real_Slurry_Amount
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public Integer getRealSlurryAmount() {
        return realSlurryAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_slurry_amount.Real_Slurry_Amount
     *
     * @param realSlurryAmount the value for t_luding_slurry_amount.Real_Slurry_Amount
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public void setRealSlurryAmount(Integer realSlurryAmount) {
        this.realSlurryAmount = realSlurryAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_slurry_amount.Water_Cement_Ratio
     *
     * @return the value of t_luding_slurry_amount.Water_Cement_Ratio
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public BigDecimal getWaterCementRatio() {
        return waterCementRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_slurry_amount.Water_Cement_Ratio
     *
     * @param waterCementRatio the value for t_luding_slurry_amount.Water_Cement_Ratio
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public void setWaterCementRatio(BigDecimal waterCementRatio) {
        this.waterCementRatio = waterCementRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_luding_slurry_amount.Density
     *
     * @return the value of t_luding_slurry_amount.Density
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public BigDecimal getDensity() {
        return density;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_luding_slurry_amount.Density
     *
     * @param density the value for t_luding_slurry_amount.Density
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public void setDensity(BigDecimal density) {
        this.density = density;
    }
}