package com.device.business.equip.bean;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class SlurryAmountBeanExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_luding_slurry_amount
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_luding_slurry_amount
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_luding_slurry_amount
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_slurry_amount
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public SlurryAmountBeanExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_slurry_amount
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_slurry_amount
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_slurry_amount
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_slurry_amount
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_slurry_amount
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_slurry_amount
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_slurry_amount
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_slurry_amount
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_slurry_amount
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_luding_slurry_amount
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_luding_slurry_amount
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSectionIdIsNull() {
            addCriterion("Section_ID is null");
            return (Criteria) this;
        }

        public Criteria andSectionIdIsNotNull() {
            addCriterion("Section_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSectionIdEqualTo(String value) {
            addCriterion("Section_ID =", value, "sectionId");
            return (Criteria) this;
        }

        public Criteria andSectionIdNotEqualTo(String value) {
            addCriterion("Section_ID <>", value, "sectionId");
            return (Criteria) this;
        }

        public Criteria andSectionIdGreaterThan(String value) {
            addCriterion("Section_ID >", value, "sectionId");
            return (Criteria) this;
        }

        public Criteria andSectionIdGreaterThanOrEqualTo(String value) {
            addCriterion("Section_ID >=", value, "sectionId");
            return (Criteria) this;
        }

        public Criteria andSectionIdLessThan(String value) {
            addCriterion("Section_ID <", value, "sectionId");
            return (Criteria) this;
        }

        public Criteria andSectionIdLessThanOrEqualTo(String value) {
            addCriterion("Section_ID <=", value, "sectionId");
            return (Criteria) this;
        }

        public Criteria andSectionIdLike(String value) {
            addCriterion("Section_ID like", value, "sectionId");
            return (Criteria) this;
        }

        public Criteria andSectionIdNotLike(String value) {
            addCriterion("Section_ID not like", value, "sectionId");
            return (Criteria) this;
        }

        public Criteria andSectionIdIn(List<String> values) {
            addCriterion("Section_ID in", values, "sectionId");
            return (Criteria) this;
        }

        public Criteria andSectionIdNotIn(List<String> values) {
            addCriterion("Section_ID not in", values, "sectionId");
            return (Criteria) this;
        }

        public Criteria andSectionIdBetween(String value1, String value2) {
            addCriterion("Section_ID between", value1, value2, "sectionId");
            return (Criteria) this;
        }

        public Criteria andSectionIdNotBetween(String value1, String value2) {
            addCriterion("Section_ID not between", value1, value2, "sectionId");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNull() {
            addCriterion("Project_ID is null");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNotNull() {
            addCriterion("Project_ID is not null");
            return (Criteria) this;
        }

        public Criteria andProjectIdEqualTo(Integer value) {
            addCriterion("Project_ID =", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotEqualTo(Integer value) {
            addCriterion("Project_ID <>", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThan(Integer value) {
            addCriterion("Project_ID >", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("Project_ID >=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThan(Integer value) {
            addCriterion("Project_ID <", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThanOrEqualTo(Integer value) {
            addCriterion("Project_ID <=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdIn(List<Integer> values) {
            addCriterion("Project_ID in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotIn(List<Integer> values) {
            addCriterion("Project_ID not in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdBetween(Integer value1, Integer value2) {
            addCriterion("Project_ID between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotBetween(Integer value1, Integer value2) {
            addCriterion("Project_ID not between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andSectionNameIsNull() {
            addCriterion("Section_Name is null");
            return (Criteria) this;
        }

        public Criteria andSectionNameIsNotNull() {
            addCriterion("Section_Name is not null");
            return (Criteria) this;
        }

        public Criteria andSectionNameEqualTo(String value) {
            addCriterion("Section_Name =", value, "sectionName");
            return (Criteria) this;
        }

        public Criteria andSectionNameNotEqualTo(String value) {
            addCriterion("Section_Name <>", value, "sectionName");
            return (Criteria) this;
        }

        public Criteria andSectionNameGreaterThan(String value) {
            addCriterion("Section_Name >", value, "sectionName");
            return (Criteria) this;
        }

        public Criteria andSectionNameGreaterThanOrEqualTo(String value) {
            addCriterion("Section_Name >=", value, "sectionName");
            return (Criteria) this;
        }

        public Criteria andSectionNameLessThan(String value) {
            addCriterion("Section_Name <", value, "sectionName");
            return (Criteria) this;
        }

        public Criteria andSectionNameLessThanOrEqualTo(String value) {
            addCriterion("Section_Name <=", value, "sectionName");
            return (Criteria) this;
        }

        public Criteria andSectionNameLike(String value) {
            addCriterion("Section_Name like", value, "sectionName");
            return (Criteria) this;
        }

        public Criteria andSectionNameNotLike(String value) {
            addCriterion("Section_Name not like", value, "sectionName");
            return (Criteria) this;
        }

        public Criteria andSectionNameIn(List<String> values) {
            addCriterion("Section_Name in", values, "sectionName");
            return (Criteria) this;
        }

        public Criteria andSectionNameNotIn(List<String> values) {
            addCriterion("Section_Name not in", values, "sectionName");
            return (Criteria) this;
        }

        public Criteria andSectionNameBetween(String value1, String value2) {
            addCriterion("Section_Name between", value1, value2, "sectionName");
            return (Criteria) this;
        }

        public Criteria andSectionNameNotBetween(String value1, String value2) {
            addCriterion("Section_Name not between", value1, value2, "sectionName");
            return (Criteria) this;
        }

        public Criteria andSectionLeaderIsNull() {
            addCriterion("Section_Leader is null");
            return (Criteria) this;
        }

        public Criteria andSectionLeaderIsNotNull() {
            addCriterion("Section_Leader is not null");
            return (Criteria) this;
        }

        public Criteria andSectionLeaderEqualTo(String value) {
            addCriterion("Section_Leader =", value, "sectionLeader");
            return (Criteria) this;
        }

        public Criteria andSectionLeaderNotEqualTo(String value) {
            addCriterion("Section_Leader <>", value, "sectionLeader");
            return (Criteria) this;
        }

        public Criteria andSectionLeaderGreaterThan(String value) {
            addCriterion("Section_Leader >", value, "sectionLeader");
            return (Criteria) this;
        }

        public Criteria andSectionLeaderGreaterThanOrEqualTo(String value) {
            addCriterion("Section_Leader >=", value, "sectionLeader");
            return (Criteria) this;
        }

        public Criteria andSectionLeaderLessThan(String value) {
            addCriterion("Section_Leader <", value, "sectionLeader");
            return (Criteria) this;
        }

        public Criteria andSectionLeaderLessThanOrEqualTo(String value) {
            addCriterion("Section_Leader <=", value, "sectionLeader");
            return (Criteria) this;
        }

        public Criteria andSectionLeaderLike(String value) {
            addCriterion("Section_Leader like", value, "sectionLeader");
            return (Criteria) this;
        }

        public Criteria andSectionLeaderNotLike(String value) {
            addCriterion("Section_Leader not like", value, "sectionLeader");
            return (Criteria) this;
        }

        public Criteria andSectionLeaderIn(List<String> values) {
            addCriterion("Section_Leader in", values, "sectionLeader");
            return (Criteria) this;
        }

        public Criteria andSectionLeaderNotIn(List<String> values) {
            addCriterion("Section_Leader not in", values, "sectionLeader");
            return (Criteria) this;
        }

        public Criteria andSectionLeaderBetween(String value1, String value2) {
            addCriterion("Section_Leader between", value1, value2, "sectionLeader");
            return (Criteria) this;
        }

        public Criteria andSectionLeaderNotBetween(String value1, String value2) {
            addCriterion("Section_Leader not between", value1, value2, "sectionLeader");
            return (Criteria) this;
        }

        public Criteria andProjectNameIsNull() {
            addCriterion("Project_Name is null");
            return (Criteria) this;
        }

        public Criteria andProjectNameIsNotNull() {
            addCriterion("Project_Name is not null");
            return (Criteria) this;
        }

        public Criteria andProjectNameEqualTo(String value) {
            addCriterion("Project_Name =", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameNotEqualTo(String value) {
            addCriterion("Project_Name <>", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameGreaterThan(String value) {
            addCriterion("Project_Name >", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameGreaterThanOrEqualTo(String value) {
            addCriterion("Project_Name >=", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameLessThan(String value) {
            addCriterion("Project_Name <", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameLessThanOrEqualTo(String value) {
            addCriterion("Project_Name <=", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameLike(String value) {
            addCriterion("Project_Name like", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameNotLike(String value) {
            addCriterion("Project_Name not like", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameIn(List<String> values) {
            addCriterion("Project_Name in", values, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameNotIn(List<String> values) {
            addCriterion("Project_Name not in", values, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameBetween(String value1, String value2) {
            addCriterion("Project_Name between", value1, value2, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameNotBetween(String value1, String value2) {
            addCriterion("Project_Name not between", value1, value2, "projectName");
            return (Criteria) this;
        }

        public Criteria andExpectWaterAmountIsNull() {
            addCriterion("Expect_Water_Amount is null");
            return (Criteria) this;
        }

        public Criteria andExpectWaterAmountIsNotNull() {
            addCriterion("Expect_Water_Amount is not null");
            return (Criteria) this;
        }

        public Criteria andExpectWaterAmountEqualTo(Integer value) {
            addCriterion("Expect_Water_Amount =", value, "expectWaterAmount");
            return (Criteria) this;
        }

        public Criteria andExpectWaterAmountNotEqualTo(Integer value) {
            addCriterion("Expect_Water_Amount <>", value, "expectWaterAmount");
            return (Criteria) this;
        }

        public Criteria andExpectWaterAmountGreaterThan(Integer value) {
            addCriterion("Expect_Water_Amount >", value, "expectWaterAmount");
            return (Criteria) this;
        }

        public Criteria andExpectWaterAmountGreaterThanOrEqualTo(Integer value) {
            addCriterion("Expect_Water_Amount >=", value, "expectWaterAmount");
            return (Criteria) this;
        }

        public Criteria andExpectWaterAmountLessThan(Integer value) {
            addCriterion("Expect_Water_Amount <", value, "expectWaterAmount");
            return (Criteria) this;
        }

        public Criteria andExpectWaterAmountLessThanOrEqualTo(Integer value) {
            addCriterion("Expect_Water_Amount <=", value, "expectWaterAmount");
            return (Criteria) this;
        }

        public Criteria andExpectWaterAmountIn(List<Integer> values) {
            addCriterion("Expect_Water_Amount in", values, "expectWaterAmount");
            return (Criteria) this;
        }

        public Criteria andExpectWaterAmountNotIn(List<Integer> values) {
            addCriterion("Expect_Water_Amount not in", values, "expectWaterAmount");
            return (Criteria) this;
        }

        public Criteria andExpectWaterAmountBetween(Integer value1, Integer value2) {
            addCriterion("Expect_Water_Amount between", value1, value2, "expectWaterAmount");
            return (Criteria) this;
        }

        public Criteria andExpectWaterAmountNotBetween(Integer value1, Integer value2) {
            addCriterion("Expect_Water_Amount not between", value1, value2, "expectWaterAmount");
            return (Criteria) this;
        }

        public Criteria andExpectCementAmountIsNull() {
            addCriterion("Expect_Cement_Amount is null");
            return (Criteria) this;
        }

        public Criteria andExpectCementAmountIsNotNull() {
            addCriterion("Expect_Cement_Amount is not null");
            return (Criteria) this;
        }

        public Criteria andExpectCementAmountEqualTo(Integer value) {
            addCriterion("Expect_Cement_Amount =", value, "expectCementAmount");
            return (Criteria) this;
        }

        public Criteria andExpectCementAmountNotEqualTo(Integer value) {
            addCriterion("Expect_Cement_Amount <>", value, "expectCementAmount");
            return (Criteria) this;
        }

        public Criteria andExpectCementAmountGreaterThan(Integer value) {
            addCriterion("Expect_Cement_Amount >", value, "expectCementAmount");
            return (Criteria) this;
        }

        public Criteria andExpectCementAmountGreaterThanOrEqualTo(Integer value) {
            addCriterion("Expect_Cement_Amount >=", value, "expectCementAmount");
            return (Criteria) this;
        }

        public Criteria andExpectCementAmountLessThan(Integer value) {
            addCriterion("Expect_Cement_Amount <", value, "expectCementAmount");
            return (Criteria) this;
        }

        public Criteria andExpectCementAmountLessThanOrEqualTo(Integer value) {
            addCriterion("Expect_Cement_Amount <=", value, "expectCementAmount");
            return (Criteria) this;
        }

        public Criteria andExpectCementAmountIn(List<Integer> values) {
            addCriterion("Expect_Cement_Amount in", values, "expectCementAmount");
            return (Criteria) this;
        }

        public Criteria andExpectCementAmountNotIn(List<Integer> values) {
            addCriterion("Expect_Cement_Amount not in", values, "expectCementAmount");
            return (Criteria) this;
        }

        public Criteria andExpectCementAmountBetween(Integer value1, Integer value2) {
            addCriterion("Expect_Cement_Amount between", value1, value2, "expectCementAmount");
            return (Criteria) this;
        }

        public Criteria andExpectCementAmountNotBetween(Integer value1, Integer value2) {
            addCriterion("Expect_Cement_Amount not between", value1, value2, "expectCementAmount");
            return (Criteria) this;
        }

        public Criteria andRealWaterAmountIsNull() {
            addCriterion("Real_Water_Amount is null");
            return (Criteria) this;
        }

        public Criteria andRealWaterAmountIsNotNull() {
            addCriterion("Real_Water_Amount is not null");
            return (Criteria) this;
        }

        public Criteria andRealWaterAmountEqualTo(Integer value) {
            addCriterion("Real_Water_Amount =", value, "realWaterAmount");
            return (Criteria) this;
        }

        public Criteria andRealWaterAmountNotEqualTo(Integer value) {
            addCriterion("Real_Water_Amount <>", value, "realWaterAmount");
            return (Criteria) this;
        }

        public Criteria andRealWaterAmountGreaterThan(Integer value) {
            addCriterion("Real_Water_Amount >", value, "realWaterAmount");
            return (Criteria) this;
        }

        public Criteria andRealWaterAmountGreaterThanOrEqualTo(Integer value) {
            addCriterion("Real_Water_Amount >=", value, "realWaterAmount");
            return (Criteria) this;
        }

        public Criteria andRealWaterAmountLessThan(Integer value) {
            addCriterion("Real_Water_Amount <", value, "realWaterAmount");
            return (Criteria) this;
        }

        public Criteria andRealWaterAmountLessThanOrEqualTo(Integer value) {
            addCriterion("Real_Water_Amount <=", value, "realWaterAmount");
            return (Criteria) this;
        }

        public Criteria andRealWaterAmountIn(List<Integer> values) {
            addCriterion("Real_Water_Amount in", values, "realWaterAmount");
            return (Criteria) this;
        }

        public Criteria andRealWaterAmountNotIn(List<Integer> values) {
            addCriterion("Real_Water_Amount not in", values, "realWaterAmount");
            return (Criteria) this;
        }

        public Criteria andRealWaterAmountBetween(Integer value1, Integer value2) {
            addCriterion("Real_Water_Amount between", value1, value2, "realWaterAmount");
            return (Criteria) this;
        }

        public Criteria andRealWaterAmountNotBetween(Integer value1, Integer value2) {
            addCriterion("Real_Water_Amount not between", value1, value2, "realWaterAmount");
            return (Criteria) this;
        }

        public Criteria andRealCementAmountIsNull() {
            addCriterion("Real_Cement_Amount is null");
            return (Criteria) this;
        }

        public Criteria andRealCementAmountIsNotNull() {
            addCriterion("Real_Cement_Amount is not null");
            return (Criteria) this;
        }

        public Criteria andRealCementAmountEqualTo(Integer value) {
            addCriterion("Real_Cement_Amount =", value, "realCementAmount");
            return (Criteria) this;
        }

        public Criteria andRealCementAmountNotEqualTo(Integer value) {
            addCriterion("Real_Cement_Amount <>", value, "realCementAmount");
            return (Criteria) this;
        }

        public Criteria andRealCementAmountGreaterThan(Integer value) {
            addCriterion("Real_Cement_Amount >", value, "realCementAmount");
            return (Criteria) this;
        }

        public Criteria andRealCementAmountGreaterThanOrEqualTo(Integer value) {
            addCriterion("Real_Cement_Amount >=", value, "realCementAmount");
            return (Criteria) this;
        }

        public Criteria andRealCementAmountLessThan(Integer value) {
            addCriterion("Real_Cement_Amount <", value, "realCementAmount");
            return (Criteria) this;
        }

        public Criteria andRealCementAmountLessThanOrEqualTo(Integer value) {
            addCriterion("Real_Cement_Amount <=", value, "realCementAmount");
            return (Criteria) this;
        }

        public Criteria andRealCementAmountIn(List<Integer> values) {
            addCriterion("Real_Cement_Amount in", values, "realCementAmount");
            return (Criteria) this;
        }

        public Criteria andRealCementAmountNotIn(List<Integer> values) {
            addCriterion("Real_Cement_Amount not in", values, "realCementAmount");
            return (Criteria) this;
        }

        public Criteria andRealCementAmountBetween(Integer value1, Integer value2) {
            addCriterion("Real_Cement_Amount between", value1, value2, "realCementAmount");
            return (Criteria) this;
        }

        public Criteria andRealCementAmountNotBetween(Integer value1, Integer value2) {
            addCriterion("Real_Cement_Amount not between", value1, value2, "realCementAmount");
            return (Criteria) this;
        }

        public Criteria andRealCement2AmountIsNull() {
            addCriterion("Real_Cement2_Amount is null");
            return (Criteria) this;
        }

        public Criteria andRealCement2AmountIsNotNull() {
            addCriterion("Real_Cement2_Amount is not null");
            return (Criteria) this;
        }

        public Criteria andRealCement2AmountEqualTo(Integer value) {
            addCriterion("Real_Cement2_Amount =", value, "realCement2Amount");
            return (Criteria) this;
        }

        public Criteria andRealCement2AmountNotEqualTo(Integer value) {
            addCriterion("Real_Cement2_Amount <>", value, "realCement2Amount");
            return (Criteria) this;
        }

        public Criteria andRealCement2AmountGreaterThan(Integer value) {
            addCriterion("Real_Cement2_Amount >", value, "realCement2Amount");
            return (Criteria) this;
        }

        public Criteria andRealCement2AmountGreaterThanOrEqualTo(Integer value) {
            addCriterion("Real_Cement2_Amount >=", value, "realCement2Amount");
            return (Criteria) this;
        }

        public Criteria andRealCement2AmountLessThan(Integer value) {
            addCriterion("Real_Cement2_Amount <", value, "realCement2Amount");
            return (Criteria) this;
        }

        public Criteria andRealCement2AmountLessThanOrEqualTo(Integer value) {
            addCriterion("Real_Cement2_Amount <=", value, "realCement2Amount");
            return (Criteria) this;
        }

        public Criteria andRealCement2AmountIn(List<Integer> values) {
            addCriterion("Real_Cement2_Amount in", values, "realCement2Amount");
            return (Criteria) this;
        }

        public Criteria andRealCement2AmountNotIn(List<Integer> values) {
            addCriterion("Real_Cement2_Amount not in", values, "realCement2Amount");
            return (Criteria) this;
        }

        public Criteria andRealCement2AmountBetween(Integer value1, Integer value2) {
            addCriterion("Real_Cement2_Amount between", value1, value2, "realCement2Amount");
            return (Criteria) this;
        }

        public Criteria andRealCement2AmountNotBetween(Integer value1, Integer value2) {
            addCriterion("Real_Cement2_Amount not between", value1, value2, "realCement2Amount");
            return (Criteria) this;
        }

        public Criteria andRealSlurryAmountIsNull() {
            addCriterion("Real_Slurry_Amount is null");
            return (Criteria) this;
        }

        public Criteria andRealSlurryAmountIsNotNull() {
            addCriterion("Real_Slurry_Amount is not null");
            return (Criteria) this;
        }

        public Criteria andRealSlurryAmountEqualTo(Integer value) {
            addCriterion("Real_Slurry_Amount =", value, "realSlurryAmount");
            return (Criteria) this;
        }

        public Criteria andRealSlurryAmountNotEqualTo(Integer value) {
            addCriterion("Real_Slurry_Amount <>", value, "realSlurryAmount");
            return (Criteria) this;
        }

        public Criteria andRealSlurryAmountGreaterThan(Integer value) {
            addCriterion("Real_Slurry_Amount >", value, "realSlurryAmount");
            return (Criteria) this;
        }

        public Criteria andRealSlurryAmountGreaterThanOrEqualTo(Integer value) {
            addCriterion("Real_Slurry_Amount >=", value, "realSlurryAmount");
            return (Criteria) this;
        }

        public Criteria andRealSlurryAmountLessThan(Integer value) {
            addCriterion("Real_Slurry_Amount <", value, "realSlurryAmount");
            return (Criteria) this;
        }

        public Criteria andRealSlurryAmountLessThanOrEqualTo(Integer value) {
            addCriterion("Real_Slurry_Amount <=", value, "realSlurryAmount");
            return (Criteria) this;
        }

        public Criteria andRealSlurryAmountIn(List<Integer> values) {
            addCriterion("Real_Slurry_Amount in", values, "realSlurryAmount");
            return (Criteria) this;
        }

        public Criteria andRealSlurryAmountNotIn(List<Integer> values) {
            addCriterion("Real_Slurry_Amount not in", values, "realSlurryAmount");
            return (Criteria) this;
        }

        public Criteria andRealSlurryAmountBetween(Integer value1, Integer value2) {
            addCriterion("Real_Slurry_Amount between", value1, value2, "realSlurryAmount");
            return (Criteria) this;
        }

        public Criteria andRealSlurryAmountNotBetween(Integer value1, Integer value2) {
            addCriterion("Real_Slurry_Amount not between", value1, value2, "realSlurryAmount");
            return (Criteria) this;
        }

        public Criteria andWaterCementRatioIsNull() {
            addCriterion("Water_Cement_Ratio is null");
            return (Criteria) this;
        }

        public Criteria andWaterCementRatioIsNotNull() {
            addCriterion("Water_Cement_Ratio is not null");
            return (Criteria) this;
        }

        public Criteria andWaterCementRatioEqualTo(BigDecimal value) {
            addCriterion("Water_Cement_Ratio =", value, "waterCementRatio");
            return (Criteria) this;
        }

        public Criteria andWaterCementRatioNotEqualTo(BigDecimal value) {
            addCriterion("Water_Cement_Ratio <>", value, "waterCementRatio");
            return (Criteria) this;
        }

        public Criteria andWaterCementRatioGreaterThan(BigDecimal value) {
            addCriterion("Water_Cement_Ratio >", value, "waterCementRatio");
            return (Criteria) this;
        }

        public Criteria andWaterCementRatioGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("Water_Cement_Ratio >=", value, "waterCementRatio");
            return (Criteria) this;
        }

        public Criteria andWaterCementRatioLessThan(BigDecimal value) {
            addCriterion("Water_Cement_Ratio <", value, "waterCementRatio");
            return (Criteria) this;
        }

        public Criteria andWaterCementRatioLessThanOrEqualTo(BigDecimal value) {
            addCriterion("Water_Cement_Ratio <=", value, "waterCementRatio");
            return (Criteria) this;
        }

        public Criteria andWaterCementRatioIn(List<BigDecimal> values) {
            addCriterion("Water_Cement_Ratio in", values, "waterCementRatio");
            return (Criteria) this;
        }

        public Criteria andWaterCementRatioNotIn(List<BigDecimal> values) {
            addCriterion("Water_Cement_Ratio not in", values, "waterCementRatio");
            return (Criteria) this;
        }

        public Criteria andWaterCementRatioBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Water_Cement_Ratio between", value1, value2, "waterCementRatio");
            return (Criteria) this;
        }

        public Criteria andWaterCementRatioNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Water_Cement_Ratio not between", value1, value2, "waterCementRatio");
            return (Criteria) this;
        }

        public Criteria andDensityIsNull() {
            addCriterion("Density is null");
            return (Criteria) this;
        }

        public Criteria andDensityIsNotNull() {
            addCriterion("Density is not null");
            return (Criteria) this;
        }

        public Criteria andDensityEqualTo(BigDecimal value) {
            addCriterion("Density =", value, "density");
            return (Criteria) this;
        }

        public Criteria andDensityNotEqualTo(BigDecimal value) {
            addCriterion("Density <>", value, "density");
            return (Criteria) this;
        }

        public Criteria andDensityGreaterThan(BigDecimal value) {
            addCriterion("Density >", value, "density");
            return (Criteria) this;
        }

        public Criteria andDensityGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("Density >=", value, "density");
            return (Criteria) this;
        }

        public Criteria andDensityLessThan(BigDecimal value) {
            addCriterion("Density <", value, "density");
            return (Criteria) this;
        }

        public Criteria andDensityLessThanOrEqualTo(BigDecimal value) {
            addCriterion("Density <=", value, "density");
            return (Criteria) this;
        }

        public Criteria andDensityIn(List<BigDecimal> values) {
            addCriterion("Density in", values, "density");
            return (Criteria) this;
        }

        public Criteria andDensityNotIn(List<BigDecimal> values) {
            addCriterion("Density not in", values, "density");
            return (Criteria) this;
        }

        public Criteria andDensityBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Density between", value1, value2, "density");
            return (Criteria) this;
        }

        public Criteria andDensityNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Density not between", value1, value2, "density");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_luding_slurry_amount
     *
     * @mbg.generated do_not_delete_during_merge Tue Dec 27 12:28:42 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_luding_slurry_amount
     *
     * @mbg.generated Tue Dec 27 12:28:42 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}